### ISSUE TITLE
Windows 10 (UWP) Support

### ISSUE THREAD

**Issue by levginsburg** [xamarin/Xamarin.Auth#100]
Any chance Windows 10 support might be added soon?

**Comment by tuath** [comment]
Yep, any news ? authorization is the first step in a client-server system !!!

**Comment by JKennedy24** [comment]
Any progress on this?

**Comment by dengere** [comment]
how we can display login page on UWP? never?

**Comment by ravensorb** [comment]
Would be great to see an update for Windows Mobile

**Comment by JoeM-RP** [comment]
Would love to see this for UWP too

**Comment by herbutant** [comment]
+1 
what's up with v1.3.0 in that respect?

**Comment by yufeih** [comment]
On UWP, you can use WebAuthenticationBroker https://msdn.microsoft.com/en-us/library/windows/apps/dn608116.aspx

**Comment by DamianMehers** [comment]
Until it is supported, I've put together this example using WebAuthenticationBroker with Xamarin.Auth http://damianblog.com/2016/09/04/uwp-oauth-in-xamarin-forms-using-xamarin-auth/

**Comment by mdonogma** [comment]
this stopped working after November 1 2016 for google. check this out: https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

when can we expect update to component

**Comment by mdonogma** [comment]
UWP support please as part of standard component please.

**Comment by BenDevelopment** [comment]
No news about that ?

**Comment by Brosten** [comment]
Yes, please! Add UWP support ASAP!

**Comment by moljac** [comment]
Please check Xamarin.Auth nuget v. 1.3.2. it has UWP support. UWP support was added a long time ago. The "only" problem were the CI process and build servers that were not able to compile/build, package and publish nupkg with UWP support. This was solved 2016-12 (before Xmas) and published recently.

https://www.nuget.org/packages/Xamarin.Auth/1.3.2

Closing.

**Comment by jssuthahar** [comment]
can you please share code for implement UWP

**Comment by johnshardman** [comment]
Is there a sample project for UWP?

**Comment by JKennedy24** [comment]
Wheres the src for UWP?

**Comment by moljac** [comment]
For source check the "portable-bait-and-switch" branch:

https://github.com/xamarin/Xamarin.Auth/tree/portable-bait-and-switch

source:

https://github.com/xamarin/Xamarin.Auth/tree/portable-bait-and-switch/source

Sample:

Samples for 15+ providers:

https://github.com/xamarin/Xamarin.Auth/tree/portable-bait-and-switch/samples/Traditional.Standard/references01projects/Providers

UWP sample:
https://github.com/xamarin/Xamarin.Auth/tree/portable-bait-and-switch/samples/Traditional.Standard/references01projects/Providers/Xamarin.Auth.Sample.UniversalWindowsPlatform

**Comment by jssuthahar** [comment]
Xamarin.Auth 1.3.2 version was support UWP app. I have created and implemented app in Android and IOS like below

**PresentViewController (auth.GetUI (), true, null);**

and for Android:

**StartActivity (auth.GetUI (this));**

I want to get know how to use auth.GetUI() in xamarin.Form UWP PageRenderer.

**Comment by moljac** [comment]
Here it is:
https://github.com/xamarin/Xamarin.Auth/blob/portable-bait-and-switch/samples/Traditional.Standard/references01projects/Providers/Xamarin.Auth.Sample.UniversalWindowsPlatform/MainPage.Xamarin.Auth.xaml.cs#L64

Please test it and report whether it works or not. There are fixed several issues that were fixed in last few days and new nuget is on the way.

**Comment by jssuthahar** [comment]
Hi moljac,

The above example is platform specific code .I have created Xamarin Form Application for  Login and added PageRenderer for iOS  and Android but I want to know how to use  PageRenderer with Xamarin .Auth in UWP

**Comment by johnshardman** [comment]
@jssuthahar - Did you work out how to do this from a generic Xamarin.Forms page on UWP?

**Comment by moljac** [comment]
@johnshardman 
Morn
No I did not (yet).
I did Xamarin.Forms Custom Renderers for Xamarn.Auth somewhere in 2015-01 through 2015-04 and never had a chance to touch it. Sorry.
It is on my list of improvements, but a lot to do before that.
My sample is  for UWP not Xamarin.Forms UWP and navigation concepts might miss something for Xamarin.Forms. If  you have any suggestion let me know.

**Comment by johnshardman** [comment]
@moljac - I've got it mostly working on UWP, using a custom page renderer. However, pressing the "Back" button on the bar at the top of the WebAuthenticatorPage is resulting in an exception being thrown. It's a generic E_FAIL exception, but looking quickly at the Xamarin.Auth code, I suspect Xamarin.Auth is trying to do navigation from a thread other than the UI thread.

**Comment by moljac** [comment]
Added Dispatcher.RunAsync in UWP nuget 1.3.2.7

**Comment by taublast** [comment]
As @johnshardman previously said, it's actually unusable on UWP version 1.5.03: 
when a user cancels the login process it randomly crashes after few open-cancel actions.
Non-native views ofc.
