### ISSUE TITLE
Authenticator.BeginInvokeOnUIThread may need WinPhone support added?

### ISSUE THREAD

**Issue by marktap** [xamarin/Xamarin.Auth#101]
In Authenticator.cs, the BeginInvokeOnUIThread method currently has iOS and Android support. I think this will need WinPhone support added unless invoking the action directly will work (i.e. the last '#else')? Here's the current code:

void BeginInvokeOnUIThread (Action action)
{
            #if PLATFORM_IOS || **IOS**
            #if !**UNIFIED**
            MonoTouch.
            #endif
            UIKit.UIApplication.SharedApplication.BeginInvokeOnMainThread 
                (
                    delegate { action (); }
                );
            #elif PLATFORM_ANDROID || **ANDROID**
            var a = context as Android.App.Activity;
            if (a != null) {
                a.RunOnUiThread (action);
            }
            else {
                action ();
            }
            #else
            action ();
            #endif
}

**Comment by newky2k** [comment]
@marktap this appears to be have been implemented now as there have been changes to how it runs on the UI thread
https://github.com/xamarin/Xamarin.Auth/blob/d592c51a6f91aa073f0c1be8a768c464aa6e62a7/source/Core/Xamarin.Auth.WindowsPhone8/Plugins/UIThreadRunInvoker.WindowsPhone8.cs
