### ISSUE TITLE
OAuth2Authenticator.RequestRefreshTokenAsync could raise the Error event?

### ISSUE THREAD

**Issue by marktap** [xamarin/Xamarin.Auth#102]
The OAuth2Autheticator.RequestRefreshTokenAsync method currently throws an exception if the refresh fails. This is different behavior than the initial authentication/authorization flow that raises the Error event.

We could modify the code to raise the Error event? This would be an interface change; however, it would make the interface more consistent so it might be worth doing. It is easier to learn if we can say "errors are always reported via the Error event" rather than "sometimes errors are reported via the Error event and sometimes it throws exceptions".

Here's a possibility for an updated implementation:

public async virtual Task<int> RequestRefreshTokenAsync(string refreshToken)
        {
            var queryValues = new Dictionary<string, string>
            {
                { "refresh_token", refreshToken    },
                { "client_id",     this.ClientId   },
                { "grant_type",    "refresh_token" }
            };

```
        if (!string.IsNullOrEmpty(this.ClientSecret))
        {
            queryValues["client_secret"] = this.ClientSecret;
        }

        try
        {
            var accountProperties = await RequestAccessTokenAsync(queryValues).ConfigureAwait(false);

            this.OnRetrievedAccountProperties(accountProperties);

            return int.Parse(accountProperties["expires_in"]);
        }
        catch (Exception e)
        {
            OnError(e);

            throw; // maybe don't need this? this will throw the exception in order to maintain backward compatibility, but maybe could just return -1 or something instead?
        }
    }
```

**Comment by newky2k** [comment]
@marktap This code has now changed -> https://github.com/xamarin/Xamarin.Auth/blob/d592c51a6f91aa073f0c1be8a768c464aa6e62a7/source/Extensions/Xamarin.Auth.Extensions.LinkSource/OAuth2AuthenticatorExtensions.cs#L43

The authenticator now handles failed responsed

**Comment by suyashgupta25** [comment]
@newky2k : This issue is still happening in version 1.6.0.3
Please review it once.
