### ISSUE TITLE
Authenticate label header

### ISSUE THREAD

**Issue by remiroyc** [xamarin/Xamarin.Auth#106]
It would be great if we need customize label header (Authenticate) or better.. just hide it.

http://image.noelshack.com/fichiers/2016/07/1455899042-screenshot-2016-02-19-17-17-17.png

``` C#
        /// <summary>
        /// Initializes a new instance of the <see cref="Xamarin.Auth.Authenticator"/> class.
        /// </summary>
        public Authenticator ()
        {
            Title = "Authenticate";
            HasCompleted = false;
            AllowCancel = true;
        }
```

and add a timeout connection.

http://image.noelshack.com/fichiers/2016/07/1455899042-screenshot-2016-02-19-17-16-55.png

Thank you. Best regards,

**Comment by newky2k** [comment]
@remiroyc  Title is s public property so you should be able to set it to what ever you want
