### ISSUE TITLE
Authentication issue in twitter android.

### ISSUE THREAD

**Issue by vinodh06** [xamarin/Xamarin.Auth#107]
After successfully authenticated in twitter using xamarin.auth,My app getting crashed and the eror message is "Android.Views.WindowManagerBadTokenException: Unable to add window -- token android.os.BinderProxy@41ac6788 is not valid; is your activity running?".
Please help me to fix these.
Thanks

**Comment by fbencosme** [comment]
Any updates on this?
I am having the same issue =/

**Comment by newky2k** [comment]
@vinodh06  is this still an issue?

**Comment by newky2k** [comment]
No response for two weeks closing
