### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by erictrinh276** [xamarin/Xamarin.Auth#112]
Hi,
I'm using Xamarin.Auth to authenticate users with OAuth2. But the component doesn't seem to accept refresh_token which is important to keep users logged in without asking them to re-log in.
Is this feature currently not supported?

**Comment by hvaughan3** [comment]
See [#79](https://github.com/xamarin/Xamarin.Auth/pull/79)

**Comment by erictrinh276** [comment]
Thanks @hvaughan3
