### ISSUE TITLE
SECURITY WARNING - Android and iOS

### ISSUE THREAD

**Issue by jzeferino** [xamarin/Xamarin.Auth#113]
Im using the Xamarin.Auth to login with facebook.
Everything works good for the first time.
But after i log out and try to login again with the same account i got:
**Success
SECURITY WARNING: Please treat the URL above as you would your password and do not share it with anyone. See the Facebook Help Center for more information.**

The `Completed` callback isn't called in the second time.

Im using the following urls:

```
authorizeUrl: new Uri("https://m.facebook.com/dialog/oauth/"),
redirectUrl: new Uri("http://www.facebook.com/connect/login_success.html"));
```

Any suggestion?

**Comment by sp3ci** [comment]
I have tried to use Xamarin.Auth and the Facebook SDK for Android and in my experience neither works at the moment.

It seems that the web view or similar gets closed before it has given a response to the Xamarin application.

**Comment by jzeferino** [comment]
I'm only using the Xamarin.Auth. But i don't want to use Facebook SDK.
With Xamarin.Auth i can authenticate with facebook or other entity using OAuth protocol.
