### ISSUE TITLE
Endless loop to POST “/oauth/token” after successful login (Android only)

### ISSUE THREAD

**Issue by deepinderCognitive** [xamarin/Xamarin.Auth#114]
I am building an app using **_Xamarin forms_** and first step of app is to validate user using **_OAuth2_**. In order to achieve this I am using **_Xamarin.Auth_** library (1.3.0) and implemented it exactly how xamarin docs have recommended. Note: I have tried Xamarin.Auth 1.2.2 also and same issue is there too. Now when I run the app everything works fine, as expected in iOS app. But on Android app when I login I get successful authentication flag with access token and application moves to next screen, but in background library keeps making call to POST "/oauth/token" which I have no idea why its happening and this POST call is happening only once for iOS (expected behaviour).

When I dig little bit more in server logs and compared what iOS and Android server calls look like and found that once Android had completed validation and got success callback it creates another call for POST "**_/oauth/token_**" with "**_access grant code_**" that was already used and hence returns "**_401 Unauthorized_**". Now at this point Xamarin.Auth library gets in bad state keeps trying to do the same thing again and again. Eventually after some time app goes out of memory and crashes.

Is this the Xamarin.Auth issue? Has anyone else encountered same issue? Is there a solution for this?

I have tried to find out solution online but without any luck. Any help will be highly appreciated.

Just an FYI - server side we have Oauth2 implemented using [Doorkeeper Gem.](https://github.com/doorkeeper-gem/doorkeeper)

Here is the [server log for Android.](https://drive.google.com/open?id=0B8R82VrIDmL5cmFwdUdUdTJROVU)

**Comment by deepinderCognitive** [comment]
Did anyone got chance to look into this?

**Comment by nhinze** [comment]
I'm seeing the same issue. Also using doorkeeper gem

**Comment by miiitch** [comment]
Same issue for me. endless loop.

**Comment by nhinze** [comment]
I got this to work just fine by using:

Xamarin.Auth 1.3.1.1

**Comment by miiitch** [comment]
I have the issue in 1.3.1.1

**Comment by nhinze** [comment]
I think I did have the issue using the "access grant code" flow. After some reading, mobile apps should use the "implicit flow", because the secret key can't be store securely in the code.
Also, if you use HTTPS, Android has many issues and you have to use Android 5+.

**Comment by miiitch** [comment]
This is not so simple (https://leastprivilege.com/2016/01/17/which-openid-connectoauth-2-o-flow-is-the-right-one/). authorization code allows you to connect with third party provider this is a good thing for security

**Comment by newky2k** [comment]
@deepinderCognitive @nhinze @miiitch We are on version 1.6.x now.  Can you check to see if this is still an issue

**Comment by newky2k** [comment]
No response for two weeks, closing
