### ISSUE TITLE
Xamarin.Auth + TLS 1.2 (CloudFlare SSL)

### ISSUE THREAD

**Issue by nhinze** [xamarin/Xamarin.Auth#115]
I'm having issues authenticating to TLS 1.2 HTTPS sites using Android. I get the following error:

ERROR Error: SecureChannelFailure (The authentication or decryption has failed.)

I use Xamarin.Auth 1.3 .

On iOS I was able to bypass the problem by selecting:
- HttpClient implementation: NSUrlSession
- SSL/TLS implementation: Apple TLS
in the project options.

Are there Android specific options also to support TLS 1.2?

**Comment by nhinze** [comment]
This issue appears resolved with Xamarin.Auth 1.3.1 alpha-2 and using the XA_HTTP_CLIENT_HANDLER_TYPE environment variable:

https://developer.xamarin.com/guides/cross-platform/transport-layer-security/

**Comment by moljac** [comment]
Can you check 1.3.1 alpha-03 please and confirm if it is solved, so this issue can be closed.

thanks

**Comment by nhinze** [comment]
Xamarin.Auth is not really at fault here. To get it to work with TLS 1.2 and Android you need to set:
- XA_HTTP_CLIENT_HANDLER_TYPE environment variable: https://developer.xamarin.com/guides/cross-platform/transport-layer-security/
- Select "AndroidClientHandler" in HttpClient implementation in the XS Android Build options.
- If using the Linker, you need to add "using Xamarin.Android.Net;" somewhere in your Android project so that the linker does not remove this library.
