### ISSUE TITLE
Google Auth - unsupported_response_type

### ISSUE THREAD

**Issue by golfguy0082** [xamarin/Xamarin.Auth#116]
I'm currently using the following code to attempt to authenticate with google.

var auth = new OAuth2Authenticator(
                "clientId",
                "openid email",
                new Uri("https://accounts.google.com/o/oauth2/auth"),
                new Uri("http://localhost"));

However, after entering my password, I receive an error: "unsupported_response_type".  Any ideas on how to move forward?  I've seen some other people having the same problem that suggest registering a "web" client in the google console instead of the "android" client, but I don't want to do that because it requires embedding a client secret in my android app (which is insecure).  It seems like there should be a better way to get this working.  Any ideas?

**Comment by MirzaSikander** [comment]
Why do you think that embedding a client secret is insecure? Even if somebody gets access to it, all they can do is impersonate your app, but nothing more. If they create a malicious app then its the users fault for installing it. If they create a webservice then your redirect URL would prevent them from getting the Auth token.

**Comment by golfguy0082** [comment]
Someone else impersonating my app is still not ideal, right (even if the impact is maybe minimal)?  Perhaps the answer is "there is no other way right now", and that's an acceptable answer.  I'm really looking for confirmation one way or the other, but I don't want to give up without pursuing the best path possible.  If this were a native android app, I wouldn't have to embed a client secret (instead it uses a SHA-1 hash of your signing cert.  This seems better because Google can verify that it was me that made the request without ever embedding a secret).  Since this is possible in native Android, I was hoping it would also be possible with Xamarin.

**Comment by MirzaSikander** [comment]
According to Googles own [article,](https://developer.android.com/training/id-auth/authenticate.html) "A client id and **client secret**, which are strings that **identify** your app to the service" 

Even if you are able to achieve what you mentioned, in the future if you need to support OAuth platforms apart from Google, you would have to implement the same functionality again.

**Comment by moljac** [comment]
When app (credentials) is created in google developers console there are several options (Web app, Native Android, Native iOS, etc)... Web app was trick workaround to use Xamarin.Auth, but web apps use Authorisation Code Grant flow where in 2nd step request contains client_secret. Web apps are considered secure (more secure than mobile/installed apps).

In this case ctor was created for Implicit grant (with response_type=token) and google needed response_type=code. Thus the error.

New Native UI OAuth by google does not require client_secret (this should not be saved/located on insecure client - mobile app)

**Comment by moljac** [comment]
closing
