### ISSUE TITLE
ArgumentNullException When Loading Accounts

### ISSUE THREAD

**Issue by adamhewitt627** [xamarin/Xamarin.Auth#118]
Fair warning - I have no experience with the Keychain API, beyond looking at this to understand my crashes. 

In version 1.3.0, I get `System.ArgumentNullException Value cannot be null. Parameter name: collection` when I load accounts. Suggested explanation (links are to current source, not 1.3, but the code is largely the same)
1. Occurs here: https://github.com/xamarin/Xamarin.Auth/blob/portable-bait-and-switch/source/Xamarin.Auth.XamarinIOS/PlatformSpecific/KeyChainAccountStore.Aync.cs#L147
2. For `accounts_fixed` to be null, either `.Count()`, `.LongCount()` or `GetAccountFromRecord` has to throw an exception. (And then be swallowed by the `catch` block)
3. Building from source, we find another `ArgumentNullException` here: https://github.com/xamarin/Xamarin.Auth/blob/portable-bait-and-switch/source/Xamarin.Auth.XamarinIOS/PlatformSpecific/KeyChainAccountStore.Aync.cs#L160
4. If I undefined `TEST_MARK_T` and load the `SecRecord.Generic` my app works.

As noted earlier, I don't understand the API, but it appears to me that these load from different parts of the keychain. Thus, if an earlier version of the library used `.Generic` then this update breaks loading those keychains. Decompiling 1.2.2 shows this to be the case: `return Account.Deserialize((string) NSString.FromData(r.Generic, NSStringEncoding.UTF8));`.

**Comment by moljac** [comment]
Can you try 1.3.2-alpha-01 nuget please and let me know if the fix in there solves this issue.

**Comment by newky2k** [comment]
no response since aug 2016
