### ISSUE TITLE
Xamarin.Auth 1.3.1-alpha-01 nuget package is not installing.

### ISSUE THREAD

**Issue by nhinze** [xamarin/Xamarin.Auth#120]
I'm getting the following error trying to install the Xamarin.Auth package in Xamarin Studio on iOS for my PCL project.

How the files look in my packages folder of my project.

![xamarin_auth](https://cloud.githubusercontent.com/assets/1156143/17458993/832fed44-5bf5-11e6-95f1-c826f27350db.jpg)

The error:

Adding Xamarin.Auth...
Installing 'Xamarin.Auth 1.3.1-alpha-01'.
Added file 'lib\portable-net45+wp8+wpa81+win8+MonoAndroid10+MonoTouch10+XamarinIOS10\Xamarin.Auth.dll' to folder 'Xamarin.Auth.1.3.1-alpha-01'.
Added file 'lib\MonoAndroid10\Xamarin.Auth.dll' to folder 'Xamarin.Auth.1.3.1-alpha-01'.
Added file 'lib\Xamarin.iOS10\Xamarin.Auth.dll' to folder 'Xamarin.Auth.1.3.1-alpha-01'.
Added file 'lib\MonoTouch10\Xamarin.Auth.dll' to folder 'Xamarin.Auth.1.3.1-alpha-01'.
Added file 'lib\wp8\Xamarin.Auth.dll' to folder 'Xamarin.Auth.1.3.1-alpha-01'.
Added file 'lib\wpa81\Xamarin.Auth.dll' to folder 'Xamarin.Auth.1.3.1-alpha-01'.
Added file 'lib\win81\Xamarin.Auth.dll' to folder 'Xamarin.Auth.1.3.1-alpha-01'.
Added file 'Xamarin.Auth.1.3.1-alpha-01.nupkg' to folder 'Xamarin.Auth.1.3.1-alpha-01'.
Successfully installed 'Xamarin.Auth 1.3.1-alpha-01'.
Adding 'Xamarin.Auth 1.3.1-alpha-01' to EventingVolunteers.
Could not install package 'Xamarin.Auth 1.3.1-alpha-01'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarintvos10+xamarinwatchos10+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by moljac** [comment]
Investigating.

Seems that nuget packaging on CI bot which is Mac has issues with '\' and '/'. Thanks for the screenshot that helped us to track the '\' issue. I will change nuspec ASAP and publish 1.3.1-alpha-02 and will ask you kindly to report if that fixes the issue.

**Comment by moljac** [comment]
1.3.1-alpha-02 pushed/published few secs ago

**Comment by nhinze** [comment]
Thank you. It works now.

**Comment by nhinze** [comment]
Actually, it appears that there is still a problem with the nuget package. The portable package has the wrong slash issue still:

![image](https://cloud.githubusercontent.com/assets/1156143/17649928/169ded7e-620e-11e6-8111-a33b4bee51ec.png)

**Comment by moljac** [comment]
From previous comment I cannot deduce if the nuget is working or not? Can it be loaded?

**Comment by moljac** [comment]
From issue #122 seems like nuget is loaded:

https://github.com/xamarin/Xamarin.Auth/issues/122

**Comment by nhinze** [comment]
I looked at the commit. You forgot to change one of the two slashes for the portable dll.

**Comment by moljac** [comment]
alpha-03 published 
Please try it out and see if this version fixes the issue.

**Comment by nhinze** [comment]
Thanks. Fixed.
