### ISSUE TITLE
Cannot display login page for Microsoft Live Connect

### ISSUE THREAD

**Issue by kazo0** [xamarin/Xamarin.Auth#121]
MS recently changed their app registration (https://apps.dev.microsoft.com/) and now whenever I try to display the login UI through the `OAuth2Authenticator` I get an error message on Android and iOS telling me: 

> The provided value for the input parameter 'response_type' is not allowed for this client. Expected value is 'code'.

I am providing  `OAuth2Authenticator` with my ClientId from the Microsoft Application Registration Portal, which is now in the form of a GUID. Along with the authorizeUrl of `https://login.live.com/oauth20_authorize.srf` and redirectUrl of `https://login.live.com/oauth20_desktop.srf`

**Comment by sushihangover** [comment]
@kazo0 Every find a workaround for this issue?

**Comment by kazo0** [comment]
@sushihangover the issue is that we no longer need to send the `client_secret` when requesting the `access_token`.

In my case specifically I just extended the `OAuth2Authenticator` and overrode `OnRedirectPageLoaded`

**Comment by sushihangover** [comment]
@kazo0 Thanks, I did the same thing. The fact that the current code does not support explicit  `code`-based auth flow is strange.

**Comment by newky2k** [comment]
work arounds have been used
