### ISSUE TITLE
The type or namespace name 'Auth' does not exist in the namespace 'Xamarin' when building iOS Release

### ISSUE THREAD

**Issue by nhinze** [xamarin/Xamarin.Auth#122]
Xamarin.Auth 1.3.1-alpha-2 works nicely in Xamarin Studio for Mac with an iOS Debug config. However, when using a Release config, I get the error below:

![xam_auth_131a2_error](https://cloud.githubusercontent.com/assets/1156143/17649194/4950e436-61fc-11e6-85b7-0472f37b851d.jpg)

With Xamarin 1.3.0 everything works fine.

**Comment by nhinze** [comment]
Same happens when trying to build an Android Release actually. Debug config is fine.

**Comment by nhinze** [comment]
This is also happening for Debug after I do a "Clean All". Only way to remedy it is to remove 1.3.1, install Xamarin.Auth 1.3.0, build, and update to 1.3.1 again.

**Comment by moljac** [comment]
Can you test if 1.3.1-alpha-03 fixes this problem. 

Maybe XS caches the dll somewhere. We are investigating this one.

**Comment by nhinze** [comment]
Thanks. Fixed after cleaning and rebuilding.
