### ISSUE TITLE
how to use Xamarin.Auth to get refresh token?

### ISSUE THREAD

**Issue by BleyChen** [xamarin/Xamarin.Auth#125]
```
My app use windows live id to login ,so i want to use Xamarin.Auth  ,now it works fine , but now  i want to implement that when user login once ,he didn't login anymore .
```

  In order to implement up scenario, so i want to save token in local ,but token will expired , anyone know how to use Xamarin.Auth to get refresh token which can be used to get latest token ? thanks

**Comment by poohzrn** [comment]
See https://github.com/xamarin/Xamarin.Auth/pull/79

**Comment by newky2k** [comment]
this has now been implented as extensions -> https://github.com/xamarin/Xamarin.Auth/tree/portable-bait-and-switch/source/Extensions

**Comment by lewixlabs** [comment]
Maybe my [gist](https://gist.github.com/lewixlabs/6addc59de22318400a3a9691078ecb33) can be usefull to somebody:

- no other OAuth2 extenensions used
- one derived class only

Hi,
Lewix
