### ISSUE TITLE
Why custom renderers are not part of the lib?

### ISSUE THREAD

**Issue by JeanCollas** [xamarin/Xamarin.Auth#126]
It would be so much simpler not having to have additional custom renderers in the code. Why is it not integrated in the nugget package?

**Comment by moljac** [comment]
The only reason is that I'm the only one maintainer and this part was not thoroughly tested, but I'm working on this. Just to sort out some critical issues...

**Comment by moljac** [comment]
1.5.0 is released with Native UI support and Xamarin.Forms (Presenters and Custom Renderers)
Closing
