### ISSUE TITLE
java.io.EOFException - Invalid Xamarin.Social.Accounts file

### ISSUE THREAD

**Issue by thomasvdb** [xamarin/Xamarin.Auth#130]
We're seeing some crash reports in Xamarin Insights with the following details.

```
Java.IO.IOExceptionException of type 'Java.IO.IOException' was thrown.
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args)
Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualVoidMethod(string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)
Java.Security.KeyStore.Load(Stream stream, char[] password)
Xamarin.Auth.AndroidAccountStore.AndroidAccountStore(Context context)
Xamarin.Auth.AccountStore.Create(Context context)
...
java.io.EOFException
at libcore.io.Streams.readFully(Streams.java:83)
at java.io.DataInputStream.readInt(DataInputStream.java:103)
at com.android.org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineLoad(BcKeyStoreSpi.java:805)
at java.security.KeyStore.load(KeyStore.java:590)
```

I can reproduce this EOFException by manually clearing the contents of the Xamarin.Social.Accounts file so I assume that at some point empty data is written in the Save method in the AndroidAccountStore class.

Unfortunately I could not reproduce this yet in the app itself.
Any ideas what could cause this issue/empty file/corrupt file?

**Comment by fschwiet** [comment]
I got into this situation while instrumentation my code to hit some stress scenarios.  This seems pretty nasty though since users need to clear application data to get past it.  We could probably write code to detect this then delete the platform-specific file that would have been corrupted (forcing the user to login in again).  This hasn't shown up in our customer logs though to justify putting in such code.  Ideally though Xamarin should have code to detect when the account store is corrupted and remove the corrupted file, rather than crash the application.

**Comment by thomasvdb** [comment]
We've added this logic inside our own app.

I can create a PR but was wondering if it's still necessary because of the complete rework which is happening?

**Comment by fschwiet** [comment]
@thomasvdb Personally I could use a copy of the code if you could share a snippet.  I haven't looked into how to locate the file, it would save me some time.

**Comment by thomasvdb** [comment]
```
public UserAccount GetUserAccount()
{
    try
    {
        var storeAccount = Store.FindAccountsForService(ServiceId).FirstOrDefault();
        if (storeAccount == null)
        {
            return null;
        }

        return new UserAccount(storeAccount.Username, storeAccount.Cookies, storeAccount.Properties);
    }
    catch (EOFException endOfFileException)
    {
        // https://github.com/xamarin/Xamarin.Auth/issues/130
        Logger.Warning(endOfFileException, "Could not read StoreAccount due to corrupt or empty file.");

        try
        {
            DeleteKeystoreFile();
        }
        catch (Exception exp)
        {
            Logger.Warning(exp, "Could not delete Xamarin.Social.Accounts (Delete was requested because of corrupted StoreAccount).");
        }
    }

    return null;
}

private void DeleteKeystoreFile()
{
    // As there is no way to clear the keystore without running into the same EOFException, we remove the file ourselves.
    // https://github.com/xamarin/Xamarin.Auth/blob/9c19d90e52994188def9e12e0bbc981a3943a752/src/Xamarin.Auth.Android/AndroidAccountStore.cs
    //
    // If we update this library, we need to verify if this workaround is still needed.
    var fileDeleted = Application.Context.DeleteFile("Xamarin.Social.Accounts");
    if (fileDeleted)
    {
        Logger.Trace("Xamarin.Social.Accounts file is deleted.");
    }
}
```

**Comment by newky2k** [comment]
User added a workaround to their own app

**Comment by fschwiet** [comment]
Well FWIW I haven't seen this affect other users since originally posting in the issue.  So maybe whatever was corrupting the file was fixed.
