### ISSUE TITLE
AuthException in RequestAccessTokenAsync

### ISSUE THREAD

**Issue by SirLanceLang** [xamarin/Xamarin.Auth#131]
After getting access token successfully, this method is called again, and throws an AuthException with error message "Invalid_grant".
Has anyone got a clue?

![image](https://cloud.githubusercontent.com/assets/7024928/19215792/12f82266-8d7e-11e6-8f70-17a99a5b91c8.png)

**Comment by MathildeRoussel** [comment]
Same here, sorry I can't help but if anyone else got a clue it would be great

**Comment by SirLanceLang** [comment]
Mathilde, if you look in issues, then:
Prevent duplicate handling of redirect page loaded #127

has actually solved the problem (For me at least)
