### ISSUE TITLE
requestParams does nothing

### ISSUE THREAD

**Issue by aandino-dev** [xamarin/Xamarin.Auth#132]
I need to add custom parameters to the querystring

Xamarin.Auth -Version 1.3.1.1

**Comment by np20891** [comment]
i am also stuck with the same issue, if you have found the solution please share

**Comment by newky2k** [comment]
@aandino-dev  do you have an example of how you liked to pass these parameters, compared to how you are using it with out?

**Comment by newky2k** [comment]
this appears to implemented now.  you just need to override OnCreateInitialRequest as detailed here -> https://github.com/xamarin/Xamarin.Auth/issues/134 and here ->
https://github.com/xamarin/Xamarin.Auth/blob/ad7f6d6453506ced0ab3af499a7492f13973e3a3/source/Xamarin.Auth.LinkSource/OAuth2Authenticator.cs#L322
