### ISSUE TITLE
add nonce to request

### ISSUE THREAD

**Issue by adussarpsbcg** [xamarin/Xamarin.Auth#134]
Hi, I don't find a way to add a nonce to my request. I'm kind of new to xamarin and nugets package, so if you can send me to the implementation of OAuth2Authenticator of the version 1.3.0 it would be nice.

I'm trying to use request parameter as : 
'auth.RequestParameters.Add("nonce", Guid.NewGuid().ToString("N"));'
 but i keep running in the nonce invalid error from okta.

 If any of you has an idea how to fix it.
I'm new to xamarin and i would be happy to contribute too!

**Comment by yngndrw-sage** [comment]
This should be the version of ```OAuth2Authenticator``` as of the v1.3.0 NuGet release:
https://github.com/xamarin/Xamarin.Auth/blob/ad7f6d6453506ced0ab3af499a7492f13973e3a3/source/Xamarin.Auth.LinkSource/OAuth2Authenticator.cs

You could probably override ```OnCreatingInitialUrl```:
https://github.com/xamarin/Xamarin.Auth/blob/ad7f6d6453506ced0ab3af499a7492f13973e3a3/source/Xamarin.Auth.LinkSource/OAuth2Authenticator.cs#L322

The ```RequestParameters``` property doesn't look to be used from what I can see, or at least not in that version.

**Comment by newky2k** [comment]
this is implemented now
