### ISSUE TITLE
Google Auth Error:disallowed_useragent

### ISSUE THREAD

**Issue by jeremy-alley** [xamarin/Xamarin.Auth#137]
Are there plans to support google's new OAuth requirements?

https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

**Comment by moljac** [comment]
Hi

Both

- Android Chrome [Custom] Tabs and
- iOS SFSafariViewController

**Comment by jeremy-alley** [comment]
awesome, thanks!

**Comment by cjam** [comment]
any idea when this might be released?

**Comment by moljac** [comment]
@cjam Sorry, but no (no idea). I work on that[those] feature[s], fixing quite new Windows UWP, WinRT support and now people would like to see easier Xamarin.Forms support...

This one is for sure highest priority, but if some bugs are blocking people I fix those first.

I have small private samples with CustomTabs and SFSafariViewController, but there are still some issues I'd like to desing/implement before releasing (navigation for CustomTabs is painfull and extracting info is not that easy, i.e. redirect_urls)

**Comment by moljac** [comment]
@cjam @jeremy-alley 

Native UI support preview was published in 1.4.0 nuget

https://www.nuget.org/packages/Xamarin.Auth/1.4.0

Getting Started:

https://github.com/xamarin/Xamarin.Auth/blob/portable-bait-and-switch/component/GettingStarted.md

Details:

https://github.com/xamarin/Xamarin.Auth/blob/portable-bait-and-switch/component/Details.md

Please provide some feedback.

Next steps:

1.  testing
2.  merge to master
3.  most likely v.2.0 with Native UI by default (based on decision)

Thanks

**Comment by jr305** [comment]
Hey @moljac I was actually looking for this functionally yesterday so great timing.
Since this release is brand new I'm guessing the documentation will be updated.

Following the docs I'm stuck where is says to switch 
`StartActivity (auth.GetUI (this));`
to 
`StartActivity (((CustomTabsIntent.Builder)auth.GetUI).Build() (this));`

I'm getting cannot convert type 'method' to CustomTabsIntent.Builder.

**Comment by moljac** [comment]
@jr 
My bad. Too much to do!
GetUI is a parameterless method, so GetUI().

Sorry!Sincere apologises.

**Comment by jr305** [comment]
Hey @moljac,
No worries, thanks for the response. 

I went to the definition of Xamarin.Auth.Authenticator.GetUI() and dont see an overload with no paramaters. The version I see is expecting Android.Content.Context type paramater.

I think I'm missing something. When I download the new version of Xamarin.Auth from NuGet the dlls have a version number of 1.3 instead of the 1.4.0.1 I was expecting because the thats the NuGet packages version #. 

Also where is " this.Finish();" defined?
`auth.Completed += (sender, eventArgs) => 
{
    // UI presented, so it's up to us to dimiss it on Android
    // dismiss Activity with WebView or CustomTabs
    this.Finish();
};`

**Comment by moljac** [comment]
@jr305 

This is copy/paste from our internal slack xamarin-auth-social room! I'm being pounded with questions:

Custom Tabs need:
1. custom schema for redirect url (NOGO - http[s] IOS for sure, Android most likely)
2. Activity with IntentFilter with schema[s], host[s]

My sample[s] (wait few hrs, so I can update it):
https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences

Android Setup:
https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences/blob/master/Providers/Xamarin.Auth.Sample.XamarinAndroid/MainActivity.cs#L109-L182

https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences/blob/master/Providers/Xamarin.Auth.Sample.XamarinAndroid/MainActivity.cs#L109-L182

Activity w IntentFilter:
https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences/blob/master/Providers/Xamarin.Auth.Sample.XamarinAndroid/ActivityCustomUrlSchemeInterceptor.cs

https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences/blob/master/Providers/Xamarin.Auth.Sample.XamarinAndroid/ActivityCustomUrlSchemeInterceptor.cs#L17-L35

**Comment by moljac** [comment]
@jr305 
1.4.1 is coming out in few hrs. 

I added 

*   Warnings to NativeUI if used with http[s] schemes    
     (cannot be intercepted on IOS and I tried hard on Android, but no success)
     and   
*   iOS has option to use WKWebView instead of UIWebView (performance etc)

**Comment by Mahdad-Baghani** [comment]
Hi @moljac,
I'm using 1.4.0.1 and I still have issues:
in my android project, I have a presenter which I register to the xamarin.auth in  MainActivity.
`
void Login(Authenticator auth)
{
   Xamarin.Forms.Forms.Context.StartActivity (auth.GetUI (Xamarin.Forms.Forms.Context) as Intent);
}
` which results is "Google Auth Error:disallowed_useragent" error
and I get compile errors using this :
`
StartActivity (((CustomTabsIntent.Builder)auth.GetUI).Build() (this));
`
I tried :
`
    var authActivity = new CustomTabsIntent.Builder().Build();
     authActivity.Intent = auth.GetUI(Xamarin.Forms.Forms.Context) as Intent;
     Xamarin.Forms.Forms.Context.StartActivity(authActivity.Intent);
` with no luck.

**Comment by moljac** [comment]
Morn

So this is the code (not pushed latest version) for Android sample:

Note I use FCC (fully qualified classes - w/o usings) so copy/paste should work.

https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences/blob/master/Providers/Xamarin.Auth.Sample.XamarinAndroid/MainActivity.cs#L109-L165

Grab the UI object with GetUI(this) (this is activiy):

            //####################################################
            // Xamarin.Auth API - Breaking Change
            //      old API returned global::Android.Content.Intent
            //Intent ui_intent_as_object = auth.GetUI ();
            //      new API returns System.Object
            System.Object ui_object = Auth1.GetUI(this);
 
You'll need CustomTabsIntent.Builder. Initially the API did work with CustomTabsIntent, but UI customisation, warmup and preloading need Builder and not Intent. 
Cast object obtained from GetUI to CustomTabs.Builder:
 
    global::Android.Support.CustomTabs.CustomTabsIntent.Builder ctib;
    ctib = (global::Android.Support.CustomTabs.CustomTabsIntent.Builder)ui_object;
 
Now with Builder customise CustomTabs (note few more customisations not here yet):

    ctib
        .SetToolbarColor(color_xamarin_blue)
        .SetShowTitle(true)
        .EnableUrlBarHiding()
        ;

Build Intent with Builder object:

    // [REQUIRED] launching Custom Tabs
    global::Android.Support.CustomTabs.CustomTabsIntent ct_intent = ctib.Build();
    // launch CustomTabs
    ct_intent.LaunchUrl(this, uri_android);

Just tested 1.4.1 and 1.4.0.1 and works. This code is a week old.

cheers.

Ping me if you need more info.

**Comment by moljac** [comment]
@jr305 @Mahdad-Baghani 
Guys can I see your Authenticator ctor, please?

**Comment by Jake-Barrow** [comment]
@moljac 
I've now got it to authenticate the user in Custom Tabs. However the completed event is never triggered, you mention above about needing to use Custom Schemas? But Google doesn't allow Custom Schemas with Web Application Credentials. So how exactly do we go about doing this?

**Comment by jr305** [comment]
@moljac 
```
new OAuth2Authenticator(
                    clientId,
                    clientSecret,
                    "https://www.googleapis.com/auth/userinfo.email",
                    new Uri("https://accounts.google.com/o/oauth2/auth"),
                    RedirectURI,//same uri defined in https://console.developers.google.com/
                    new Uri("https://accounts.google.com/o/oauth2/token"),
                    null,
                    true
               );
```

**Comment by jr305** [comment]
@moljac I cant really follow the sample. 
I'm working with Xamarin forms. 

```
public async Task GetTokenFromOAuth()
{
                var presenter = new Xamarin.Auth.Presenters.OAuthLoginPresenter();
                presenter.Completed += OnAuthCompleted;
                var authenticator = new OAuth2Authenticator(
                    clientId,
                    clientSecret,
                    "https://www.googleapis.com/auth/userinfo.email",
                    new Uri("https://accounts.google.com/o/oauth2/auth"),
                    RedirectURI,//same uri defined in https://console.developers.google.com/
                    new Uri("https://accounts.google.com/o/oauth2/token"),
                    null,
                    true
               );

                presenter.Login(authenticator);
}
```
Then in my Droid project I have OAuthLoginPresenter

```
namespace Brenock.IdeaPipeLine.App.Droid
{
    public class OAuthLoginPresenter
    {
        public void Login(Xamarin.Auth.Authenticator auth)
        {
            
        }
    }
}
```

Dont really know how to set this up

**Comment by Mahdad-Baghani** [comment]
Hi again, @moljac .
I followed the docs for the xamarin.auth, so I created a Presenter for each specific platform; also, I have a AuthenticationService code in my app.
the code starts with each platform registering its presenter with xamarin auth, so this is my main activity and its OnCreate method:
`
            Xamarin.Auth.Presenters.OAuthLoginPresenter.PlatformLogin = (auth) =>
            {
                var oAuthLogin = new OAuthLoginPresenter();
                oAuthLogin.Login(auth);
            };
`
My viewModel calls into AuthenticationService, which Passes the Authenticator to the Presenter:
`
 if (googleAuthenticator == null)
            {
                googleAuthenticator = new OAuth2Authenticator(
                    clientId: "28120777995-pqkmcgk2phdl318pmt390nif37l0klm2.apps.googleusercontent.com",
                    clientSecret: " ",
                    scope: "profile",
                    authorizeUrl: new Uri( "https://accounts.google.com/o/oauth2/auth"),
                    redirectUrl: new Uri("urn:ietf:wg:oauth:2.0:oob"),
                    accessTokenUrl: new Uri ("https://accounts.google.com/o/oauth2/token"),
                    isUsingNativeUI: true);
                googleAuthenticator.AllowCancel = true;
                googleAuthenticator.Completed += GoogleAuthenticator_Completed;
                googleAuthenticator.Error += GoogleAuthenticator_Error;
                googleAuthenticator.BrowsingCompleted += GoogleAuthenticator_BrowsingCompleted;
            }
            new Xamarin.Auth.Presenters.OAuthLoginPresenter().Login(googleAuthenticator);
`
and this is the android presenter (I had to change your code a little bit, since it left me with a null reference at runtime when I tried to cast 'ui_object' to 'ctib'):
`
public void Login(Authenticator auth)
        {
            System.Object ui_object = auth.GetUI(CrossCurrentActivity.Current.Activity);
            if ((auth as OAuth2Authenticator).IsUsingNativeUI == true)
            {
                //=================================================================
                // Xamarin.Auth API - Native UI support 
                //      *   Android - [Chrome] Custom Tabs on Android       
                //          Android.Support.CustomTabs      
                //          and 
                //      *   iOS -  SFSafariViewController     
                //          SafariServices.SFSafariViewController
                // on 2014-04-20 google (and some other providers) will work only with this API
                //  
                //
                //  2017-03-25
                //      NEW UPCOMMING API undocumented work in progress
                //      soon to be default
                //      optional API in the future (for backward compatibility)
                //
                //  required part
                //  add 
                //     following code:
                System.Uri uri_netfx = (auth as OAuth2Authenticator).GetInitialUrlAsync().Result;
                global::Android.Net.Uri uri_android = global::Android.Net.Uri.Parse(uri_netfx.AbsoluteUri);
                global::Android.Support.CustomTabs.CustomTabsIntent.Builder ctib = new CustomTabsIntent.Builder();
                ctib.Build().Intent = ui_object as Intent;
                //  add custom schema (App Linking) handling
                //      1.  add Activity with IntentFilter to the app
                //          1.1. Define sheme[s] and host[s] in the IntentFilter
                //          1.2. in Activity's OnCreate extract URL with custom schema from Intent
                //          1.3. parse OAuth data from URL obtained in 1.2.
                //  NOTE[s]
                //  *   custom scheme support only
                //      xamarinauth://localhost
                //      xamarin-auth://localhost
                //      xamarin.auth://localhost
                //  *   no http[s] scheme support
                //------------------------------------------------------------
                // [OPTIONAL] UI customization
                // CustomTabsIntent.Builder
                ctib
                    .SetToolbarColor((int)ConsoleColor.Black)
                    .SetShowTitle(true)
                    .EnableUrlBarHiding()
                    ;
                // TODO: warmup, prefetching
                // TODO: menu
                // TODO: bottom bar
                //------------------------------------------------------------
                // [REQUIRED] launching Custom Tabs
                global::Android.Support.CustomTabs.CustomTabsIntent ct_intent = ctib.Build();
                ct_intent.LaunchUrl(CrossCurrentActivity.Current.Activity, uri_android);
                //=================================================================
            }
            return;

        }
`
I managed to do the authentication, it loads a chrome instance, I can follow the auth steps, but at the end it asks me to copy a code in my app, which I donno what to with it!!

**Comment by moljac** [comment]
@Mahdad-Baghani 
Hi

NOTE: I'm using my repo with the same samples based on nuget refs from Xamarin.Auth repo!

Few things are bothering me, so in higher priority order 1st:

>  I can follow the auth steps, but at the end it asks me to copy a code in my app, 
> which I donno what to with it!!

1.   who is asking you to copy code in your app? Xamarin.Auth code/comments (me)?   
      Yes, Custom [Chrome] Tabs need AppLinks (usually implemented via custom URL schemes)  
      So, add Activity with IntentFilter to intercept opening URL.
2.  In that Activity add code to Parse Oauth Fragment in OnCreate   
     NOTE: I tried to implement http[s], but did not manage. There are samples for Android   
     IntentFilters with http[s] scheme, but did not have time to debug why this does not work.

File:
    https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences/blob/master/Providers/Xamarin.Auth.Sample.XamarinAndroid/ActivityCustomUrlSchemeInterceptor.cs

IntentFilter:

https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences/blob/master/Providers/Xamarin.Auth.Sample.XamarinAndroid/ActivityCustomUrlSchemeInterceptor.cs#L17-L35

Parsing OAuth Data from redirect_url Fragment:

https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences/blob/master/Providers/Xamarin.Auth.Sample.XamarinAndroid/ActivityCustomUrlSchemeInterceptor.cs#L44-L71

Ping me here again if you need more info

**Comment by Mahdad-Baghani** [comment]
@moljac 
Hi again.
I added the IntentFilter according to your example. I am using a xamarin.forms PCL project and I wanted to seperate the MainActivity and AndroidAuthPresenter, but that seem impossible since I'm getting all kinds of compile errors when I added your recent changes to your sample MainActivity (when Ii looked at your code for MainActivity, I noticed that you've completed some of the TODOs, and I added those too).

**Comment by jr305** [comment]
any tips @moljac ?

**Comment by moljac** [comment]
@Mahdad-Baghani @jr305
Guys can you try this repo?

https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences

This is the same solution with nuget references like the one in Xamarin.Auth repo in samples/** folder. First try Traditional/Standard approach (no Xamarin.Forms) this will give you feeling how to implement Renderers/Presenters for Xamarin.Forms.

And go to Xamarin community slack xamarin-auth-social room. There are few guys that made progress. Now they are trying to move on google Console from Web App to Installed App which are intended for mobile.

invitation link fo slack:

https://xamarinchat.herokuapp.com/

**Comment by biapar** [comment]
News?

**Comment by JeffDalby** [comment]
@moljac I'm also trying to get this to work with Xamarin Forms, because like many here I'm working on borrowed time.  The deadline has passed for Google to cut off embedded login pages, luckily our app hasn't been cutoff yet, but I'm guessing that could happen any day now.  It seems there's still a lot of confusion on how to make this new stuff work with forms, and not clear documentation yet (which is completely understandable)

I'm looking at the example in the repo you linked to and in the Forms nativeUI example it's creating a Xamarin.Auth.XamarinForms.AuthenticatorPage.  Can't find any documentation on it, looks like it may be a feature coming out in 1.5?  Is the general idea going to be for forms we just navigate to a page based on that and have the Authenticator in the the constructor?  

I'm trying to figure out the best, and quickest way to move forward, and if that means I'll have to use alpha code I guess that's what needs to be done.  Is there any documentation on this yet that I just haven't been able to find?

**Comment by moljac** [comment]
@JeffDalby 

Xamarin.Auth never supported Xamarin.Forms. I added support for Forms in 2015, but it got stale and it was on portable-bait-and-switch branch. This was my side project and now I'm main maintainer (and developer) of the whole lib, additionaly I'm the only one person on this project. I hope you can understand why there is no docs (yet).

> The deadline has passed for Google to cut off embedded login pages, luckily our app hasn't been 
> cutoff yet, but I'm guessing that could happen any day now

If you have Credentials setting opened before 2016-10 (2016-08) your app will still work. Google is cutting off NEW apps. I have appid for the app (WebApp) created in 2015 (it is in the samples) and it is working still.

> I'm looking at the example in the repo you linked to and in the Forms nativeUI example it's creating 
> a Xamarin.Auth.XamarinForms.AuthenticatorPage. Can't find any documentation on it, looks like it 
> may be a feature coming out in 1.5?

yes. This is in 1.5.0-alpha

>  Is the general idea going to be for forms we just navigate to a page based on that and have 
> the Authenticator in the the constructor?

Yes. Do you have better suggestion. I resurrected old Xamarin.Forms code and really fast added Forms support. It looks good to me, but if you have better suggestion I'm all ears.

> I'm trying to figure out the best, and quickest way to move forward, and if that means I'll have to 
> use alpha code I guess that's what needs to be done

I would suggest you to use 1.5.0-alpha. There are (IMO) issues - like closing CustomTabs automatically, Twitter issues etc. It is very close to be published. I just need more info/feedback (you can provide it too)

>  Is there any documentation on this yet that I just haven't been able to find?

No. I'm working on it. The docs I wrote month ago was for 1.4.1 when API changed. The I was under so big pressure with "how to do it in forms", so I added forms support and never had time to go back and rewrite docs.
Follow the samples. That is the reason I put them there.

**Comment by JeffDalby** [comment]
@moljac Thanks for the answer.  If we can get this new forms way working, I'll figure out how to make some time to help you document it.  Right now I'm stuck on an issue where my app crashes on launch in external code after adding the new xamarin auth and xamarin auth.forms packages.  In the process of reverting everything until it will launch again to isolate the issue.

**Comment by moljac** [comment]
@JeffDalby 

Please, can you try this sample 1st? 

https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences

Xamarin.Forms sample ComicBook

https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences/tree/master/Xamarin.Forms/Evolve16Labs

Let's leave other samples out of the discussion for now. Try ComicBook to see if you have crashes.

Ping me here for realtime help. 

https://xamarinchat.slack.com/messages/C4TD1NHPT

I was not able to setup gitter channel for the repo.

**Comment by moljac** [comment]
@JeffDalby And yes. Thanks for offering help with the docs.

**Comment by JeffDalby** [comment]
OK I'm working off that sample now, found my crash (was actually in Xamarin Code injecting the navigation service, which I was doing to push the nav window)  I'll have to do that differently because I'm using PRISM, so it's not really surprising there.

I've also started a document to write down all the steps as I go.  In the end it'll be a tutorial on how to use Xamarin Auth with Forms to authenticated to Google and pass that Authentication to Azure Mobile Apps. I'll try to separate it into two parts in case you only want the Xamarin Auth half here.

To reach you on slack it says I need to request an invitation from the team administrator,  so I guess if that's you can you send an invitation to jeff@wefeel.us?

**Comment by moljac** [comment]
@JeffDalby 
Self invitation
https://xamarinchat.herokuapp.com/

**Comment by JatinKinraAis** [comment]
@Mahdad-Baghani 
@moljac 

I tried above mentioned way of implementing OAuth with custom tabs.
After login, it redirects to redirect-url given in request; and never triggers Auth_Completed().
Can you please help me out here ?

**Comment by moljac** [comment]
@JatinKinraAis 

Seems like you use nuget v.1.4.x. Right?

I'm confused (a lot) by your post, but few mistakes you made:

1. Your ctor does not use isUsingNativeUI, so you should get "disallowed_useragent" yet you say you are being redirected. Seems like you fooled google.

2. for events Native UI => implies custom scheme redirect_url, so:
```
    redirectUrl: new Uri("http://localhost:2000/Home/Callback"),
```
Is wrong. http scheme will be handled by the system browser (Native UI) and you will never be able to capture redirected url to parse it.

3. Next google does not specify that in their docs explicitly that client_secret is not required parameter, so send null or "".

OK. You have Android, so check Providers sample from here:

https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences/tree/master/Traditional.Standard/Providers

For Xamarin.Forms sample - ComicBook:

https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences/tree/master/Xamarin.Forms/Evolve16Labs

**Comment by JatinKinraAis** [comment]
@moljac 
Yes, I am using nuget 1.4.1

And, I am sorry if I was not clear.
Actually, I followed the solution provided by Mahdad-Baghani above.
And, my project is Xamarin. Android application, not Xamarin.Forms.

Despite all the mistakes you pointed out, I am being redirected to the url mentioned.
I have provided this specific url just to gather the access_token in Auth_Completed function.

But the code lifecycle never hits the Auth_Completed function.
I went through the links you mentioned but don't know what to do make this work.
Please help me out.

**Comment by JatinKinraAis** [comment]
@moljac 

I tried solving the issues you mentioned.
When I add isUsingNativeUi true in the ctor, I am getting the following exception -

System.TypeLoadException: Could not load type 'Android.Support.CustomTabs.CustomTabsActivityManager' from assembly 'Xamarin.Android.Support.CustomTabs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

**Comment by moljac** [comment]
@JatinKinraAis 

Bump nugets to 25.x.x. And report here if that helped pls.

**Comment by JatinKinraAis** [comment]
@moljac 
Facing issue while updating 
Error:	Could not install package 'Xamarin.Android.Support.CustomTabs 25.3.1'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by moljac** [comment]
@JatinKinraAis 

Bump your TargetFramework for Android in project settings to 7.x. You might need to update Android SDK first.

**Comment by JatinKinraAis** [comment]
@moljac 
Thanks a lot for addressing my concerns continuously.
Above issues are resolved. but now I have another issue - 
 Auth2.GetUI(this) returns an object, but StartActivity() expects an Intent parameter.

ui_object = Auth2.GetUI(this);
Intent uiObj = ui_object as Intent or // Intent uiObj = Intent(ui_object)
StartActivity(uiObj); 

How can we achieve this ?

**Comment by moljac** [comment]
@JatinKinraAis 

> but then it never hit Auth_Completed function after authentication completes.

Your redirect is:

    redirectUrl: new Uri("http://localhost:2000/Home/Callback"),

Yes Native UI will naviate to localhost:2000, but will not be able to load it, because you have no HTTP server on mobile device. Because of http scheme you will stay in system browser and nothing will happen. Go to samples I provided in this thread and try them. Then visit community slack channel and ping us for help.

**Comment by moljac** [comment]
Closing
