### ISSUE TITLE
System.MissingMethodException: Method 'Xamarin.Auth.Authenticator.GetUI' not found.

### ISSUE THREAD

**Issue by BenDevelopment** [xamarin/Xamarin.Auth#138]
When I try to display the OAuth2Authenticator in Android, I got this error message:
`System.MissingMethodException: Method 'Xamarin.Auth.Authenticator.GetUI' not found.`

Here is my code:
```
[assembly: ExportRenderer(typeof(AuthenticationPage), typeof(AuthenticationPageRenderer))]
namespace my_project.Droid
{
    class AuthenticationPageRenderer : PageRenderer
    {
        private bool _isShown;

        protected override void OnElementChanged(ElementChangedEventArgs<Page> e)
        {
            base.OnElementChanged(e);

            if (_isShown) return;
            _isShown = true;

            var auth = new OAuth2Authenticator(
                Constants.OAuthGoogle.ClientId,
                Constants.OAuthGoogle.ClientSecret,
                Constants.OAuthGoogle.Scope,
                new Uri(Constants.OAuthGoogle.AuthorizeUrl),
                new Uri(Constants.OAuthGoogle.CallbackUrl),
                new Uri(Constants.OAuthGoogle.AccessTokenUrl));
            auth.Completed += OnAuthenticationCompleted;

            // Display the UI
            var activity = Context as Activity;
            activity?.StartActivity(auth.GetUI(activity));
        }

        private async void OnAuthenticationCompleted(object sender, AuthenticatorCompletedEventArgs e)
        {
            if (e.IsAuthenticated)
            {
                await AuthenticationHelper.FetchGoogleEmailAndPicture(e.Account);
            }
        }
    }
}
```
I have no compilation errors. Does anybody faces the same problem ?

**Comment by moljac** [comment]
Can you try turning linker off pls?

**Comment by mitchellthomas10** [comment]
I'm seeing this as well. I just checked, and I don't have Linker turned on. However, when I turned linker on for SDK assemblies only, it worked.

**Comment by moljac** [comment]
Yes. linker removed some methods. Xamarin.Auth is not part of SDK.

**Comment by BenDevelopment** [comment]
I'm sorry for not being active on this post but this problem no longer appear on my project and I don't know how. :(

**Comment by moljac** [comment]
@BenDevelopment 

Glad to hear that (you have not problems anymore).

The reason for fix can be multi-fold (update changed something in project file[s], or it was a bug in linker which was fixed in the meantime, build process changed - improved or fixed something).

When you have this error - Disable linking completely. When everything compiles and works and before release you can turn on linking step by step. This will give you insights about linking process.

Can I close this one?

**Comment by BenDevelopment** [comment]
Yes we can close it ! :)

**Comment by biapar** [comment]
I'll try me too. I've the same error.
