### ISSUE TITLE
 Could not save account to KeyChain: -34018

### ISSUE THREAD

**Issue by kyurkchyan** [xamarin/Xamarin.Auth#139]
I'm using Xamarin.Auth 1.3.1.1 in a Xamarin.Forms project. Xamarin.Forms version is 2.3.2.127. I've upgraded Xcode to 8.2.1 and ran the Xamarin.Forms app  in ios 10.2 simulator. After I call `_accountStore.SaveAsync(account, ServiceId);` exception is raised stating ` Could not save account to KeyChain: -34018`.

**Comment by sushihangover** [comment]
@kyurkchyan  http://stackoverflow.com/questions/39492752/xamarin-error-code-34018

**Comment by kyurkchyan** [comment]
@sushihangover Couldn't access the inner link yet. But in the post the issue is about XCode 8.0, does this mean the issue reappeared and I should file another bug report?

**Comment by sushihangover** [comment]
@kyurkchyan The most usual way a `-34018` (a `NSOSStatusErrorDomain` error) surfaces is you have not granted Keychain access to your application. This is a change within the iOS 10.x permissions model and not `Xamarin.Auth`. 

First thing to check is have you granted Keychain sharing in your entitlements.

There are dozens of `-34018` related questions and answers posted on StackOverflow, most dealing with Keychain access, KeyChain sharing, Keychain difference between simulator and physical device etc.... 

Ref: http://stackoverflow.com/search?q=%5Bios%5D+%22-34018%22

**Comment by kyurkchyan** [comment]
Thanks @sandyarmstrong I added the following lines to my `Entitlements.plist` and made sure it is also attached when building for simulator and it worked.
`<dict>
	<key>keychain-access-groups</key>
	<array>
		<string>com.myapp.id</string>
	</array>
</dict>`

**Comment by moljac** [comment]
Closing.

References (duplicates):

*	139 Could not save account to KeyChain: -34018 		
	https://github.com/xamarin/Xamarin.Auth/issues/139
*	133 System.Exception: Could not save account to KeyChain: -34018 			
	on iOS Simulator 7 OS 10.1			
	https://github.com/xamarin/Xamarin.Auth/issues/133
*	128 Error: Could not save account to KeyChain -- iOS 10			
	https://github.com/xamarin/Xamarin.Auth/issues/128

## Analysis

This problem is not Xamarin related: seems like this is bug in iOS 10 simulator and XCode (8.x).
 
https://forums.developer.apple.com/thread/4743?tstart=0
https://forums.developer.apple.com/thread/51071
https://stackoverflow.com/questions/27752444/ios-keychain-writing-value-results-in-error-code-34018
https://stackoverflow.com/questions/22082996/testing-the-keychain-osstatus-error-34018
https://stackoverflow.com/questions/38456471/secitemadd-always-returns-error-34018-in-xcode-8-in-ios-10-simulator
https://stackoverflow.com/questions/29740952/osstatus-error-code-34018


## [Re]Solution / Workaround

If not present create empty Entitlements.plist 

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
</dict>
</plist>
```

Entitlements.plist must be added to iOS Bundle Signing options for the `iPhoneSimulator|Debug` 
platform.

```
iOS App Options/Properties +/ Build / iOS Bundle Signing +/ Custom Entitlements : Entitlements.plist
```

This will result in following code in *.csproj file:

```xml
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|iPhone' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\iPhone\Debug</OutputPath>
    <DefineConstants>DEBUG;ENABLE_TEST_CLOUD;</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <ConsolePause>false</ConsolePause>
    <MtouchArch>ARMv7, ARM64</MtouchArch>
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    <MtouchFloat32>true</MtouchFloat32>
    <CodesignKey>iPhone Developer</CodesignKey>
    <DeviceSpecificBuild>true</DeviceSpecificBuild>
    <MtouchDebug>true</MtouchDebug>
    <MtouchProfiling>true</MtouchProfiling>
    <IpaPackageName>
    </IpaPackageName>
  </PropertyGroup>
```

while default *.csproj file looks like this


```xml
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|iPhoneSimulator' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\iPhoneSimulator\Debug</OutputPath>
    <DefineConstants>DEBUG;ENABLE_TEST_CLOUD;</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <CodesignKey>iPhone Developer</CodesignKey>
    <DeviceSpecificBuild>true</DeviceSpecificBuild>
    <MtouchDebug>true</MtouchDebug>
    <MtouchNoSymbolStrip>true</MtouchNoSymbolStrip>
    <MtouchFastDev>true</MtouchFastDev>
    <IOSDebuggerPort>50317</IOSDebuggerPort>
    <MtouchLink>None</MtouchLink>
    <MtouchArch>i386, x86_64</MtouchArch>
    <MtouchHttpClientHandler>HttpClientHandler</MtouchHttpClientHandler>
  </PropertyGroup>
```

NOTE: difference is in this file:

```xml
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
```

**Comment by vaices** [comment]
Create BlankProperty list file iOS, for example 
DebugProperties.plist

Right click the iOS project in the solution pane and select Unload Project (if VS2017)
Right click the project again and select Edit [ProjectName].csproj
Locate the Debug PropertyGroups, they should start with flags that look like this:
Debug: <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|iPhoneSimulator' ">
Release: <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|iPhoneSimulator' ">
In each of the builds that use the simulator locate and edit following property to: 
<CodesignEntitlements>DebugProperties.plist</CodesignEntitlements>

Reload the project and see you simulator working.
