### ISSUE TITLE
Any plans to implement SFSafariViewController instead of WebView for iOS?

### ISSUE THREAD

**Issue by michaeldimoudis** [xamarin/Xamarin.Auth#140]
Hi, thanks for this library. Just curious if SFSafariViewController instead of WebView support for iOS is on the roadmap?

**Comment by moljac** [comment]
Hi

Both

-  Android Chrome [Custom] Tabs and
-  iOS SFSafariViewController

I'm currently working on this. I had some high priority tasks to finish. Most of them related to Xamarin.Auth and other Components/SDKs. For example extracting Xamarin.Auth code baked in Salesforce SDK.

**Comment by moljac** [comment]
@michaeldimoudis 

Native UI support preview was published in 1.4.0 nuget

https://www.nuget.org/packages/Xamarin.Auth/1.4.0

Getting Started:

https://github.com/xamarin/Xamarin.Auth/blob/portable-bait-and-switch/component/GettingStarted.md

Details:

https://github.com/xamarin/Xamarin.Auth/blob/portable-bait-and-switch/component/Details.md

Please provide some feedback.

Next steps:

1.  testing
2.  merge to master
3.  most likely v.2.0 with Native UI by default (based on decision)

Thanks

**Comment by roopeshnaik** [comment]
@moljac i am getting invalid cast error
System.InvalidCastException: Specified cast is not valid. at
ctib = (global::Android.Support.CustomTabs.CustomTabsIntent.Builder)ui_intent;

**Comment by moljac** [comment]
@roopeshnaik Is it 1.4.0? Try 1.4.0.1 it has few additions/enhancements and few fixes (mostly Android and one bigger in iOS).

**Comment by roopeshnaik** [comment]
@moljac I was trying this code from your sample with 1.4.0.1, but was getting this cast error

**Comment by simonfriesenbichler** [comment]
Hi @moljac, 

we trying to use SFSafariViewController to authenticate with Facebook. But Facebook does not allow to specify urls with custom protocol as redirect urls.  Do we need to use a Webview or are we thinking wrong?

Thank you!

**Comment by moljac** [comment]
@simonfriesenbichler 
No you don't need to use WebView it should work with SFSafariViewContorller, but FB did not prohibit (yet) AFAIK.

Custom scheme for FB is fb<YOURAPPID>.
Go to Xamarin Community slack channel #xamarin-auth-social there is 3-5 people that have implemented everything. OK. most of them google, but you'll get answers there faster.
All cool kids including me are hanging out there.

nuget 1.5.0-alpha-03 with Xamarin.Forms support was published few minutes ago.

**Comment by moljac** [comment]
1.5.0 nuget with Native UI and Xamarin.Forms was published few days ago.
Closing
