### ISSUE TITLE
UWP in 1.3.2 is only compiled in x86

### ISSUE THREAD

**Issue by squinn7** [xamarin/Xamarin.Auth#141]
I noticed that there is new support UWP in the new releases but it seems to be limited only to intel 32 bit which is causing problems in my project. Due to decencies on SQLite my library project is causing conflicts with my application when compiled for a specific architecture, and anyway I won't be able to compile to Windows phone with only a x86 target.

I get this error when compiling on any CPU in my library

There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\...\.nuget\packages\Xamarin.Auth\1.3.2\lib\uap10.0\Xamarin.Auth.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.		

I am wondering why the new UWP update does not compile to MSIL or have all dlls packaged. Otherwise I will have to revert and keep using my own secure store for UWP(which is a pain).

Thanks

**Comment by moljac** [comment]
Let me check it.

This might be my mistake in cake file (it has grown pretty big for all platforms). 

Thanks for reporting

**Comment by moljac** [comment]
Seems like copying output with this pattern ** caused that x86 did overwrite AnyCPU binaries...

New nuget was published few minutes ago!

https://www.nuget.org/packages/Xamarin.Auth/1.3.2.1

Please let me know (here) if this fixes the issue, so we can close it.

Mel

**Comment by squinn7** [comment]
Thanks for the fast response on this! I have updated to the latest nuget and this issue is fixed for UWP.

Thanks

**Comment by moljac** [comment]
closing this one
