### ISSUE TITLE
WinPhone 8.1 has only x86 build

### ISSUE THREAD

**Issue by Shan11812** [xamarin/Xamarin.Auth#142]
I'm trying to build Windows Phone 8.1 (WinRT) with ARM config. Getting the following error.

`There was a mismatch between the processor architecture of the project being built "ARM" and the processor architecture of the reference "Xamarin.Auth, Version=1.3.0.0, Culture=neutral, processorArchitecture=ARM", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.	<project>.WinPhone`

**Comment by moljac** [comment]
Please check 1.3.2.3 and report results here.

NOTE: there are few issues I'm working on. Seems like some events are not firing.

**Comment by Shan11812** [comment]
Yes it is working now, even though the events are not bound to webview's events.

**Comment by moljac** [comment]
@Shan11812 

NativeUI or WebView?
The problem is that I simply have no time to test and fix problems like this one.
