### ISSUE TITLE
Getting InvalidOperationException 

### ISSUE THREAD

**Issue by saryuwahi** [xamarin/Xamarin.Auth#143]
I am getting a System.InvalidOperationException: The current SynchronizationContext may not be used as a TaskScheduler.

**Stacktrace below**:

---> (Inner Exception #0) System.InvalidOperationException: The current SynchronizationContext may not be used as a TaskScheduler.

System.Threading.Tasks.SynchronizationContextTaskScheduler.SynchronizationContextTaskScheduler()<a67c5439364a4a4992cd952d9010b635>:0
System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext()<a67c5439364a4a4992cd952d9010b635>:0
Xamarin.Auth.WebAuthenticatorActivity.BeginLoadingInitialUrl()<fb4933d771d243b68420bc88c470530c>:0
Xamarin.Auth.WebAuthenticatorActivity.<OnCreate>m__1(object s, AuthenticatorErrorEventArgs e)<fb4933d771d243b68420bc88c470530c>:0
Xamarin.Auth.Authenticator.<RaiseErrorEvent>c__AnonStorey1.<>m__0()<fb4933d771d243b68420bc88c470530c>:0
Xamarin.Auth.Authenticator.BeginInvokeOnUIThread(Action action)<fb4933d771d243b68420bc88c470530c>:0
Xamarin.Auth.Authenticator.RaiseErrorEvent(AuthenticatorErrorEventArgs args)<fb4933d771d243b68420bc88c470530c>:0
Xamarin.Auth.Authenticator.OnError(Exception exception)<fb4933d771d243b68420bc88c470530c>:0
Xamarin.Auth.OAuth1Authenticator.<OnPageLoaded>m__1(Task getTokenTask)<fb4933d771d243b68420bc88c470530c>:0
System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()<a67c5439364a4a4992cd952d9010b635>:0
System.Threading.Tasks.Task.Execute()<a67c5439364a4a4992cd952d9010b635>:0

**Comment by moljac** [comment]
Please can you provide minimal sample for testing?

**Comment by newky2k** [comment]
no response for over a year
