### ISSUE TITLE
Create another Icon

### ISSUE THREAD

**Issue by hajuuk** [xamarin/Xamarin.Auth#148]
When I installed Xamarin.Auth from Nuget, it have two icon of the same Application.

One is for MainActivity, another named "Xamarin.Auth.CustomUrlSchemeCallbackActivity" may open CustomUrlSchemeCallbackActivity.

For my application, I only need this library to store token securely, is there have a method to remove this icon?

Thank you.

**Comment by moljac** [comment]
See this please

https://github.com/xamarin/Xamarin.Auth/issues/149

https://github.com/xamarin/Xamarin.Auth/issues/150

**Comment by moljac** [comment]
Nuget v. 1.3.2.4 published few minutes ago. Please test it and report any issues (even better if issues are fixed).
NOTE: new nuget with UWP and WinRT fixes is on the way.

**Comment by moljac** [comment]
Fixed in 1.4.x and 1.5.0
Closing
