### ISSUE TITLE
No resource found that matches the given name (at 'icon' with value '@drawable/icon')

### ISSUE THREAD

**Issue by petermajor** [xamarin/Xamarin.Auth#149]
After updating to 1.3.2.2 I could no longer compile my application.

I get this error in Xamarin Studio for the Android project:

`/Users/petermajor/Source/pelican/Pelican.Mobile/src/Pelican.UI.Droid/obj/Debug/android/manifest/AndroidManifest.xml(0,0): Error APT0000: No resource found that matches the given name (at 'icon' with value '@drawable/icon'). (APT0000) (Pelican.UI.Droid)`

Strange, as we don't use `@drawable/icon`, we use `@mipmap/ic_launcher`

I looked at the AndroidManifest.xml in obj\debug and found this, which the nuget package must be inserting:

```
    <activity android:icon="@drawable/icon" android:label="Xamarin.Auth.CustomUrlSchemeCallbackActivity" android:name="md5a104545e4d19c4ffe9ec3d5074a3b979.CustomUrlSchemeCallbackActivity">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
```

I don't think that's gonna work - we don't have `@drawable/icon` in the project...

**Comment by Jake-Barrow** [comment]
This seems to be a bug in the current version of Xamarin.Auth (1.3.2.2) which adds a new Activity, this activity is created a second application icon on the installed device and as you found, that will be using the @drawable/icon.

The quickest way to temporarily fix this will be to add an icon.png to your drawable folder. But hopefully the package will be fixed soon.

**Comment by moljac** [comment]
Guys my bad. Sorry. I committed few files I'm working on for new features and Windows support.

I will fix this and repackage this in 1.3.2.4 this evening. Please report here results.

Note: this activity will not go away! I forgot to remove icon in ActivityAttribute.

See here why this will not go away:

https://github.com/xamarin/Xamarin.Auth/issues/150

Thanks and sorry for inconvenience.

**Comment by moljac** [comment]
Nuget v. 1.3.2.4 published few minutes ago. Please test it and report any issues (even better if issues are fixed).
NOTE: new nuget with UWP and WinRT fixes is on the way.

**Comment by moljac** [comment]
Closing
