### ISSUE TITLE
Activity unknown? android.support.customtabs.CustomTabsIntent

### ISSUE THREAD

**Issue by abbert** [xamarin/Xamarin.Auth#152]
Android.Content.ActivityNotFoundException: Unable to find explicit activity class {nl.abbert.asdf/android.support.customtabs.CustomTabsIntent}; have you declared this activity in your AndroidManifest.xml?

**Comment by JakubHolovsky** [comment]
@abbert do you have the Xamarin.Android.Support.CustomTabs package installed?

**Comment by NPadrutt** [comment]
Hi 
I guess I have a similar issue. When I upgrade to v1.3.2.6 I get this exception:
```
Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Xamarin.Android.Support.CustomTabs, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Xamarin.Android.Support.CustomTabs.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	
```

When I add Xamarin.Android.Support.CustomTabs I get 6 new exceptions. Any idea how to solve this?

**Comment by thomas-goerlich** [comment]
@NPadrutt are you using Xamarin.Forms? I ran into the same problem with Forms and i can't upgrade the Xamarin.Android nuget packages because then forms does not work anymore.

**Comment by NPadrutt** [comment]
No, I use Xamarin Native with MvvmCross.

**Comment by NPadrutt** [comment]
@thomas-goerlich It seems my issue was fixed after some cycles of clean and rebuild :)

**Comment by sukhai** [comment]
@abbert As mentioned by @JakubHolovsky , you may need to install Xamarin.Android.Support.CustomTabs to get it compiles. I installed that package and now it works.

**Comment by abbert** [comment]
Hi, I use Xamarin.Forms. I installed Xamarin.Android.Support.CustomTabs in the Android folder. Do I need to install it in the main folder too?

**Comment by sukhai** [comment]
@abbert I only installed the CustomTabs in the Android project/folder, not the forms/PCL project. i.e inside MyApp.Droid

**Comment by moljac** [comment]
CustomTabs will be pulled with nuget automatically
Closing
