### ISSUE TITLE
Location of release notes?

### ISSUE THREAD

**Issue by JakubHolovsky** [xamarin/Xamarin.Auth#154]
I can see from Nuget that the Xamarin.Auth is getting stable development however I am not able to see what changed in each version. What is the official location of release notes when this github page is so outdated?

**Comment by moljac** [comment]
Working on docs to, but there are other priorities.

**Comment by moljac** [comment]
Morn

readme.md updated - https://github.com/xamarin/Xamarin.Auth/tree/portable-bait-and-switch

It points to Components docs:

https://github.com/xamarin/Xamarin.Auth/tree/portable-bait-and-switch/component

https://github.com/xamarin/Xamarin.Auth/blob/portable-bait-and-switch/component/GettingStarted.md
https://github.com/xamarin/Xamarin.Auth/blob/portable-bait-and-switch/component/Details.md

I started adding changed bits (Windows support and NativeUI)

**Comment by JakubHolovsky** [comment]
Great, thanks, I am sure this will help a lot of people using the library.

**Comment by moljac** [comment]
@JakubHolovsky 

Native UI support preview was published in 1.4.0 nuget

https://www.nuget.org/packages/Xamarin.Auth/1.4.0

Getting Started:

https://github.com/xamarin/Xamarin.Auth/blob/portable-bait-and-switch/component/GettingStarted.md

Details:

https://github.com/xamarin/Xamarin.Auth/blob/portable-bait-and-switch/component/Details.md

Please provide some feedback.

Next steps:

1.  testing
2.  merge to master
3.  most likely v.2.0 with Native UI by default (based on decision)

Thanks
