### ISSUE TITLE
OAuth 1.0a (One Legge)

### ISSUE THREAD

**Issue by bpBily** [xamarin/Xamarin.Auth#159]
hi,
On OAuth1 i don't have token before beginning registered. And when i used OAuth1.getsignature without token secret the method return me a empty signature.
Can you help me?
thx

**Comment by moljac** [comment]
Hi @bpBily 

Can I get back to you in few days (as soon as NativeUI support is published - SFSafariViewController and Custom Tabs).

**Comment by moljac** [comment]
@bpBily 
Which OAuth service provider?
I need for testing.

**Comment by newky2k** [comment]
No response from over a year
