### ISSUE TITLE
WebView SetAcceptThirdPartyCookies

### ISSUE THREAD

**Issue by bradlol** [xamarin/Xamarin.Auth#160]
Hi,
I'm creating an app for WordPress site, using REST API and WP OAuth Server to auth users. 
Problem is that there's login page also with Facebook login and it works fine on iOS and Android below Lollipop, but in Lollipop and above third party cookies are disallowed by default. That makes impossible to login with Facebook JS API.
So is there anyway of exposing WebView? Or any other way of working around it?

**Comment by moljac** [comment]
Hi @bradlol 

I will check this issue as soon as version with Native UI (SFSafariViewController and CustomTabs).

**Comment by EthanHitGub** [comment]
Any news on this? Exposing WebView could greatly improve flexibility.

**Comment by newky2k** [comment]
@bradlol  @ethanae  can you check this with the latest version please?  

Regards

**Comment by newky2k** [comment]
no response after two weeks, closing
