### ISSUE TITLE
Cannot fire completed event second time

### ISSUE THREAD

**Issue by Kacpur** [xamarin/Xamarin.Auth#161]
I implemented Xamarin.Auth both on Android and iOS. When I hit button and the Authenticator View is presented for the first time there is no problem. I can cancel it or log in and then it disappears. But when I do it second time, I cannot cancel it (back button does nothing) and after successful log in I get an error page and cannot dismiss it. This is how my code looks like on Android Page Renderer (i cannot check it for iOS yet):

```
public class AuthViewRenderer : PageRenderer, IAuthPage
    {
        public void PushLoginPage()
        {
            var auth = App.FBAuth;

            var activity = Context as Activity;
            activity.StartActivity((Intent)auth.GetUI(activity));
        }
    }
```

PushLoginPage is a DependencyService method fired when I hit the login button.

**Comment by moljac** [comment]
Need more details:

*  nuget package
*  Native UI yes/no

thanks

**Comment by Kacpur** [comment]
Nuget is 3.4.4.1321
Xamarin.Auth is 1.3.2.7

I have no native UI.

**Comment by ads90** [comment]
same issue here

**Comment by newky2k** [comment]
no response after two weeks, closing
