### ISSUE TITLE
can't redirect in xamarin ios 

### ISSUE THREAD

**Issue by ads90** [xamarin/Xamarin.Auth#162]
version 1.3.0.0 and above  can't redirect after authenticated from twitter app

**Comment by moljac** [comment]
@ads90 Authenticator ctor?

**Comment by ads90** [comment]
after calling GetUI() and signing in page doesnt back to the app

**Comment by moljac** [comment]
Did you get token?

**Comment by ads90** [comment]
i get the token in older versions when its directly back but the app now stock and doesnt return back

**Comment by moljac** [comment]
https://forums.xamarin.com/discussion/comment/234063/#Comment_234063

**Comment by moljac** [comment]
Closing. User is most likely incorrectly using Native UI with http scheme. 
Lack of info.
