### ISSUE TITLE
get list of users in facebook

### ISSUE THREAD

**Issue by maxdiable** [xamarin/Xamarin.Auth#163]
hi,
how it's possible to get the list of users from facebook ?

br
Max

**Comment by Kacpur** [comment]
Have you tried this: https://developers.facebook.com/docs/graph-api/reference/user/friends ?

**Comment by prashantvc** [comment]
@maxdiable Could you elaborate the your question? Xamarin.Auth is library to authenticate an user, it does not include Facebook APIs.

You may want to take a look at the [Facebook graph API](https://developers.facebook.com/docs/graph-api/)
