### ISSUE TITLE
Error while building Android: Could not load PCLCrypto

### ISSUE THREAD

**Issue by mdekrey** [xamarin/Xamarin.Auth#165]
I recently upgraded my application to Xamarin.Auth 1.4.1, and am getting a new error while building my Android application:

    Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'PCLCrypto, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d4421c8a4786956c'. Perhaps it doesn't exist in the Mono for Android profile?
    File name: 'PCLCrypto.dll'
       at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
       at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
       at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)

I have tried adding PCLCrypto, but it leads to further errors.

I am using Xamarin.Auth with a .netstandard library which is referenced my Android Xamarin project, and the error occurs in the Android project.

What is the correct process for referencing Xamarin.Auth via a cross-platform library reference?

# Update w/ Workaround
While I ran into this again today with `Xamarin.Auth 1.5.0.3` (and finding my own open issue was discouraging), I was able to solve this problem by following [@nolanblew's suggestion](https://github.com/xamarin/Xamarin.Auth/issues/165#issuecomment-330961312) - add an explicit reference to `PCL Crypto 2.0.147` directly to the Android project. This is not an ideal solution, so I hope this is solved in the future... and that the workaround doesn't change in the meantime.

**Comment by moljac** [comment]
Sorry for late response, but /netstandard support was not tested at all (yet).

Xamarin.Auth is PCL bait-n-switch library. You might want to try newer 1.5.0-alpha-* nugets there were several bug fixes and improvements for Xamarin.Forms.

**Comment by nickkimbrough** [comment]
I can confirm upgrading to 1.5.0-alpha-10 and then manually installing PCLCrypto 2.0.147 to the android project fixed the build issues, at least for my project with the same issues.

**Comment by jaricardodev** [comment]
I can confirm the same as @nickkimbrough

**Comment by marktap** [comment]
We might be able to remove the PCL Crypto dependency - I _think_ it is only used in some samples.

**Comment by moljac** [comment]
@marktap 

Removing PCLCrypto after more than a year is not very wise. It was refactored from the Evolve16 labs and added to the Xamarin.Auth.

**Comment by nolanblew** [comment]
Still hitting this same bug after adding `Xamarin.Auth 5.0.3` to an empty Android project. Looks like it doesn't automatically bring in `PCLCrypto` into the project as a dependency, so I had to manually add `PCL Crypto 2.0.147` to successfully get it to work.

**Comment by itlks** [comment]
@nolanblew Yep, that's it. Still with the same bug. Works fine adding manually.

**Comment by newky2k** [comment]
@mdekrey @nickkimbrough @jaricardodev @marktap  @nolanblew @itlks  can you check this with  latest version of Xamarin.Auth, currently at 1.6.0.2, and see if this is still and issue.

Regards

**Comment by newky2k** [comment]
no response after two weeks, closing

**Comment by nishankbhati** [comment]
I had the same issue. The solution is to add PCL crypto manually,
