### ISSUE TITLE
It does not work if used in a dependency service implemenation from PCL?

### ISSUE THREAD

**Issue by jelmarlaunchlabs** [xamarin/Xamarin.Auth#168]
I've tried using this in a dependency service implementation by setting isUsingNativeUI = true and:

var authenticator = new OAuth2Authenticator(/*setting clientId and other parameters here*/, isUsingNativeUI = true);

var context = Forms.Context;
context.StartActivity(authenticator.GetUI(context));

The login or whatever it is doesn't even open, however if isUsingNativeUI = false, it normally opens a WebView which is also NOT ALLOWED if you are using the OAuth2 to login to Google Sign-in.

The point is I am using this for Google Sign-in, and it does not work.

**Comment by moljac** [comment]
Aware of the issue.

**Comment by jelmarlaunchlabs** [comment]
For the latest -alpha-06, there seems to be an error the when I use the code above:

In my application output:

`[Mono] Assembly Ref addref Zeemo.Droid[0xb7c87e80] -> Newtonsoft.Json[0xb7cb4630]: 4
[Mono] Assembly Ref addref Zeemo.Droid[0xb7c87e80] -> Xamarin.Auth[0xb7cd3c90]: 2
[Mono] Assembly Ref addref Zeemo.Droid[0xb7c87e80] -> System[0xb7d9c5a0]: 17
[Mono] Assembly Ref addref Xamarin.Auth[0xb7cd3c90] -> System[0xb7d9c5a0]: 18
[Mono] Assembly Ref addref Xamarin.Auth[0xb7cd3c90] -> Xamarin.Android.Support.CustomTabs[0xb7cd2f60]: 2
[Mono] Assembly Ref addref Xamarin.Auth[0xb7cd3c90] -> System.Core[0xb7f75ca0]: 10
[Mono] Assembly Ref addref Mono.Android[0xb7cf12c8] -> System.Runtime.Serialization[0xb86df0e0]: 4`

**Comment by moljac** [comment]
1.5.0-alpha-* have Xamarin.Forms support and this caused linker issues. Investigating that.

**Comment by moljac** [comment]
@jelmarlaunchlabs 

Please try released 1.5.0 and provide some feedback here.

**Comment by Cariaga** [comment]
Problem still persist
 ` Activity activity = this;
          

            var auth = new OAuth2Authenticator(
                  clientId: "myclientid",
            scope: "",
            authorizeUrl: new Uri("https://m.facebook.com/dialog/oauth/"),
            redirectUrl: new Uri("http://www.facebook.com/connect/login_success.html"));

            auth.Completed += (sender, eventArgs) => {
                if (eventArgs.IsAuthenticated)
                {
                    App.SuccessfulLoginAction.Invoke();
                    // Use eventArgs.Account to do wonderful things
                    Log.Debug("App", eventArgs.Account.Properties["access_token"]);
                    Log.Debug("App", eventArgs.Account.Properties["email"]);
                    Log.Debug("App", eventArgs.Account.Properties["contact"]);
                    App.SaveToken(eventArgs.Account.Properties["access_token"]);
                }
                else
                {
                    // The user cancelled
                    Log.Debug("App", "Cancelled By User");
                }
            };
           var intent = auth.GetUI(activity);


           // StartActivity(intent);
            Forms.Context.StartActivity(intent);`

**Comment by newky2k** [comment]
@jelmarlaunchlabs  @Cariaga Can you please check to see if this is still and issue with the latest version.

**Comment by newky2k** [comment]
no response after 2 weeks, closing
