### ISSUE TITLE
Invalid Cast Excepition on Native UI

### ISSUE THREAD

**Issue by piotrekas1** [xamarin/Xamarin.Auth#169]
Hi, I have problem with Xamarin.Auth.
I'm making a Xamarin.Forms Application and I want to implement Login with Google. I read details from repository and my application end with invalid cast exception. 

`[assembly: ExportRenderer(typeof(ProviderLoginPage), typeof(LoginRenderer))]
namespace MyApp.Droid
{
    public class LoginRenderer : PageRenderer
    {
        bool showLogin = true;
        protected override void OnElementChanged(ElementChangedEventArgs<Page> e)
        {
            base.OnElementChanged(e);
            try
            {
                var loginPage = Element as ProviderLoginPage;
                string providerName = loginPage.ProviderName;
                var activity = Context as Activity;
                if (showLogin)
                {
                    showLogin = false;
                    OAuthProviderSetting oauth = new OAuthProviderSetting();
                    var auth = oauth.LoginWithProvider(providerName);
                    auth.Completed += (sender, eventArgs) =>
                    {
                        if (eventArgs.IsAuthenticated)
                        {

                        }
                    };
                    System.Object uiObject = auth.GetUI(activity);
                    if (auth.IsUsingNativeUI)
                    {
                        System.Uri uriNetfx = auth.GetInitialUrlAsync().Result;
                        Android.Net.Uri uriAndroid = Android.Net.Uri.Parse(uriNetfx.AbsoluteUri);
                        CustomTabsIntent.Builder ctib = (CustomTabsIntent.Builder) uiObject;
                        CustomTabsIntent ctIntent = ctib.Build();
                        ctIntent.LaunchUrl(activity, uriAndroid);
                    }
                    else
                    {
                        Android.Content.Intent i = null;
                        i = (Android.Content.Intent) uiObject;
                        activity.StartActivity(i);
                    }
                }
            }
            catch (System.Exception a)
            {
                System.Console.WriteLine(a);
            }
        }
    }
}`

Problem take place int this line
`CustomTabsIntent.Builder ctib = (CustomTabsIntent.Builder) uiObject;`
I use newest alpha version on Xamarin.Auth
I have installed CustomTabs.
OAuthProviderSetting class implement OAuth2Authentificator and return it to variable.
Can you help me?

**Comment by moljac** [comment]
@piotrekas1 
Yes. We can try to help you, but you need to help us and provide us more details.

Which nuget? Seems like 1.4.1, but this is wild guess.

**Comment by JakubHolovsky** [comment]
@piotrekas1 cast it to "CustomTabsIntent" not to the builder.

**Comment by piotrekas1** [comment]
As i mentioned in my first post i use latest alpha version. To be specific 1.5.0-alpha-04.
@JakubHolovsky I try to change it as you suggested but get the same result.
`CustomTabsIntent ctIntent = (CustomTabsIntent)uiObject;` 
The following line ends with the same error of invalid cast exception.
`System.InvalidCastException: Specified cast is not valid.`

**Comment by JakubHolovsky** [comment]
@piotrekas1 interesting, sure your line read like this: 

`CustomTabsIntent cti = (CustomTabsIntent) uiObject;`

just checking :)

**Comment by JakubHolovsky** [comment]
@piotrekas1 when you put a breakdown on the cast and see what the uiObject is like, what does it say?

**Comment by piotrekas1** [comment]
@JakubHolovsky 
I check and i think i see a problem
[http://imagizer.imageshack.us/a/img922/4971/C17fpJ.png](url)
There you see the variables is not set( i think)
[http://imagizer.imageshack.us/a/img922/6724/KwbFaq.png](url)
There you see changes (close to searched ones)
What do you think is a problem?
Thank you for trying to help me

**Comment by moljac** [comment]
@piotrekas1 @JakubHolovsky 
1.5.0 has Xamarin.Forms implementation (2 of them) 

*    Presenters (Dependency Injection/Service in a sense)   
*    Custom Renderers   

The docs are not updated, but the GetUI() object returns Intent like it used to. I have managed to make API the same as it used to be in old version.

@piotrekas1 
Pasting hundreds lines of code and urls for images (which do not work) does not help a lot. If you want help, please help us out at least with proper info.

In your case important information is only:

*   nuget version - 1.5.0-alpha-04   
*   GetUI() does not return CustomTabsIntent nor CustomTabsIntent.Builder, but Intent

Try pasting text, not images.

If you want even faster help go to XamarinChat on slack (Community slack channel) room #xamarin-auth-social. There are several people that have implemented NativeUI logins in Xamarin Standard/Traditonal (Xamarin.Android and/or Xamarin.iOS).

With Forms there are runtime issues that we are being investigated.

**Comment by piotrekas1** [comment]
@moljac 
I understand your point of view, but i tried this links in many ways and there are working. Only problem is that github don't understand them propertly. I assume you will try to copy paste them with that error. Again sorry about it.
But getting back to point. I've think i get it works (get chrome tabs started) with this code
`System.Object uiObject = auth.GetUI(activity);
                    if (auth.IsUsingNativeUI)
                    {
                        System.Uri uriNetfx = auth.GetInitialUrlAsync().Result;
                        Android.Net.Uri uriAndroid = Android.Net.Uri.Parse(uriNetfx.AbsoluteUri);
                        CustomTabsIntent.Builder builder = new CustomTabsIntent.Builder();
                        CustomTabsIntent ctIntent = builder.Build();
                        ctIntent.LaunchUrl(activity, uriAndroid);
                    }
                    else
                    {
                        Android.Content.Intent i = null;
                        i = (Android.Content.Intent) uiObject;
                        activity.StartActivity(i);
                    }`
Thank you for help. Now i'll need to read about getting data from there.

**Comment by moljac** [comment]
@piotrekas1 
No reason to be (or feel) sorry. I just made my observations. I'm (almost) alone on this project and retyping errors or parts of it from image into IDE is a bit painful. 

>  I've think i get it works (get chrome tabs started) without casting uiObject to Builder. 
> Just by making separate.

This is change (reverted API) in 1.5.0-alpha-*. When I was refactoring to add Xamarin.Forms support (with help and suggestion from other Components Team members and some community) I was able to implement the API, so the cast is not necessary anymore (functionality is pushed deeper into Xamarin.Auth API and hidden from user).

**Comment by piotrekas1** [comment]
@moljac 
And what about collecting data from that?
Is it working like you described in details in portable branch or some changes in newest version?

**Comment by moljac** [comment]
@piotrekas1 
Sure. If you can try new 1.5.0-alphas and collect data. Namely I'm trying to solve linker issues, since I added Xamarin.Forms support

**Comment by Serdfd** [comment]
@piotrekas1  
Can you pls show me how you resolve it?

**Comment by piotrekas1** [comment]
The solution i have won't work. I abandon working of that load. Maybe some day there will be one simply solution (no offence to author, great to even try to make it).

**Comment by Prosenjitsds** [comment]
Hello Moljac, I am facing a similar issue of invalid cast xxcepition in my Xamarin.Andriod app. It was working well with webview but have to update to native view due to new Google policies. Please find my code below:
 void LoginToGoogle(bool allowCancel){
            try {
                var auth = new OAuth2Authenticator (
                    clientId: "2957********-j294559rkrfdeku9p39hhhcs6tjmjvo6.apps.googleusercontent.com",
                    scope: "https://www.googleapis.com/auth/userinfo.email",
                    authorizeUrl: new Uri ("https://accounts.google.com/o/oauth2/auth"),
                    redirectUrl: new Uri ("http://go********.com/"),
                    getUsernameAsync:null,
                    isUsingNativeUI: true
                    );

                auth.AllowCancel = allowCancel;

                // If authorization succeeds or is canceled, .Completed will be fired.
                auth.Completed += LoginGoogleComplete;
                
             

                System.Object ui_intent_as_object = auth.GetUI(this);
                if (auth.IsUsingNativeUI == true)
                {
                    // Add Android.Support.CustomTabs package 
                    global::Android.Support.CustomTabs.CustomTabsIntent cti = null;
                    cti = (global::Android.Support.CustomTabs.CustomTabsIntent)ui_intent_as_object;

                }
                else
                {
                    global::Android.Content.Intent i = null;
                    i = (global::Android.Content.Intent)ui_intent_as_object;
                    StartActivity(i);
                }
            } 
            catch (Exception ex) 
            { 
            }
        }

I am getting an exception  " Specified cast is not valid. at Pr*******.LogInPage.LoginToGoogle (System.Boolean allowCancel) [0x0005d] "
at the line
cti = (global::Android.Support.CustomTabs.CustomTabsIntent)ui_intent_as_object;

I m using auth version 1.5.0.0. Please help me with your suggestions.
Thanks

**Comment by moljac** [comment]
@Prosenjitsds 

At a glance:

*  WRONG redirect_url - Native Ui will not work with http[s] schemes.
*  you're mixing code from 1.4.x in 1.5.x 

In order to deliver native UI I didn't have enough time to refactor (and design API), so 1.4.x exposed CustomTabsIntent and it was released so. in 1.5.0 I added Forms support and was able to design/refactor so the API is like old one (prior to 1.4.0). Just use 

```csharp
global::Android.Content.Intent i = null;
i = (global::Android.Content.Intent)ui_intent_as_object;
StartActivity(i);
```

read the docs in component/ and docs/

you have links for slack channel - se you there

**Comment by Prosenjitsds** [comment]
Hello Moljac, 

I am facing following issue in another project after added Xamarin Auth version 1.5 alpha and PCLCrypto at reference though  Xamarin.Android.Support.CustomTabs installed in my package:

Severity	Code	Description	Project	Project Rank	File	Line	Column	Category	Source	Suppression State
Error Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Xamarin.Android.Support.CustomTabs, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Xamarin.Android.Support.CustomTabs.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute()

Please help me with your suggestions.
Thanks

**Comment by moljac** [comment]
@Prosenjitsds 

Try updating to higher versions (CustomTabs at least)

**Comment by manalikundu** [comment]
Hello Sir,

I have updated  Xamarin Auth version 1.5 alpha and also Xamarin.Android.Support.CustomTabs version 25.Then also I am getting following errors:

Please install GPS Base,
 Please install GPS Basement
Please install GPS GCM
GPS Measurement

though everything is added in my project already.

Please look in to this issue,
Thanks

**Comment by moljac** [comment]
@manalikundu 

Try removing all Xamarin.Auth nuget packages and re-install the same.

**Comment by fernandovm** [comment]
@moljac 

What's the expected behavior when the Android back button is pressed? In my code neither the OnCompleted, neither OnError events are raised. How we can detect this case?

**Comment by newky2k** [comment]
No response since may 2017
