### ISSUE TITLE
Xamarin.Auth and Xamarin.Auth.Extensions Resources conflict in Android

### ISSUE THREAD

**Issue by theVietCoder** [xamarin/Xamarin.Auth#171]
I recently installed Xamarin.Auth.Extension to use the refresh_token feature.
When I build the Android project, it throws the error in Resource.Designer.cs file:
The type 'Resource' exists in both 'Xamarin.Auth.Extensions, Version=1.3.0.14858, Culture=neutral, PublicKeyToken=null' and 'Xamarin.Auth, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null'
the resources:
`global::Xamarin.Auth.Resource.Id.webview
global::Xamarin.Auth.Resource.Layout.activity_webview
global::Xamarin.Auth.Resource.String.library_name
global::Xamarin.Auth.Resource.String.title_activity_webview`

I think because both package have same namespace, it causes this issue.

**Comment by uprightbass360** [comment]
I am also attempting to install Xamarin.Auth.Extensions and am receving the same error any time I attempt to access the type Resource. Is there any updates on this issue?

**Comment by jgold6** [comment]
This was also filed as bug report: https://bugzilla.xamarin.com/show_bug.cgi?id=57156

**Comment by jgold6** [comment]
Looks like this may be fixed by this commit: https://github.com/xamarin/Xamarin.Auth/commit/21cfde7ef498bda2bf12269d022df3e77c0130a3

**Comment by theVietCoder** [comment]
@jgold6 any idea when it'll be available on nuget?

**Comment by jgold6** [comment]
Unfortunately, I do not.

**Comment by theVietCoder** [comment]
The latest update in Nuget seems to resolve this issue.
