### ISSUE TITLE
Xamarin Form: Google Auth problems with native view

### ISSUE THREAD

**Issue by biapar** [xamarin/Xamarin.Auth#172]
Hi,
I'm able to authenticate with facebook, but with Google there are some troubles because it request to use native webview ( Google drop support to non native webview ). The problem is that xamarin.auth don't intercept return events.

**Comment by biapar** [comment]
Continue here https://github.com/xamarin/Xamarin.Auth/issues/151#issuecomment-297839054

**Comment by moljac** [comment]
No relevant data.
Closing this one.
