### ISSUE TITLE
How to close the view after authenticate without click on done button?

### ISSUE THREAD

**Issue by biapar** [xamarin/Xamarin.Auth#173]
How to close the view ( into shared project ) after authenticate without click on done button?
I'm using TODOAWSAuth example.
( like DismissViewController (true, null); )

**Comment by moljac** [comment]
@biapar

How about more info?

1. version
2. platform
3. Xamarin technology

**Comment by biapar** [comment]
Sorry. I made a new test and it close, now.

**Comment by moljac** [comment]
@biapar No need to be sorry. 
Which version is it? I added code to close CustomTabs last nighy in 15.0-alpha-11, but seems this depends on bunch of parameters like Android version (system image API level), Chrome Version (not sure 100%, testing) and Android.Support used.

Please can you provide info from above?

**Comment by moljac** [comment]
Closing this issue due to the comment: https://github.com/xamarin/Xamarin.Auth/issues/173#issuecomment-298501654
