### ISSUE TITLE
Android NativeUI RegisterNativeMethods 0 native methods

### ISSUE THREAD

**Issue by fileman** [xamarin/Xamarin.Auth#178]
Xamarin.auth with xamarin.auth.xamarinforms both 1.5.0 Alpha 15, following this [sample](https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences/tree/master/Xamarin.Forms/Evolve16Labs)

With AuthenticatorPage
`05-14 16:34:56.130 D/Mono    ( 2991): Assembly Ref addref MyProject[0xadbd3a40] -> Xamarin.Auth[0xb40d9c60]: 3
05-14 16:34:56.130 D/Mono    ( 2991): Assembly Ref addref EasySAD[0xadbd3a40] -> Xamarin.Auth.XamarinForms[0xb40d9ba0]: 2
05-14 16:34:56.130 D/Mono    ( 2991): Assembly Ref addref Xamarin.Auth.XamarinForms[0xb40d9ba0] -> Xamarin.Auth[0xb40d9c60]: 4
05-14 16:34:56.144 W/art     ( 2991): JNI RegisterNativeMethods: attempt to register 0 native methods for md5b45e996e2ca0ae5ccf67ed6721558f59.AuthenticatorPageRenderer
05-14 16:34:56.151 D/Mono    ( 2991): Assembly Ref addref Xamarin.Auth[0xb40d9c60] -> Xamarin.Android.Support.CustomTabs[0xadce1be0]: 2
05-14 16:34:56.164 D/Mono    ( 2991): Assembly Ref addref Xamarin.Auth[0xb40d9c60] -> System.Core[0xaa89f9c0]: 11
05-14 16:34:56.175 W/art     ( 2991): JNI RegisterNativeMethods: attempt to register 0 native methods for md53c585be971e02235139fd1aef11fc0c1.WebAuthenticatorNativeBrowserActivity_State`

With OAuthLoginPresenter
`05-14 16:28:26.031 D/Mono    ( 2779): Assembly Ref addref MyProject[0xadbd3920] -> Xamarin.Auth[0xadce1fa0]: 3
05-14 16:28:26.039 D/Mono    ( 2779): Assembly Ref addref Xamarin.Auth[0xadce1fa0] -> Xamarin.Android.Support.CustomTabs[0xadce1ac0]: 2
05-14 16:28:26.041 D/Mono    ( 2779): Assembly Ref addref Xamarin.Auth[0xadce1fa0] -> System.Core[0xaa8a58a0]: 11
05-14 16:28:26.074 W/art     ( 2779): JNI RegisterNativeMethods: attempt to register 0 native methods for md53c585be971e02235139fd1aef11fc0c1.WebAuthenticatorNativeBrowserActivity_State`

Same issue when I try to run sample.
Something is missing in current sample code?
thanks

**Comment by moljac** [comment]
@fileman 

Few questions:

1. Does it crash?
2. Android version?
3. Nuget version? (Forms, Android.Support.*, Auth)

Try updating and consolidating all nugets

**Comment by fileman** [comment]
1. Yes, with unhandled exception 
2. Android Emulator Hyper-V API 23 & Samsung API 22
3. Xamarin.Forms 2.3.4.231 - Android.Support.* 23.3.0 as required by Forms, Auth all alpha 15

In sample Android.Support.* are 25.1.1 ... we must use only this version?

**Comment by fileman** [comment]
And project is netstandard not PCL

**Comment by fileman** [comment]
ok, I've found problem was the netstandard project nuget reference, I've tried to install all manually and now work without issue.
Thanks for your help

**Comment by moljac** [comment]
@fileman

Again no need to thank me, you re welcome.

Can you give me some insights? 

Xamarin.Android has no netstandard support. Did you try to add it to netstandard project?

I asked Q about Android version, because most people having similar error use L and ART.

**Comment by fileman** [comment]
Xamarin has netstandard support or so I realized reading this [this blog](https://blog.xamarin.com/net-standard-library-support-for-xamarin/), I misunderstood?
The Portable class library in based on netstandard instead of PCL profiles.

**Comment by moljac** [comment]
@fileman 

> Xamarin has netstandard support or so I realized reading this this blog, I misunderstood?

Xamarin has support for netstandard - True. You did not misunderstood.

> The Portable class library in based on netstandard instead of PCL profiles.

This is your PCL. Right?
Xamarin.Auth does not support netstandard (yet). PCL (I think Profile259 or maybe 78) was created in 2015 and I didn;t have time to add netstandard support. 

> As I was saying something goes wrong until I install manually any packages.

I'm not sure how interpoperabiltiy works (netstandard and PCL) or how nuget handles it.
