### ISSUE TITLE
Google Login won't redirect on Android 5.0 and 6.0

### ISSUE THREAD

**Issue by choirunnisa** [xamarin/Xamarin.Auth#179]
Hi,

I successfully added the Google Login to my application using Xamarin.Auth version v1.5.0-alpha-12.
I followed the ComicBook sample using Xamarin.Auth.Presenters and it works fine on Android 7.0.
However on Android 5.0 and 6.0, everytime I login, it won't redirect back to the application but it shows the Google homepage instead.

My redirect url is: {mypackagename}:/oauth2redirect

I tried to upgrade to alpha-15, but the problem persists.
What did I miss?

Thank you in advance for your response.

**Comment by moljac** [comment]
@choirunnisa 

Interesting. Emulator? Chrome browser version?

Update Chrome 1st.

Can you try installing another Chrome version? Maybe Firefox or Opera?

**Comment by choirunnisa** [comment]
@moljac Both emulator and real device. 
I tried to install Google Chrome on the emulator, and now it works! Hooray!
Thank you very much for your help!
And thank you for dedicating your time in building, updating, and responding to issues on this awesome plugin.
Your work is very much appreciated :)

**Comment by JesseOlmer** [comment]
@moljac I'm seeing the same behavior but on a Nexus 5X running Android 7.1.2. I have the latest updates for Chrome according to the store (Chrome 58.0.3029.83). Using Xamarin.Auth 1.5.0-alpha-15.
```
new OAuth2Authenticator(
                    clientId: "<snip>.apps.googleusercontent.com",
                    clientSecret: null,
                    authorizeUrl: new Uri("https://accounts.google.com/o/oauth2/auth"),
                    accessTokenUrl: new Uri("https://www.googleapis.com/oauth2/v4/token"),
                    redirectUrl: new Uri("com.mealplanner:/oauth2redirect"),
                    scope: "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/plus.login",
                    getUsernameAsync: null,
                    isUsingNativeUI: true
                    );
```

I get the request for permissions page, followed by a very brief moment of "Loading [redirect url]" (see image below), then brought to the google homepage.
![image](https://cloud.githubusercontent.com/assets/10536384/26090823/2526bdcc-39bc-11e7-9cf6-38d29b455bfb.png)

My redirect matches my manifest:
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:installLocation="auto" package="com.mealplanner" ...
Let me know what other diagnostics I can provide. Thanks.

**Comment by moljac** [comment]
@choirunnisa 

Thanks a lot for your kind words.

I'm closing this one.
