### ISSUE TITLE
Please make it clear in the Wiki what platforms are supported

### ISSUE THREAD

**Issue by weitzhandler** [xamarin/Xamarin.Auth#181]
Is it suitable for Windows/Droid/iOS?

**Comment by moljac** [comment]
@weitzhandler 

All of them: "one ring to rule them all".

https://github.com/xamarin/Xamarin.Auth/tree/portable-bait-and-switch/source

https://github.com/xamarin/Xamarin.Auth/blob/portable-bait-and-switch/docs/readme-repo-root-old.md#status

23:59:59 day is too short for me to make everyone happy. I work on docs as of writing.

**Comment by weitzhandler** [comment]
Thank you guys so much for everything!

**Comment by moljac** [comment]
@weitzhandler I wish it is plural. But thanks for your kind words.

**Comment by weitzhandler** [comment]
@moljac 
LOL it says 'Member'...
Thank you then much more!
