### ISSUE TITLE
Changed Iphone but with the same AppleID: application crash on reading store values.

### ISSUE THREAD

**Issue by biapar** [xamarin/Xamarin.Auth#183]
Hi,
I installed the application on a first iPhone device and all works.
The I changed my Iphone, but I used the same Apple ID.
So, the application start and crash when read the values into the auth store.
Is there some possible to delete the store when the application will be deleted or manually delete the store on the Iphone?

**Comment by moljac** [comment]
Please wrap reading code in try/catch and check excpetion. Post it here.

it is (most likely) NRE, because there is no accounts on the new phone.

**Comment by biapar** [comment]
`store = AccountStore.Create();
            account = store.FindAccountsForService(Constants.AppName).FirstOrDefault();

            if (account != null)
            {
                //DependencyService.Get<INativeMsg>().ShowMsg("Restored previous session!");

                LoadProfile(account);

                FBbutton.IsVisible = false;
                IconaLogin.IsVisible = false;
                FBbuttonLogout.IsVisible = true;

                CrossLocalNotifications.Current.Show("Bagno 38", "Bentornato!");

            }
            else
            {

                //DependencyService.Get<INativeMsg>().ShowMsg("No session!");
                CrossLocalNotifications.Current.Show("Bagno 38", "Ciao! Effettua il login dal menu.");

            }`

**Comment by biapar** [comment]
Changed to:
`async void LoadProfile(Account account)
        {


            Loader.IsRunning = true;

            try
            {
                var request = new OAuth2Request("GET", new Uri(Constants.UserInfoUrl), null, account);
                var response = await request.GetResponseAsync();

                if (response != null)
                {

                    string userJson = await response.GetResponseTextAsync();

                    App.User = JsonConvert.DeserializeObject<User>(userJson);

                    User.Text = App.User.FirstName + " " + App.User.LastName;
                    Avatar.Source = UriImageSource.FromUri(new Uri(App.User.Picture.Data.url));

                    this.IsBusy = true;

                    MessagingCenter.Send<MenuPage>(this, "Hi");

                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine("Load Profile " + ex.Message);
                if (account != null)
                {
                    //AccountStore.Create().Delete(account, Constants.AppName);
                    store.Delete(account, Constants.AppName);
                }
            }



            

            Loader.IsRunning = false;
        }`

**Comment by biapar** [comment]
With the workaround it works.

**Comment by moljac** [comment]
@biapar 

I don't know why new account store is not created. I inherited the code and would need massive time to read and understand some details. It could be writing (locks etc), but not sure.

If this works please close the issue.
