### ISSUE TITLE
Xamarin.Auth with Google Drive API - How to start a DriveService with Xamarin.Auth.AccountStore

### ISSUE THREAD

**Issue by dbelcher** [xamarin/Xamarin.Auth#184]
Continued from [https://forums.xamarin.com/discussion/comment/277778](https://forums.xamarin.com/discussion/comment/277778)

I'm unable to create a Google DriveService with stored credentials from Xamarin.Auth.  I've created this minimal sample that I hope illustrates my problem:

[https://github.com/dbelcher/TestXamAuthGoogleDrive](https://github.com/dbelcher/TestXamAuthGoogleDrive)

There are a some TODO: items that must be filled in with a test-harness [Google API credentials](https://console.developers.google.com/apis/credentials):
1. Change the [ClientID here](https://github.com/dbelcher/TestXamAuthGoogleDrive/blob/master/TestXamAuthGoogleDrive/GoogleDriveAgent.cs#L40) and
2. Change the [ClientSecret here](https://github.com/dbelcher/TestXamAuthGoogleDrive/blob/master/TestXamAuthGoogleDrive/GoogleDriveAgent.cs#L43) and
3. Change the [RedirectURL here](https://github.com/dbelcher/TestXamAuthGoogleDrive/blob/master/TestXamAuthGoogleDrive/GoogleDriveAgent.cs#L46) and
4. Add test [URL scheme here](https://github.com/dbelcher/TestXamAuthGoogleDrive/blob/master/TestXamAuthGoogleDrive/Info.plist#L44) ...all to match those from the Google API test-harness app.

Once this is running, click Test Sign In ...once authorized, you will notice [an exception is thrown here](https://github.com/dbelcher/TestXamAuthGoogleDrive/blob/master/TestXamAuthGoogleDrive/GoogleDriveAgent.cs#L189).

Any insight into what I'm doing wrong would be greatly appreciated.  It is entirely possible the bug is between the keyboard and the chair.

**Comment by dbelcher** [comment]
I don't believe this is an issue with Xamarin.Auth.

**Comment by moljac** [comment]
@dbelcher 

It might be... Though not directly... 

Google Drive needs PATCH verb for some use cases and HttpMethod class does have all, but PATCH.

I will come to your sample as soon as I find some time.

**Comment by manonaga2188** [comment]
@dbelcher How did you able to upload file to google drive? can please show to sample code.

                Account GAcc = (Account)App.Current.Properties["GDACC"];
                Uri uri = new Uri("https://www.googleapis.com/upload/drive/v3/files?uploadType=media");
                OAuth2Request requestUpload = new OAuth2Request("POST", uri, null, GAcc);
                requestUpload.AddMultipartData("body", fileData,file_mimetype, fileName);

                var responseUpload = await requestUpload.GetResponseAsync();
                Debug.WriteLine(responseUpload);

I have used above code. When i see the file in drive it look like this.

![image](https://user-images.githubusercontent.com/35101045/49518154-f5be4a00-f8c3-11e8-8cc2-ff6bcf20bd16.png)
