### ISSUE TITLE
V 1.5.0 Stable: Error executing task LinkAssemblies: error XA2006: Could not resolve reference to CustomTabs

### ISSUE THREAD

**Issue by DFerenczi** [xamarin/Xamarin.Auth#185]
Hello again! 

I'm have the same problem as #167, wrote some comments there but thought that I should probably open a new one after doing some research. When I use stable version of 1.5.0 I still get this:

Error: Error executing task LinkAssemblies: error XA2006: Could not resolve reference to 'Android.Support.CustomTabs.CustomTabsClient/ExtraCallbackDelegate' 
(defined in assembly 'Xamarin.Auth, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.Android.Support.CustomTabs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. 
When the scope is different from the defining assembly, it usually means that the type is forwarded. (MyApp.Droid)

when trying to build in release.

From #167 I got the information that version 1.5.0 is pinned to CustomTabs version 23.3.0. So I started testing alpha versions and noticed that building in Release worked from 1.5.0-alpha-03 up to 1.5.0-alpha-08. Then when I updated to 1.5.0-alpha-09 it stopped working and does give me the error for every version over 09 (including stable). 

So I checked the commits and found this:

https://github.com/xamarin/Xamarin.Auth/commit/9e5117f6397bffd86ccfc9d7d9124f361e6d60fd#diff-f6026efe6e14c1b09646b2ba065b7706

So you upgraded the CustomTabs package right? Does this mean that we need to update to 25.3.1? 

I'm currently running Xamarin.Forms 2.3.4.247 and CustomTabs 23.3.0. 

Thanks in advance! 

/Ferenczi

**Comment by moljac** [comment]
@DFerenczi 
Package management became real problem since Xamarin.Forms support was added. Forms are pinned to 23.3.0.

Usually I encourage users to install with 23.3.0 and then update CustomTabs (and other Android support if that does not hurt badly). Minimal version is pinned to 23.3.0

I have similar setup and never hit similar problems. 

Try bumping and provide us feedback here pls.

**Comment by DFerenczi** [comment]
Alright, unfortunately updating other Android support does hurt badly and creates other conflicts in my project. Guess i'll have to use the alpha version for now until I have the time to resolve problems that appear when updating. 

Will post here when I update! 

/Ferenczi

**Comment by robintschroeder** [comment]
+1 experiencing the same problem and will attempt the same work around. I will be watching for an update Thanks @DFerenczi

**Comment by alexvitoriano** [comment]
+1 get the same error, when "link assemblies" are checked in project options.
in debug builds the error doesn't show

**Comment by kapslocker** [comment]
My PCL project builds with Xamarin.Auth 1.5.0 by updating CustomTabs and dependencies to 25.3.1.

I'm using the latest prerelease of Xamarin.Forms, with Android 7.1 as compile version.

**Comment by DFerenczi** [comment]
@kapslocker Thats interesting! I have not had the time to try updating my packages since updating the CustomTabs package requires updating all other Support packages to the same version (or at least bumping them to a higher version). The app I'm building is going live in a couple of days so for now the alpha version will be my option. But will try to update packages in the future!

**Comment by nuller1joe** [comment]
@kapslocker 
Thank you for the tip. Using Xamarin.Forms 2.3.5.255-pre5 with updated support packages made my project build in release!

**Comment by robintschroeder** [comment]
Upgrade to Xamarin.Auth 1.5.0.3 upgrade fixed it for me! Thanks!

**Comment by biapar** [comment]
I've the same problem and I blocked to release the apk.
The error is:
ion: error XA2006: Could not resolve reference to 'Android.Support.CustomTabs.CustomTabsClient/ExtraCallbackDelegate' (defined in assembly 'Xamarin.Auth, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.Android.Support.CustomTabs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve Android.Support.CustomTabs.CustomTabsClient/ExtraCallbackDelegate

**Comment by biapar** [comment]
@robintschroeder Which Xamarin Forms and Support libs version do you have?

**Comment by jenart** [comment]
@biapar update all your Xamarin.Android libraries to the latest v25.3.1 to match what is in the current Xamarin.Auth-master source.

Here is a working Android sample project: https://www.dropbox.com/s/gffs7uvj1xqp0zr/XamarinAuthTest.zip?dl=0

* See Xamarin.Auth-master\source\XamarinForms\Xamarin.Auth.Forms.Droid\packages.config

`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="monoandroid71" />
  <package id="PCLCrypto" version="2.0.147" targetFramework="monoandroid71" />
  <package id="PInvoke.BCrypt" version="0.5.64" targetFramework="monoandroid71" />
  <package id="PInvoke.Kernel32" version="0.5.64" targetFramework="monoandroid71" />
  <package id="PInvoke.NCrypt" version="0.5.64" targetFramework="monoandroid71" />
  <package id="PInvoke.Windows.Core" version="0.5.64" targetFramework="monoandroid71" />
  <package id="Validation" version="2.4.15" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Animated.Vector.Drawable" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Annotations" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Compat" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Core.UI" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Core.Utils" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.CustomTabs" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Design" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Fragment" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Media.Compat" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Transition" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v4" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.AppCompat" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.CardView" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.MediaRouter" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.Palette" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.RecyclerView" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Vector.Drawable" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Build.Download" version="0.4.4" targetFramework="monoandroid71" />
  <package id="Xamarin.Forms" version="2.3.4.247" targetFramework="monoandroid71" />
</packages>`

**Comment by biapar** [comment]
So I need install Android 7 SDK? 
I've now the v6. 
Have you installed Xamarin.Auth.Forms or Xamarin.Auth?

**Comment by robintschroeder** [comment]
@biapar 

Microsoft Visual Studio Enterprise 2017 
Version 15.2 (26430.14) Release
VisualStudio.15.Release/15.2.0+26430.14
Microsoft .NET Framework
Version 4.6.01586

Mono Debugging for Visual Studio   Mono.Debugging.VisualStudio
Support for debugging Mono processes with Visual Studio.

Xamarin   4.5.0.486 (fec6f88)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android SDK   7.3.1.2 (9dbc4c5)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   10.10.0.37 (ad35de4)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by robintschroeder** [comment]
@biapar 
Xamarin.Forms v2.3.4.247
Xamarin.Auth v1.5.0.3
Xamarin.Build.Download v0.4.5

**Comment by biapar** [comment]
@robintschroeder Have you update the Android Support Libs to v25.3.1?

**Comment by robintschroeder** [comment]
@biapar  not quite - I am running Xamarin.Android.Support... v25.1.0
hth

**Comment by newky2k** [comment]
@biapar  @DFerenczi @robintschroeder @jenart @alexvitoriano Can you please try this with the latest version of Xamarin.Auth

Regards

**Comment by newky2k** [comment]
no resonse after two weeks closing
