### ISSUE TITLE
Login Screen for Android is not destroyed?

### ISSUE THREAD

**Issue by SuhanKoh** [xamarin/Xamarin.Auth#189]
# Xamarin.Auth Issue

On Android, if using 'is_using_native_ui = false', while showing the login screen, rotate the screen to landscape, then back to portrait. Then Login. You will be required to login three time. (The non-native-ui is creating each instance on rotate while not destroying.)
Is is an expected behavior?

### Version 1.5.0

- [x] nuget version = 1.5.0

### Steps to reproduce

1. Using'is_using_native_ui = false', while showing the login screen.
2.  Rotate screen, login page will be created without destroying.

**Comment by newky2k** [comment]
@SuhanKoh can you try this on the latest version please.

Regards

**Comment by newky2k** [comment]
no response after two weeks, closing
