### ISSUE TITLE
How to avoid showing redirect url on screen while using xamarin.auth For linkedin sign-in

### ISSUE THREAD

**Issue by ruchiverma6** [xamarin/Xamarin.Auth#191]
# Xamarin.Auth Issue

*IF BUG, INCLUDE THIS PART:*

### Version

- [ ] nuget version = Xamarin.auth 1.5.0
- [ ] component version = 
- [ ] sample

### Steps to reproduce

1. For Xamarin Forms, on android device once user gets successfully authenticated for LinkedIn sign in, redirect url screen is coming for 2 seconds instead of directly going in app, then after 2 seconds user lands to app screen.

I m using xamarin.auth library and using below code:

var authenticator = new OAuth2Authenticator(
StringConstants.LinkedInClientId,
StringConstants.ClientSecret,
StringConstants.Scope,
new Uri(StringConstants.AuthorizeUrl),
new Uri(redirectUrl),
new Uri(StringConstants.AccessTokenUrl));

//redirectUrl is valid website url.

authenticator.Completed += OnAuthCompleted;
authenticator.Error += OnAuthError;
authenticator.ShowErrors = false;
var presenter = new Xamarin.Auth.Presenters.OAuthLoginPresenter();
presenter.Login(authenticator);

After above log-in call I get call back in following method:

void OnAuthCompleted(object sender, AuthenticatorCompletedEventArgs e)
{
Account account = 
store.FindAccountsForService(DeploymentConstants.AppTitle).FirstOrDefault();
var authenticator = sender as OAuth2Authenticator;
if (authenticator != null)
{
authenticator.Completed -= OnAuthCompleted;
authenticator.Error -= OnAuthError;
}
if (e.IsAuthenticated)
{
var values = e.Account.Properties;
var access_token = values["access_token"];
Settings.AuthData = access_token;
if (account != null)
{
store.Delete(account, DeploymentConstants.AppTitle);
}
store.Save(account = e.Account, DeploymentConstants.AppTitle);
}

}

Then in further flow I m calling:
await Navigation.PopModalAsync();

Platform: Xamarin forms, Android device

-	[] .NET version = 4.5
-	[] mono version = 

### Expected behaviour

Once user authenticates successfully using xamarin.auth for LinkedIn sign-in, user should go to app screen instead of showing redirect url on screen.

### Actual behaviour

For Xamarin forms, on android device once user gets successfully authenticated, redirect url screen is coming for 2 seconds instead of directly going in app, then after 2 seconds user lands to app screen.

Tell us what happens instead
Can you also include a screen shot?

*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by newky2k** [comment]
@ruchiverma6 can you please try this with the latest version please.

Regards

**Comment by newky2k** [comment]
no response for two weeks, closing
