### ISSUE TITLE
WP8.1 Fails Store Certification because of Xamarin.Auth's dependency on PCLCrypto 2.x

### ISSUE THREAD

**Issue by HelenMamalaki** [xamarin/Xamarin.Auth#193]
# Xamarin.Auth Issue
- [ ] nuget version = 1.3.1.1 >

### Steps to reproduce

Using Xamarin.Auth in PCL and Windows Phone8.1 project. App fails Windows Store certification with an unsupported APIs error (see zip file for certification report). The issue is with APIs used by PCLCrypto which Xamarin.Auth is dependent on. There is an issue open for PCLCrypto since last year with no resolution; https://github.com/AArnott/PCLCrypto/issues/97
[Certification Report.zip](https://github.com/xamarin/Xamarin.Auth/files/1098154/Certification.Report.zip)

Platform:

-	[] .NET version = .NET Framework 4.5
-	[] mono version =

**Comment by newky2k** [comment]
@HelenMamalaki  the PCLCrypto bug has been fixed and the latest version is Store compatible
