### ISSUE TITLE
possible issue in documentation showing how to register custom scheme for Android

### ISSUE THREAD

**Issue by sanjogs** [xamarin/Xamarin.Auth#195]
# CustomURLSchemeInterceptor documentation Issue
Using code from following section of the documentation did not produce expected behavior
https://github.com/xamarin/Xamarin.Auth#code

Changing LaunchMode to **LaunchMode.SingleTask** instead of  LaunchMode.SingleTop produced the expected behavior for me.

Tried on Android 5.1.1

### Expected behaviour
Custom Tabs should close (UI should return back to app) if user cancels, or Signs in with the third party.

### Actual behaviour
UI does not return back to app after hitting cancel or after successful sign in.

**Comment by newky2k** [comment]
@sanjogs  Can you please try this with the latest version.

Regards

**Comment by newky2k** [comment]
no response for two weeks, closing
