### ISSUE TITLE
More than 1000 errors at opening sln... Nuget may not restore... Big piece of shit

### ISSUE THREAD

**Issue by SergeyOrlovXIM** [xamarin/Xamarin.Auth#196]
# Xamarin.Auth Issue

*IF BUG, INCLUDE THIS PART:*

### Version

- [ ] nuget version = 
- [ ] component version = 
- [ ] sample

### Steps to reproduce

1.
2.
3.

Platform:

-	[] .NET version = 
-	[] mono version = 

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead
Can you also include a screen shot?

*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by moljac** [comment]
Closing due to lack of information
