### ISSUE TITLE
What is the nuget Xamarin.Auth.XamarinForms package?

### ISSUE THREAD

**Issue by biapar** [xamarin/Xamarin.Auth#199]
What is the nuget Xamarin.Auth.XamarinForms package?

**Comment by jenart** [comment]
Have a look here: https://github.com/xamarin/Xamarin.Auth/wiki/Details#xamarinforms-support

If you are using Xamarin.Forms then you should use the Xamarin.Auth.XamarinForms package if you are wanting to use custom renderers.

**Comment by moljac** [comment]
@biapar 

Xamarin.Forms comes with 2 implementations

- Presenters which have no dependency on Xamarin.Forms packages, but can be used for Xamarin.Forms. This is in Xamarin.Auth itself.
- Custom Renderers which are in Xamarin.Auth.XamarinForms package. This implementation is not tested as well as Presenters.

@jenart Thanks for pointing this out.

**Comment by EmilAlipiev** [comment]
hi, is there any sample code or sample app to see how to use it and how different this than xamarin.auth package? Do we do all coding in shared code or we still have to code something on native level for each project type?
