### ISSUE TITLE
Implement log out/sing off

### ISSUE THREAD

**Issue by xrkolovos** [xamarin/Xamarin.Auth#200]
OAuthLoginPresenter should have a method to log out/sing off. 

The user is still sing in the authority. OidcClient has a method to logout.
https://github.com/IdentityModel/IdentityModel.OidcClient/blob/73a56fdef54009ed471445079ef2fdeb6e4159ea/src/Shared/OidcClient.cs

That is a security issue as said in #113

**Comment by EndlessDelirium** [comment]
I would also appreciate if this would be implemented

**Comment by marisst** [comment]
Until then you can do something like this:
```csharp
const string EndSessionUrl = "https://yourIdentityServer.com/identity/endsession";
const string LogoutRedirectUrl = "https://localhost/yourLogoutRedirectUrl";

var requestParameters = new Dictionary<string, string>
{
    { "id_token_hint", idToken },
    { "post_logout_redirect_uri", LogoutRedirectUrl }
};
var request = new Request("GET", new Uri(EndSessionUrl), requestParameters);
var response = await request.GetResponseAsync();
```

**Comment by Redth** [comment]
Not currently on our roadmap.  If you need to explicitly log out, you'll need to do it yourself as suggested in a previous comment.
