### ISSUE TITLE
Integrate accounts with android account manager?

### ISSUE THREAD

**Issue by dazinator** [xamarin/Xamarin.Auth#205]
### Feature description

Android has a concept of an [AccountManager](https://developer.android.com/reference/android/accounts/AccountManager.html), and Authenticator services which are platform level services.

Does Xamarin Auth integrate with these two components? Ideally, i'd like for my accounts to show up under android's "accounts and sync" screen, and for other non-xamarin apps (we have some native android apps) to be able to retreive these accounts and access tokens. Am I right in thinking Xamarin Auth has it's own implementation of this stack, and doesn't integrate here with the android platform?

**Comment by moljac** [comment]
@dazinator 

Xamarin.Auth uses `KeyStore`

https://github.com/xamarin/Xamarin.Auth/blob/master/source/Xamarin.Auth.XamarinAndroid/PlatformSpecific/AndroidAccountStore.cs

Seems like feasible and not complex enhancement. I will take a look, but not sure when can I implement it. 

Any ideas how fast do you need it? Yesterday?

**Comment by dazinator** [comment]
Thanks. No rush!
I've done some experiments with the android account manager recently and I thought it might be a good enhancement for xamarin.auth. I like the fact it means you can see the user accounts properly listed on the device, and also that it opens up the possibility of writing things like android SyncAdaptors (which is how android schedules background sync for user accounts) which is useful to me. I've rolled my own JWT authentication for the time being so that I can take advantage of these things.

The mechanism I ended up using was:

1. When a new user account is created I store the refresh token for the account in the android user accounts "password" field.
2. When something uses accountmanager to request an auth token for a particular user account, my authinticator service grabs the refresh token on the account and calls the webservice to get an access token from the refresh token. I cache this access token for future use. (My access tokens last about 5 mins).
3. I disabled the android account managers own cache for auth tokens - so it always defers to my authentication service (point 2) when an auth token for an account is requested - in which I use my own cache.

I haven't yet handled what happens when a refresh token is blacklisted.. but one step at a time :-)

**Comment by nielscup** [comment]
+1 for AccountManager: another huge benefit is that you kan use the same account for multiple apps. This is not possible with KeyStore because this is only accessible to the owning app.

**Comment by Redth** [comment]
This seems like a good idea but is currently out of the scope of this project.  We are deprecating Keystore and recommend using Xamarin.Essentials' SecureStorage https://docs.microsoft.com/en-us/xamarin/essentials/secure-storage

You can always manage adding your account to Android Account Manager yourself.  I don't believe this should be the default behavior as it adds some additional potential security risks.

Sorry, but we will not be adding this feature.
