### ISSUE TITLE
Webview won't dismiss if "Not Now" is tapped in facebook

### ISSUE THREAD

**Issue by arctouch-oberdanbitencourt** [xamarin/Xamarin.Auth#206]
# Xamarin.Auth Issue

### Version

- [X] nuget version = 1.5.0.3

### Steps to reproduce
I'm using the following code in my Xamarin.Forms (PCL) project:
```csharp
OAuth2Authenticator auth = new OAuth2Authenticator
(
                clientId: "", //ommited for security reasons
                scope: "",
                authorizeUrl: new Uri("https://m.facebook.com/dialog/oauth/"),
                redirectUrl: new Uri("https://mycustomuri.com/signin-facebook"), //ommited for security reasons
                isUsingNativeUI: false
            )
            {
                ShowErrors = false,
            };

            auth.Completed += OnAuthenticationCompleted;
            auth.Error += OnAuthenticationFailed;
            AuthenticationState.Authenticator = auth;

            var presenter = new Xamarin.Auth.Presenters.OAuthLoginPresenter();
            presenter.Login(auth);
```

1. In the Facebook webview, tap on the "Not Now" link
2. auth.Error event is called but webview is not dismissed.

Platform:

- [x] mono version = 5.2.0.196 (2017-04/478c04a) (64-bit)
- [x] XCode version = Xcode 8.3.3 (12175.1)
- [x]  Xamarin.iOS Version = 10.12.0.12 
- [x]  Xamarin.Android Version = 7.4.0.13
- [x]  Android SDK Tools Version = 26.0.2
- [x]  Android SDK Platform Tools Version = 26.0.0
- [x]  Android SDK Build Tools Version = 26.0.0
- [x]  Java SDK version = 1.8.0_121

### Expected behaviour

I excpect when an error occurs in the webviews, the auth flow should be cancelled and the webview (UIViewController or Activity) should be dismissed/closed.

### Actual behaviour

The webview doesn't get closed - page remains the same.
Error message from AuthenticatorErrorEventArgs.Message: `OAuth Error = Permissions+error`

Can you also include a screen shot?
![xamarinauthfacebookbug](https://user-images.githubusercontent.com/11648468/27969256-89dc15ea-6320-11e7-8d06-1f5c5d3d68ed.gif)

**Comment by moljac** [comment]
@arctouch-oberdanbitencourt 
Facebook only?
Investigating, but info is more than welcome?

**Comment by SirLanceLang** [comment]
Seems to be the same that is reported in 217 for Google and Mircrosoft as well.
https://github.com/xamarin/Xamarin.Auth/issues/217

**Comment by Vijay4657** [comment]
Hi Everyone, 
Anyupdate on this issue.?

**Comment by Emixam23** [comment]
Is it doing it as well for UWP?

**Comment by Vijay4657** [comment]
this issue occurs in android and ios, but i have not checked in UWP.

**Comment by newky2k** [comment]
@arctouch-oberdanbitencourt  @SirLanceLang  @Vijay4657 @Emixam23  Can you please check this with the latest version of Xamarin.Auth, and the other xamarin ecosystem elements.

Regards

**Comment by sergiobonillamorales** [comment]
In your **OnAuthenticationFailed** method you need to add 

`var authenticator = sender as OAuth2Authenticator;`
`authenticator.OnCancelled();`

I hope it works.
Regards,
Sergio.

**Comment by newky2k** [comment]
thanks @sergiobonillamorales
