### ISSUE TITLE
How to set aud property in Google ID Token as my server client ID?

### ISSUE THREAD

**Issue by HyoseopSong** [xamarin/Xamarin.Auth#207]
Is it possible to set the 'aud' property of Google ID token as my server client ID?
I can get google ID token by below code snippet.

```
async void OnAuthCompleted(object sender, AuthenticatorCompletedEventArgs e)
        {
           ...
            if (e.IsAuthenticated)
            {
                ...
                var id_token = e.Account.Properties["id_token"];
                ...
            }
            ...
        }
```

The problem is the 'aud' property of token is my Mobile App client ID and  same with the 'azp' property. What I want is the 'aud' property is my backend client ID.

In google document, the 'aud' property can be set as below code line.

```
GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
        .requestIdToken(getString(R.string.server_client_id))
        .build();
```

On the other hands, I think OAuth2Authenticator constructor doesn't have any parameter that deliver my backend client ID.

```
var authenticator = new OAuth2Authenticator(
                clientId,
                null,
                Constants.Scope,
                new Uri(Constants.AuthorizeUrl),
                new Uri(redirectUri),
                new Uri(Constants.AccessTokenUrl),
                null,
                true);
```
How can I pass my backend client ID to google ID token?

**Comment by Redth** [comment]
Not currently on our roadmap.
