### ISSUE TITLE
AuthState grows on serialisation/deserialisation

### ISSUE THREAD

**Issue by zBrianW** [xamarin/Xamarin.Auth#211]
# Xamarin.Auth Issue

*IF BUG, INCLUDE THIS PART:*

### Version

- [ ] nuget version = 
- [x] component version = 1.5.0 (also replicated with 1.5.3)
- [ ] sample

### Steps to reproduce

1. as per this [issue identified in openid AppAuth-Android](https://github.com/openid/AppAuth-Android/issues/224), the same is experiencing with Xamarin.OpenId.AppAuth.Android.
2.
3.

Platform:

- [x] .NET version = .NETStandard 1.4
- [ ] mono version = 

### Expected behaviour

The AuthState's "mLastTokenResponse" > "additionalParameters" node's additionalParameters should not continue to grow after each request.

### Actual behaviour
The AuthState's "mLastTokenResponse" > "additionalParameters" node's additionalParameters grows after each request.

Can you also include a screen shot?
please see [issue identified in openid AppAuth-Android](https://github.com/openid/AppAuth-Android/issues/224)

**Comment by newky2k** [comment]
@zBrianW can you please try this in the latest version

**Comment by newky2k** [comment]
no response for two weeks, closing
