### ISSUE TITLE
Developer-intended toast showing up after login

### ISSUE THREAD

**Issue by hardcodet** [xamarin/Xamarin.Auth#214]
# Xamarin.Auth Issue

### Version

- [ ] nuget version = 1.5.0.3

### Steps to reproduce

I am seeing a popup upon native auth on Google after returning from the Google account selection page which fades after a bit: _If CustomTabs Login Screen does not close automatically, close CustomTabs by navigating back to the app._ From the wording, I assume the message is intended for developers:

<img src="https://user-images.githubusercontent.com/873009/28747560-50a22240-74a2-11e7-979e-0b5a591859d6.png" width="200" />

**Comment by moljac** [comment]
@hardcodet 
Check `Xamarin.Auth.CustomTabsConfiguration.` class. 
Set the warning message to `null` and it will not be shown.

NOTE: alpha API, subject to changes!! Undocumented for that reason.

**Comment by hardcodet** [comment]
That was easy - thanks! :)

Note for others - the property is the following. Just set it when initializing Xamarin.Auth in your main activity:

    //don't show warning message when closing account selection page
    CustomTabsConfiguration.CustomTabsClosingMessage = null;
