### ISSUE TITLE
Contributors, Please Clarify: Does this version work with Azure Mobile Client or Not?

### ISSUE THREAD

**Issue by dgerding** [xamarin/Xamarin.Auth#215]
Hi,
I've been trying to figure out if I am supposed to be using this Nuget for Xamarin.Auth with mobile app on Azure (using Azure Mobile App Client and Server libraries) or am I supposed to be using this one
["Auth for Azure"](https://github.com/azure/azure-mobile-services-xamarin-auth/tree/46aa4f283caaef23beb1b0786e6837f4bc29fe66) ?

I am targeting Xamarin.Forms "235.Pre6" using .Net Standard project for the Xam Forms project and trying, unsuccessfully, to use either 4.0.0 or 4.0.1 of [Azure Mobile Client](https://github.com/Azure/azure-mobile-apps-net-client)

**I am only trying to use Xamarin.Auth for secure account and token storage abstract.**  What ever the "right" way to get authentication working again for Azure and Xamarin on 4.x will someone please respond?

Thanks, sincerely.
Dave G

**Comment by moljac** [comment]
@dgerding 
Xamarin.Auth has changed a lot in version 1.4. and 1.5 to support Native UI. I contacted Azure Mobile Service Client team and am being in contact with them, but they decided to keep their own fork of Xamarin.Auth. This means they must change code to compile Xamarin.Auth for their need (mostly changing  `public` to `internal`).

Recent changes to Xamarin.Auth (coming in 1.5.0.4, after my vacation - 2 more weeks)  have preprocessor defines to reduce changes for Azure Mobile Service Client team, so they will be able to do the changes faster.

Last info from their team was that the Xamarin.Auth code (their fork) was under review. When this will be available - I have no idea. My suggestion is ping them pls. I simply have no time to try to implement AMSC myself.

... and if the answer is OK for you close the issue, pls.

**Comment by newky2k** [comment]
no response since Aug 2017
