### ISSUE TITLE
Google/Android: Cancelling from account selection doesn't fire event

### ISSUE THREAD

**Issue by hardcodet** [xamarin/Xamarin.Auth#217]
# Xamarin.Auth Issue

### Version

- [ ] nuget version = Android, 1.5.0.3

### Steps to reproduce

1. Go to account selection
2. Cancel instead of selecting an account by tapping the "x" icon (marked in the screenshot)
3. No event fires

### Expected behaviour

Looking at the source, I assume `OnCancelled` should be invoked and the `Completed` event should fire.

### Actual behaviour

No event fires and my app remains to wait for the login process to complete.

<img src="https://user-images.githubusercontent.com/873009/28959843-82f77e12-78fc-11e7-8caa-6dddd98acff6.png" width="300"></img>

**Comment by SirLanceLang** [comment]
This happens as well for the Back button in the embedded view for Microsoft Login.
The Error event is being fired.

**Comment by newky2k** [comment]
@hardcodet @SirLanceLang  can you try this on the latest version please?

**Comment by newky2k** [comment]
no repsonse for two weeks closing
