### ISSUE TITLE
Exception using isUsingNativeUI: true ? For facebook

### ISSUE THREAD

**Issue by marcelocferdeveloper** [xamarin/Xamarin.Auth#218]
I am reading the doc, but if i set isUsingNativeUI: true i got a exception. If i set to false, works ! 
Its for facebook login...
I am a begginer. Do i need to set something on MainActivity ? beside             global::Xamarin.Auth.Presenters.XamarinAndroid.AuthenticationConfiguration.Init(this, bundle);

**Comment by gabrielsalmeida** [comment]
Same issue for me!

**Comment by moljac** [comment]
@marcelinhovt @gabrielsalmeida 

Sorry, but I'll need more info:

1.  is it Xamarin.Forms app? 
2. if yes: are you using Presenters or Renderers?
3. Did you initialize Presenter?

Thanks

**Comment by marcelinhovt** [comment]
1- yes
2- Presenters
3- Yes! For sure...

2017-08-19 13:16 GMT-03:00 Miljenko Cvjetko moljac moki mel <
notifications@github.com>:

**Comment by dagostinelli** [comment]
+1 Same issue, but for Google.  When I do isUsingNativeUI: false, it doesn't throw an exception (but google blocks it because it's using a web view)

**Comment by dagostinelli** [comment]
Here is some code that shows the same issue on google.

```
// Initialize
global::Xamarin.Auth.Presenters.XamarinAndroid.AuthenticationConfiguration.Init(this, bundle);
```

Then:
```
	    public partial class LoginPage : ContentPage
		{		
			...
			
			async void OnGoogleLoginButtonClicked(object sender, EventArgs e)
			{
				var authenticator = new OAuth2Authenticator(
					clientId,
					"https://www.googleapis.com/auth/userinfo.email",
					new Uri("https://accounts.google.com/o/oauth2/auth"),
					new Uri(<secret>),
					null,
					true);

				authenticator.Completed += OnAuthCompletedGoogle;
				authenticator.Error += OnAuthError;

				var presenter = new Xamarin.Auth.Presenters.OAuthLoginPresenter();
				presenter.Login(authenticator);
				
				// When it exits here -- it crashes				
				// There is no detail in the exception
				
			}
			
			...
		}

```

**Comment by dagostinelli** [comment]
I made progress, but it's not perfect yet.  Here's what I did to improve things (TLDR; upgrade everything)

NOTE: the fact that I had to do this implies there is some seriously wrong monkey business in Xamarin.

1) Re-Targeted the entire project to v7.1 (up from 6.0)
2) Remove Xamarin.Auth
3) Downgrade Xamarin.Forms to 2.3.4.247 (so that I could upgrade the Xamarin Android Support libraries)
4) Upgrade all of the Xamarin Android Support Libraries
5) Reinstall Xamarin.Forms to 2.3.4.270 

Problem solved

Monkey business leads to more monkey business.  Someone needs to find the root cause of this instability in Xamarin.  It's not in Xamarin. Auth in this case.  There is widespread fragmentation in the GUI development world these days.  It used to be a lot better than this.

**Comment by muhaym** [comment]
I have the same issue

No meaningful exceptions. Working perfectly in iOS, but in Android

```
[] * Assertion at /Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/mono/mini/debugger-agent.c:8956, condition `locals->locals [i].index < header->num_locals' not met
[google-breakpad] ### ### ### ### ### ### ### ### ### ### ### ### ###
[google-breakpad] Chrome build fingerprint:
[google-breakpad] 1.0
[google-breakpad] 1
[google-breakpad] ### ### ### ### ### ### ### ### ### ### ### ### ###
[libc] Fatal signal 6 (SIGABRT), code -6 in tid 32084 (Debugger agent)
```

Xamarin.Forms Version : 2.3.4.270
CustomTab Version: Tried with 25.3.1 and 25.4.0.2 
Target 7.1
Minimum API LEVEL 15

Have been facing this issue past 3 days.

**Comment by moljac** [comment]
@muhaym Can you please create minimal sample and share it (either repo or zip)?

This would help me a lot. 
I will replace nuget references with project and test it.

**Comment by dagostinelli** [comment]
@muhaym Are all of your Xamarin Android Support Libraries up to date (latest versions)?  (Look at NuGet Package Manager -- see any updates for Android Support Libraries)

**Comment by muhaym** [comment]
@dagostinelli  Yes

**Comment by newky2k** [comment]
@marcelinhovt @gabrielsalmeida @dagostinelli  can you please try this with the latest version.

**Comment by newky2k** [comment]
no response for over two weeks, closing
