### ISSUE TITLE
Google API Authenticating Users with an Identity Provider

### ISSUE THREAD

**Issue by Dermendzhiev** [xamarin/Xamarin.Auth#219]
I am still getting used to Xamarin.Forms and I am on very basic level. I went through many articles for my issue, but to the end couldn't resolve it. So...

Currently I am trying to add Google authentication inside my Xamarin.Forms application, which use Droid and iOS (no WP). So far I am following guide from [here](https://developer.xamarin.com/guides/xamarin-forms/cloud-services/authentication/oauth/). I am using Xamarin.Auth to authenticate to Google.

Here is some part from my source code.

The problem is coming after my method complete it's work. So after my last line:

`presenter.Login(authenticator);`

everything looks alright and debugging I am following that compiler goes out of method without any errors, but then I receive exception, which you can see [here](https://prnt.sc/g8ii9q). It's "**No compatible code running**".

Here some more information regarding my source code:

- [Source ](https://prnt.sc/g8inln)of "Constants" class used for client ids and URLs
- [Source ](https://prnt.sc/g8ijji)of implemented methods for on authentication complete/error, which in fact still I cannot hit because of my error
- [Source ](https://prnt.sc/g8ik3i)of Android MainActivity where I added

`global::Xamarin.Auth.Presenters.XamarinAndroid.AuthenticationConfiguration.Init(this, bundle);`

[Source ](https://prnt.sc/g8il5f)of UrlSchemeInterceptorActivity
Here are the main articles I went through deeply => [Link 1](http://www.joesauve.com/using-xamarin-auth-with-xamarin-forms/), [Link 2](https://forums.xamarin.com/discussion/19021/using-xamarin-auth-with-xamarin-forms) and[ Link 3](https://forums.xamarin.com/discussion/99753/how-to-use-xamarin-oauth-presenters-login-method-for-google), but still couldn't resolve the issue.

I am not sure where the error comes from, or can I can I continue debugging it to resolve issue.

Thanks in advance

**Comment by Dermendzhiev** [comment]
Found solution, I provide it [here](https://stackoverflow.com/questions/45684166/xamarin-forms-google-api-authenticating-users-with-an-identity-provider)

**Comment by moljac** [comment]
@Dermendzhiev 
If you have found an solution and if it is not related to Xamarin.Auth (in this case it is not) please close the issue.

In the future please go to the community slack team channel where you can get help a lot faster.

Thanks

**Comment by Dermendzhiev** [comment]
Closed issue: Invalid reference
