### ISSUE TITLE
Object reference not set to an instance of an object 

### ISSUE THREAD

**Issue by jigneshbodarya** [xamarin/Xamarin.Auth#222]
# Xamarin.Auth Issue
Xamarin.Forms/Evolve16Labs/Droid/ComicBook.Droid.csproj: Object reference not set to an instance of an object 
*IF BUG, INCLUDE THIS PART:*
While trying to run android project in xamarin forms getting this error
### Version
=== Xamarin Studio Community ===

Version 6.3 (build 864)
Installation UUID: 5d3a5d5e-7841-46a7-8ad3-61c053d98ea2
Runtime:
	Mono 5.2.0.215 (d15-3/da80840) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 502000215

=== NuGet ===

Version: 3.5.0.0

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Xamarin.Android ===

Version: 7.4.0.21 (Xamarin Studio Community)
Android SDK: /Volumes/Untitled 2/04/sdk
	Supported Android versions:
		2.3    (API level 10)
		4.2    (API level 17)
		4.3    (API level 18)
		4.4    (API level 19)
		4.4.87 (API level 20)
		5.0    (API level 21)
		5.1    (API level 22)
		6.0    (API level 23)
		7.0    (API level 24)
		7.1    (API level 25)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 26
SDK Build Tools Version: 26.0.1

Java SDK: /usr
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Not Installed

=== Apple Developer Tools ===

Xcode 8.3.1 (12170)
Build 8E1000a

=== Xamarin.Mac ===

Version: 3.6.0.19 (Xamarin Studio Community)

=== Xamarin.iOS ===

Version: 10.12.0.20 (Xamarin Studio Community)
Hash: 80b8487d
Branch: d15-3
Build date: 2017-08-18 16:07:26-0400

=== Build Information ===

Release ID: 603000864
Git revision: 6c2f6737278ccc3e81e12276d49c0d92f975f189
Build date: 2017-04-24 11:26:01-04
Xamarin addins: d8d46e577d8507c35260ce9d73df3c33415bb214
Build lane: monodevelop-lion-d15-1

=== Operating System ===

Mac OS X 10.12.4
Darwin Maliks-iMac.local 16.5.0 Darwin Kernel Version 16.5.0
    Fri Mar  3 16:52:33 PST 2017
    root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64

- [ ] nuget version = 3.5.0.0
- [ ] component version =   7.4.0.21
- [ ] sample

### Steps to reproduce

1. download code from repo
2. extract it update and restore package
3. run android project

Platform: Android

-	[] .NET version = 6.3
-	[] mono version = Mono 5.2.0.215

### Expected behaviour
Project need to should be run
Tell us what should happen
whole compiling it returns error
### Actual behaviour
Project giving compile error
Tell us what happens instead
Can you also include a screen shot?

*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by moljac** [comment]
@jigneshbodarya 

I'm sorry, but I will need more info:

1. Xamarin.Auth version
2. Are Presenters or Renderers used?
3. Which provider?

> Expected behaviour
> Project need to should be run
> Tell us what should happen
> whole compiling it returns error

Seems like project is running. NRE (NullReferenceException, "Object reference not set to an instance of an object" is runtime error.

Did you initialize Presneters?

> Actual behaviour
> Project giving compile error

Is it NRE runtime or compile error?

If you cannot answer these questions please create repo with minimal sample and add link to it so I can test.

**Comment by jigneshbodarya** [comment]
I am getting this error after updating package
Downloaded latest version from github repo

Give me some time I will add repo so you can test it

**Comment by jigneshbodarya** [comment]
Here is a dropbox link you can download and test it
https://www.dropbox.com/s/7xy6hbva41nw5al/Evolve16Labs.zip?dl=0

**Comment by newky2k** [comment]
@jigneshbodarya can you please try this with the latest version.

**Comment by newky2k** [comment]
no repsonse for three week, closing
