### ISSUE TITLE
Xamarin Auth - Facebook & GooglePlus

### ISSUE THREAD

**Issue by Emixam23** [xamarin/Xamarin.Auth#224]
I'm currently begining to work with `Xamarin.Auth` and I'm facing 2 problems for which I'm stuck since 1 day and half..

I have this piece of code :

    public class OAuth
	{
		private Account account;
		private AccountStore store;

		// These values do not need changing
		public string Scope;
		public string AuthorizeUrl;
		public string AccessTokenUrl;
		public string UserInfoUrl;

		string clientId;
		string redirectUri;

        private Func<JObject, User> OAuthParser;

        private Action<User> OnCompleted;
        private Action<string> OnError;

        public OAuth()
        {
            account = null;
            store = null;

            Scope = "";
            AuthorizeUrl = "";
            AccessTokenUrl = "";
            UserInfoUrl = "";

            clientId = "";
            redirectUri = "";
        }

		public OAuth Facebook()
		{
			// These values do not need changing
			Scope = "public_profile";
			AuthorizeUrl = "https://m.facebook.com/dialog/oauth/";
			AccessTokenUrl = "";
			UserInfoUrl = "";

			switch (Device.RuntimePlatform)
			{
				case Device.iOS:
					clientId = "<insert IOS client ID here>";
					redirectUri = "<insert IOS redirect URL here>:/oauth2redirect";
					break;

				case Device.Android:
					clientId = "206316176526191";
					redirectUri = "http://www.facebook.com/connect/login_success.html";
					break;
			}

			OAuthParser = ParseFacebookResponse;

			return this;
		}

        public OAuth GooglePlus()
		{
			// These values do not need changing
			Scope = "https://www.googleapis.com/auth/userinfo.email";
			AuthorizeUrl = "https://accounts.google.com/o/oauth2/auth";
			AccessTokenUrl = "https://www.googleapis.com/oauth2/v4/token";
			UserInfoUrl = "https://www.googleapis.com/oauth2/v2/userinfo";

			switch (Device.RuntimePlatform)
			{
				case Device.iOS:
					clientId = "<insert IOS client ID here>";
					redirectUri = "<insert IOS redirect URL here>:/oauth2redirect";
					break;

				case Device.Android:
					clientId = "548539660999-muighch5brcrbae8r53js0ggdad5jt45.apps.googleusercontent.com";
					redirectUri = "com.googleusercontent.apps.548539660999-muighch5brcrbae8r53js0ggdad5jt45:/oauth2redirect";
					break;
			}

			OAuthParser = ParseGooglePlusResponse;

			return this;
		}

		public OAuth2Authenticator Authenticator(Action<User> onCompleted, Action<string> onError)
		{
			OAuth2Authenticator authenticator = new OAuth2Authenticator(
                clientId,
                null,
                Scope,
                new Uri(AuthorizeUrl),
                new Uri(redirectUri),
                new Uri(AccessTokenUrl),
                null,
                false);

        authenticator.Completed += OnAuthCompleted;
        authenticator.Error += OnAuthError;

            OnCompleted = onCompleted;
            OnError = onError;

            return authenticator;
		}

        private async void OnAuthCompleted(object sender, AuthenticatorCompletedEventArgs e)
        {
		OAuth2Authenticator OAuth2Authenticator = sender as OAuth2Authenticator;
		if (OAuth2Authenticator != null)
		{
			OAuth2Authenticator.Completed -= OnAuthCompleted;
			OAuth2Authenticator.Error -= OnAuthError;
		}

		//User user = null;
		if (e.IsAuthenticated)
		{
			// If the user is authenticated, request their basic user data from Google
			// UserInfoUrl = https://www.googleapis.com/oauth2/v2/userinfo
			var request = new OAuth2Request("GET", new Uri(UserInfoUrl), null, e.Account);
			var response = await request.GetResponseAsync();
			if (response != null)
			{
                    // Deserialize the data and store it in the account store
                    // The users email address will be used to identify data in SimpleDB
                    string str = await response.GetResponseTextAsync();
                    JObject jobject = JObject.Parse(str);
                    User user = OAuthParser(jobject);

                    OnCompleted(user);
			}

			if (account != null)
			{
				store.Delete(account, App.AppName);
			}

			await store.SaveAsync(account = e.Account, App.AppName);
		}
    }

    private void OnAuthError(object sender, AuthenticatorErrorEventArgs e)
    {
            OAuth2Authenticator OAuth2Authenticator = sender as OAuth2Authenticator;

		if (OAuth2Authenticator != null)
		{
			OAuth2Authenticator.Completed -= OnAuthCompleted;
			OAuth2Authenticator.Error -= OnAuthError;
		}

		OnError("Authentication error: " + e.Message);
    }

        private static User ParseGooglePlusResponse(JObject jobject)
        {
            try
            {
                User user = new User()
                {
                    Email = jobject["email"].ToString(),
                    Pseudo = jobject["name"].ToString(),
                    Firstname = jobject["given_name"].ToString(),
                    Surname = jobject["family_name"].ToString(),
                    Image = jobject["picture"].ToString(),
                    Password = "girafe"
                };
                return user;
            }
            catch (Exception e) 
            { Debug.WriteLine(e.ToString()); }
            return null;
        }

		private static User ParseFacebookResponse(JObject jobject)
		{
			try
			{
                Debug.WriteLine(jobject);
				User user = new User()
				{
					Email = jobject["email"].ToString(),
					Pseudo = jobject["name"].ToString(),
					Firstname = jobject["given_name"].ToString(),
					Surname = jobject["family_name"].ToString(),
					Image = jobject["picture"].ToString(),
					Password = "girafe"
				};
				return user;
			}
			catch (Exception e)
			{ Debug.WriteLine(e.ToString()); }
			return null;
		}
    }

So, I'm using this class like that:

    private void FacebookAuthConnection()
        {
            AuthenticationState.Authenticator = OAuthService.Facebook().Authenticator(OAuthLoginCompleted, OAuthLoginError);
            Presenter.Login(AuthenticationState.Authenticator);
        }

However, the problems are coming.. First, GooglePlus works, but I got an alert on my android phone that says *"Chrome Custom Tabs Doesn't Close ..."*, so the application crashes with an empty stack trace... I searched on the web and the only thing I got is to turn false the last parameter of `new OAuth2Authenticator();`, which doesn't work since google doesn't allow it from a webview...

So I was like, ok my code works, I get the user infos blablabla, let's try with facebook if it works from the native browser. However, I can't find the parameters URL...

    Scope = "";
    AuthorizeUrl = "";
    AccessTokenUrl = "";
    UserInfoUrl = "";

 - **Scope** seems to be `public_profile`
 - **AuthorizationUrl** would be `https://m.facebook.com/dialog/oauth/`

But what about the 2 others? I have them for Google+.

I'm really stuck and I feel like, each new seconds that passes, I get more and more frustrated...

Thank !

**Comment by newky2k** [comment]
@Emixam23 can you provide a small sample to replicate this issue and help us investigate

**Comment by newky2k** [comment]
no repsonse for two weeks, closing
