### ISSUE TITLE
NullReferenceException in Xamarin.Auth.Presenters.OAuthLoginPresenter.Login()

### ISSUE THREAD

**Issue by dagostinelli** [xamarin/Xamarin.Auth#225]
# Xamarin.Auth Issue

### Version

- [ ] nuget version = 4.0.0.2283
- [ ] Xamarin.Auth version = 2.3.4.270

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Fody" version="2.1.2" targetFramework="portable45-net45+win8+wp8+wpa81" developmentDependency="true" />
  <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="Newtonsoft.Json" version="10.0.3" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="PCLCrypto" version="2.0.147" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="PropertyChanged.Fody" version="2.1.4" targetFramework="portable45-net45+win8+wp8+wpa81" developmentDependency="true" />
  <package id="Validation" version="2.2.8" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="Xamarin.Auth" version="1.5.0" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="Xamarin.Auth.XamarinForms" version="1.5.0.3" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="Xamarin.Forms" version="2.3.4.270" targetFramework="portable45-net45+win8+wp8+wpa81" />
</packages>
```

### Steps to reproduce

1. Stick a button on a form

2. Put this code into the handler.  (I lifted this code from the following sample)

https://github.com/xamarin/xamarin-forms-samples/tree/master/WebServices/OAuthNativeFlow/OAuthNativeFlow

        void OnLoginClicked(object sender, EventArgs e)
        {
            string clientId = null;
            string redirectUri = null;

            switch (Device.RuntimePlatform)
            {
                case Device.iOS:
                    clientId = Constants.iOSClientId;
                    redirectUri = Constants.iOSRedirectUrl;
                    break;

                case Device.Android:
                    clientId = Constants.AndroidClientId;
                    redirectUri = Constants.AndroidRedirectUrl;
                    break;
            }

            var authenticator = new OAuth2Authenticator(
                clientId,
                null,
                Constants.Scope,
                new Uri(Constants.AuthorizeUrl),
                new Uri(redirectUri),
                new Uri(Constants.AccessTokenUrl),
                null,
                true);

            AuthenticationState.Authenticator = authenticator;

            var presenter = new Xamarin.Auth.Presenters.OAuthLoginPresenter();
            presenter.Login(authenticator);
        }

Platform:

-	[] .NET version = ??
-	[] mono version = ??

### Expected behaviour

Expect it to login / show the Google or Facebook site

### Actual behaviour

I get a null reference exception.  The stack trace shows all my code except for this 1 line where the exception is (inside the Xamarin.Auth library)

`  at Xamarin.Auth.Presenters.OAuthLoginPresenter.Login (Xamarin.Auth.Authenticator authenticator) [0x00012] in <79c158e996ba43a7a588d390cd5d4c2d>:0 `

**Comment by moljac** [comment]
@dagostinelli 
Did you initialize Presenter??

**Comment by dagostinelli** [comment]
That was it.  Thank you.  I looked up what you meant and found instructions.

For anyone else who runs into this, here are some [detailed instructions here](https://developer.xamarin.com/guides/xamarin-forms/cloud-services/authentication/oauth/).

**Comment by Bgamal** [comment]
@dagostinelli please show me the code you added or modified as i faced same problem and cannot fix

**Comment by Bgamal** [comment]
@dagostinelli:
   void OnLoginClicked(object sender, EventArgs e)
        {
			string clientId = null;
			string redirectUri = null;

			switch (Device.RuntimePlatform)
			{
				case Device.iOS:
					clientId = Constants.iOSClientId;
					redirectUri = Constants.iOSRedirectUrl;
					break;

				case Device.Android:
					clientId = Constants.AndroidClientId;
					redirectUri = Constants.AndroidRedirectUrl;
					break;
			}

            //var authenticator = new OAuth2Authenticator(
            //	clientId,
            //	null,
            //	Constants.Scope,
            //	new Uri(Constants.AuthorizeUrl),
            //	new Uri(redirectUri),
            //	new Uri(Constants.AccessTokenUrl),
            //	null,
            //	false);



            var authenticator = new OAuth2Authenticator(
                clientId: "Clientid",
                clientSecret: "ClientSecret",
                scope: Constants.Scope,
                authorizeUrl: new Uri(Constants.AuthorizeUrl),
                accessTokenUrl: new Uri(Constants.AccessTokenUrl),
                redirectUrl: new Uri(redirectUri),
                getUsernameAsync: null,
                isUsingNativeUI: true
            );

          
            authenticator.Completed += OnAuthCompleted;
			authenticator.Error += OnAuthError;
            authenticator.IsLoadableRedirectUri = true;
            AuthenticationState.Authenticator = authenticator;

			var presenter = new Xamarin.Auth.Presenters.OAuthLoginPresenter();
			presenter.Login(authenticator);
        }

**Comment by Bgamal** [comment]
@dagostinelli , i did but error still exist

**Comment by UlliStirnweiss** [comment]
I am facing the same issue with the NullReferenceException nevertheless I initialized the AuthenticationConfiguration. Even with the current version 1.7.0 I have this problem. Are you working on this?

**Comment by isurzhenko** [comment]
@dagostinelli Works great! Thank you!

**Comment by Tushar5292** [comment]
> @dagostinelli:
> void OnLoginClicked(object sender, EventArgs e)
> {
> string clientId = null;
> string redirectUri = null;
> 
> ```
> 		switch (Device.RuntimePlatform)
> 		{
> 			case Device.iOS:
> 				clientId = Constants.iOSClientId;
> 				redirectUri = Constants.iOSRedirectUrl;
> 				break;
> 
> 			case Device.Android:
> 				clientId = Constants.AndroidClientId;
> 				redirectUri = Constants.AndroidRedirectUrl;
> 				break;
> 		}
> 
>         //var authenticator = new OAuth2Authenticator(
>         //	clientId,
>         //	null,
>         //	Constants.Scope,
>         //	new Uri(Constants.AuthorizeUrl),
>         //	new Uri(redirectUri),
>         //	new Uri(Constants.AccessTokenUrl),
>         //	null,
>         //	false);
> 
> 
> 
>         var authenticator = new OAuth2Authenticator(
>             clientId: "Clientid",
>             clientSecret: "ClientSecret",
>             scope: Constants.Scope,
>             authorizeUrl: new Uri(Constants.AuthorizeUrl),
>             accessTokenUrl: new Uri(Constants.AccessTokenUrl),
>             redirectUrl: new Uri(redirectUri),
>             getUsernameAsync: null,
>             isUsingNativeUI: true
>         );
> 
>       
>         authenticator.Completed += OnAuthCompleted;
> 		authenticator.Error += OnAuthError;
>         authenticator.IsLoadableRedirectUri = true;
>         AuthenticationState.Authenticator = authenticator;
> 
> 		var presenter = new Xamarin.Auth.Presenters.OAuthLoginPresenter();
> 		presenter.Login(authenticator);
>     }
> ```


@dagostinelli 
Is your above code ref is working for Ios i want implement this on Ios.
