### ISSUE TITLE
Xamarin.Auth UWP side

### ISSUE THREAD

**Issue by Emixam23** [xamarin/Xamarin.Auth#231]
Hi,

I would like to know how does work the redirection (OnSuccess) on UWP because I stay on google and I the webview doesn't get closed.. 

I know that, on Android, I need the following class :

    using System;
    using Android.App;
    using Android.Content;
    using Android.Content.PM;
    using Android.OS;
    using PROJECT.Sources.Components;

    namespace PROJECT.Droid.Sources.DependencyServices
    {
    	[Activity(Label = "CustomUrlSchemeInterceptorActivity", NoHistory = true, LaunchMode = LaunchMode.SingleTop)]
    	[IntentFilter(
    		new[] { Intent.ActionView },
    		Categories = new[] { Intent.CategoryDefault, Intent.CategoryBrowsable },
    		DataSchemes = new[] { "com.googleusercontent.apps.xxxxxxxxxx=xxxxxxxxxxxxxxx", "http://www.facebook.com/connect/login_success.html" },
    		DataPath = "/oauth2redirect")]
    	public class CustomUrlSchemeInterceptorActivity : Activity
    	{
    		protected override void OnCreate(Bundle savedInstanceState)
    		{
    			base.OnCreate(savedInstanceState);

    			// Convert Android.Net.Url to Uri
    			var uri = new Uri(Intent.Data.ToString());

    			// Load redirectUrl page
    			AuthenticationState.Authenticator.OnPageLoading(uri);

    			Finish();
    		}
    	}
    }

But what about UWP?

Thank for any help !

**Comment by moljac** [comment]
@Emixam23 

This is completely different story from Android, so forget Android. Check topics on deep-linking (app-linking) for UWP and Windows platforms in general (WinRT Windows and WIndows Phone are very similar).

I work on updating samples (Windows platforms especially) and I hope this will be done this week. I'm blocked with some CI (msbuild) issues and work on bug reporting for Visual Studio team.

Or wait until I finish those samples (they were finished, but I need to refactor them for easier maintenance and testing)

**Comment by Emixam23** [comment]
@moljac 

Hi, alright, thank you, I'll see what I can find and also wait what you'll release :)

**Comment by Emixam23** [comment]
Hey !

Could you move forward on the UWP side?

**Comment by moljac** [comment]
@Emixam23 
I would if I could.

I have problems with builds, because of .NET Standard support which was recently added.

**Comment by Emixam23** [comment]
:'( I search on the web but I still don't know if I need interceptors or any other extension to handle the redirection over UWP

Maybe I haven't done the good searches, idk but still stuck on it ...

**Comment by moljac** [comment]
@Emixam23 

On UWP and other Windows platforms app-linking/deep-linking is called "link/url activation".
You need:
1. App.cs must have OnActivated(object, SomeEventArgs) (link activation/deep-linking)
2. Package.appxmanifest schema def
3. Main page code behind in my samples has switch/case with 3 cases Android, iOS, Windows. Windows is the one.

I have collected few links but need time to find those.

**Comment by Emixam23** [comment]
Hi,

Well, I'm still stuck, I keep working weekly on my project and over UWP, it still doesn't work..

I searched and worked based on what you said and, the problème I got is about the links. I added them as protocols to the apppackagesManifest and it seems like they can't be accepted in the Name fields:

    Logo : 
    Display name :
    Name : http://www.facebook.com/connect/login_success.html

    ...


then, when I build, it throws this :

    Description : Validation error. error C00CE169: 
    App manifest validation error: The app manifest must be 
    valid as per schema: Line 31, Column 25, Reason:

    'http://www.facebook.com/connect/login_success.html'
    violates maxLength constraint of '39'. The attribute 'Name' with value 
    'http://www.facebook.com/connect/login_success.html' failed to parse.

**Comment by RadekES** [comment]
If you are using Facebook Auth with NativeUI than redirect url may be different (shorter):

```
if (isUsingNativeUI)
            {
                authenticator = new OAuth2Authenticator(
                    clientId: ClientId,
                    scope: "",
                    authorizeUrl: new Uri("https://m.facebook.com/v2.10/dialog/oauth "),
                    redirectUrl: new Uri($"fb{ClientId}://authorize"),
                    getUsernameAsync: null,
                    isUsingNativeUI: true
                )
                {
                    AllowCancel = true,
                    ShowErrors = false
                };
            }
            else
            {
                authenticator = new OAuth2Authenticator
                (
                    clientId: ClientId,
                    scope: "",
                    authorizeUrl: new Uri(
                        "https://m.facebook.com/v2.10/dialog/oauth "),
                    redirectUrl: new Uri("https://m.facebook.com/connect/login_success.html"),
                    getUsernameAsync: null, 
                    isUsingNativeUI: false
                )
                {
                    AllowCancel = true,
                    ShowErrors = false
                };
            }
```

It works in iOS and solves the problem with protocol name length in UWP... but actually still not works for me in UWP :) no redirection (protected override void OnActivated(IActivatedEventArgs args) isn't called).... and can't logout/forget successfully logged user in iOS (as I described in my question in other topic, no answers yet) :)

If you find a way how to make it all works together :) please put some info here...

**Comment by moljac** [comment]
@RadekES 

> no redirection (protected override void OnActivated(IActivatedEventArgs args) isn't called).... 

Did you add custom scheme definition in Package.appxmanifest? You need to tell OS which app (your app should be opened for some custom-scheme url).

> and can't logout/forget successfully logged user in iOS (as I described in my question in other topic, no answers yet)

Are you talking about UWP or iOS? Please do not mix topics it makes reading, answering and troubleshooting very difficult.

For that You must go to Safari (actually device settings) and logout user.

https://github.com/OAuthSwift/OAuthSwift/issues/235#issuecomment-226457350

See how it is done:

https://github.com/OAuthSwift/OAuthSwift/wiki/Logout

I'm rewriting large parts of Xamarin.Auth to enable some standard OAuth2 features like

- refresh_token
- token revocation (AKA logout, sign-out)

**Comment by RadekES** [comment]
@moljac 

Thank you very much for your answe and links. I'm sorry for mixing platforms little bit.

In UWP app manifest I have (with correct ClientId).

```
<Extensions>
        <uap:Extension Category="windows.protocol">
          <uap:Protocol Name="fb1234567890123456" />
        </uap:Extension>
       <uap:Extension Category="windows.protocol">
          <uap:Protocol Name="com.yourcompany.appname" />
        </uap:Extension>
 </Extensions>
```

It works fine in Mobile Emulator, but when run code on Local Machine after successfully login it stuck on blank Facebook page, in same code Google auth works fine and redirect back to app.

**Comment by Emixam23** [comment]
@RadekES can you provide (with some edit for private data) your UWP AppPackageManifest? Because I don't find where you add these lines of code...

    <?xml version="1.0" encoding="utf-8"?>
    <Package xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10" xmlns:mp="http://schemas.microsoft.com/appx/2014/phone/manifest" xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10" IgnorableNamespaces="uap mp">
      <Identity Name="xxxx-xxxxxxxxxx-xxxxxxxxxxx-xxxx" Publisher="CN=Emixam23" Version="0.1.0.0" />
      <mp:PhoneIdentity PhoneProductId="xxxx-xxxxxxxxxx-xxxxxxxxxxx-xxxx" PhonePublisherId="00000000-0000-0000-0000-000000000000" />
      <Properties>
        <DisplayName>Project.UWP</DisplayName>
        <PublisherDisplayName>Emixam23</PublisherDisplayName>
        <Logo>Assets\StoreLogo.png</Logo>
      </Properties>
      <Dependencies>
        <TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.0.0" MaxVersionTested="10.0.0.0" />
      </Dependencies>
      <Resources>
        <Resource Language="x-generate" />
      </Resources>
      <Applications>
        <Application Id="App" Executable="$targetnametoken$.exe" EntryPoint="Project.UWP.App">
          <uap:VisualElements DisplayName="Project.UWP" Square150x150Logo="Assets\Square150x150Logo.png" Square44x44Logo="Assets\Square44x44Logo.png" Description="Project.UWP" BackgroundColor="transparent">
            <uap:DefaultTile Wide310x150Logo="Assets\Wide310x150Logo.png">
            </uap:DefaultTile>
            <uap:SplashScreen Image="Assets\SplashScreen.png" />
          </uap:VisualElements>
        </Application>
      </Applications>
      <Capabilities>
        <Capability Name="internetClient" />
        <DeviceCapability Name="location" />
      </Capabilities>
    </Package>

**Comment by RadekES** [comment]
@Emixam23  no problem, bigger part bellow, you can just put it inside <Application>. You can also edit easier in manifest editor in VS, like in the picture. In code bellow "fb1234567890123456" is for Facebook and "com.yourcompany.appname" for Google .

![p12](https://user-images.githubusercontent.com/30774825/32122006-2d610cf2-bb5f-11e7-8140-460077981477.png)


```
<Applications>
    <Application Id="App" Executable="$targetnametoken$.exe" EntryPoint="XAuth01.UWP.App">
      <uap:VisualElements DisplayName="XAuth01.UWP" Square150x150Logo="Assets\Square150x150Logo.png" Square44x44Logo="Assets\Square44x44Logo.png" Description="XAuth01.UWP" BackgroundColor="transparent">
        <uap:DefaultTile Wide310x150Logo="Assets\Wide310x150Logo.png">
        </uap:DefaultTile>
        <uap:SplashScreen Image="Assets\SplashScreen.png" />
      </uap:VisualElements>
      <Extensions>
        <uap:Extension Category="windows.protocol">
          <uap:Protocol Name="fb1234567890123456" />
        </uap:Extension>
        <uap:Extension Category="windows.protocol">
          <uap:Protocol Name="com.yourcompany.appname" />
        </uap:Extension>
      </Extensions>
    </Application>
  </Applications>

```

**Comment by Emixam23** [comment]
Thank I'll take a look in few minutes :)

**Comment by Emixam23** [comment]
I tried:

    <Extensions>
        <uap:Extension Category="windows.protocol">
          <uap:Protocol Name="http://www.facebook.com/connect/login_success.html" />
        </uap:Extension>
      </Extensions>

But I get this error when I put the cursor over the URL in the source file:

    The 'name' attribute is invalid - The value 'http://www.facebook.com/connect/login_success.html' is invalid according to its datatype 'http://schemas.microsoft.com/appx/manifest/uap/type:ST_Protocol_2010_v2' - The Pattern constraint failed

And when I build:

    Description: Validation error. error C00CE169: App manifest validation error: The app manifest must be valid as per schema: Line 31, Column 25, Reason: 'http://www.facebook.com/connect/login_success.html' violates maxLength constraint of '39'. The attribute 'Name' with value 'http://www.facebook.com/connect/login_success.html' failed to parse.

Also, I'm just showing the XML part because, I don't know but, it seems easier to me when it's source code instead of a GUI or something like that :)

**Comment by RadekES** [comment]
```
<uap:Extension Category="windows.protocol">
          <uap:Protocol Name="fb1234567890123456" />
</uap:Extension>
```

This is protocol name you suppose to use there (of course with you FB client ID), not the link. And when you create authenticator, check my previous example, it is also with ClientId, so in this case redirectUri is "fb1234567890123456://authorize"

```
redirectUrl: new Uri($"fb{ClientId}://authorize")
```

**Comment by Emixam23** [comment]
Thank you for your answer, however, after I logged in, the app stay on a white facebook page

**Comment by RadekES** [comment]
This problem appear when you run on Windows (not mobile), right? If so, this is the problem I mentioned before

> It works fine in Mobile Emulator, but when run code on Local Machine after successfully login it stuck on blank Facebook page. In same code Google auth in UWP Local Machine works fine and redirect back to app.

And unlucky I didn't find any solution yet for Facebook NativeUI on desktop computer (as I mentioned this code works fine in UWP Mobile)... :( Good news is that with facebook you don't have to use NativeUI and than it works fine :) 

Did you try if not NativeUI version will works for you? Than you not need any new protocol in manifest, just register for some events

```
authenticator.Completed += OnFacebookAuthCompleted;
authenticator.Error += OnFacebookAuthError;
```

**Comment by Emixam23** [comment]
I see :)

Ok you know what, I'll try sunday evening (gmt +1) and come back here. (Lucky me) I have a windows phone running UWP so i'll be able to try to move forward on the test :)

**Comment by Emixam23** [comment]
Hi :)

It doesn't seems to work on mobile neither :(

**Comment by RadekES** [comment]
Hi! :) Hmm... Checked just no my test code... and on a mobile simulator, it works. What exactly not working in your case on mobile?

**Comment by Emixam23** [comment]
The redirection on success, I tried on a Nokia Lumia, let me answer you properly later today :)

**Comment by EmilAlipiev** [comment]
Did you guys find a solution for uwp local?

**Comment by newky2k** [comment]
@Emixam23 @radekdoulik Is this still an issue?

**Comment by newky2k** [comment]
RadoslawKubas Is this still an issue?

**Comment by newky2k** [comment]
no response for over two weeks, closing
