### ISSUE TITLE
UWP: Payload contains two or more files with the same destination path 'Xamarin.Auth.pdb'.

### ISSUE THREAD

**Issue by mesta1** [xamarin/Xamarin.Auth#232]
Hello,
I got an error message that is preventing me to use Windows Mobile Center build server because of this library.
This happens when I try to compile the UWP app on Windows Mobile Center, whatever configuration I use.
Xamarin.Auth is referenced both in the UWP project and in a portable library.
Any idea on how to fix it ?

Here is the full log:

##[error]C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1743,5): Error APPX1101: Payload contains two or more files with the same destination path 'Xamarin.Auth.pdb'. Source files: 
C:\Users\buildguest\.nuget\packages\Xamarin.Auth\1.5.0.3\lib\uap10.0\Xamarin.Auth.pdb
d:\a\1\s\MyProject.Contracts\bin\Debug\Xamarin.Auth.pdb
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1743,5): error APPX1101: Payload contains two or more files with the same destination path 'Xamarin.Auth.pdb'. Source files:  [d:\a\1\s\MyProject.T10.UWP\MyProject.T10.UWP.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1743,5): error APPX1101: C:\Users\buildguest\.nuget\packages\Xamarin.Auth\1.5.0.3\lib\uap10.0\Xamarin.Auth.pdb [d:\a\1\s\MyProject.T10.UWP\MyProject.T10.UWP.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1743,5): error APPX1101: d:\a\1\s\MyProject.Contracts\bin\Debug\Xamarin.Auth.pdb [d:\a\1\s\MyProject.T10.UWP\MyProject.T10.UWP.csproj]
Done Building Project "d:\a\1\s\MyProject.T10.UWP\MyProject.T10.UWP.csproj" (default targets) -- FAILED.
Done Building Project "d:\a\1\s\MyProject.sln" (default targets) -- FAILED.

**Comment by moljac** [comment]
@mesta1 

Try disabling PDB generation - this was my [re]solution/workaround, but it is not pretty.

This has been reported to Visual Studio team and issue is under investigation.

"Error when using Project References for libraries that implement NuGet bait-n-switch - Payload contains two or more files with the same destination path"

https://developercommunity.visualstudio.com/content/problem/53431/error-when-using-project-references-for-libraries.html

I'm currently generating minimal sample[s] for Visual Studio team, so they can investigate that.

This is not strictly Xamarin.Auth problem, but Visual Studio and I would appreciate if you would close this issue.

**Comment by mesta1** [comment]
Thank you !

**Comment by dnet78** [comment]
had the same problem turned out that the problem was in the build screen I had the Arm platform targeting the x86 platform for some reason. resolved it by making sure all platforms were targetting themselves
