### ISSUE TITLE
Bug size of the window with Facebook Authentificator on IOS

### ISSUE THREAD

**Issue by Clemon-R** [xamarin/Xamarin.Auth#233]
# Xamarin.Auth Issue

Hello,

I have a problem with facebook authentificator, "the window is too small to continue."
![image001](https://user-images.githubusercontent.com/23109272/30797218-6e8afa2e-a1d5-11e7-8bc3-29524daf6030.png)

with this code:
OAuth2Authenticator authenticator = new OAuth2Authenticator("XXXXXXXXXXXX",
                "public_profile,publish_actions,manage_pages,publish_pages",
                new Uri("https://m.facebook.com/dialog/oauth"),
                new Uri("https://www.facebook.com/connect/login_success.html"));

This bug happen only on IOS

**Comment by newky2k** [comment]
@Clemon-R can you please try the latest version of Xamarin.Auth to see if this is a still a problem

**Comment by newky2k** [comment]
no response for over two weeks, closing
