### ISSUE TITLE
Capture the screen (prevent showing offline page)?

### ISSUE THREAD

**Issue by SuhanKoh** [xamarin/Xamarin.Auth#235]
Is there a way to override the page when you call Authenticate while you're offline?
Right now it will display the default offline page (android will show the whole URL on the screen).

### Steps to reproduce

1. Turn on airplane mode
2. Call Xamarin.Auth authentication
3. It should show the offline page.

**Comment by moljac** [comment]
@SuhanKoh 
Not that I'm aware of. But I must admit good idea for improvement/enhancement. I will try to add it ASAP. It might be available in 1.5.0.4, just to solve NET standard and UWP build issues on CI servers and I will publish it.

**Comment by SuhanKoh** [comment]
@moljac Thanks for the response. On the iOS, Xamarin Auth actually throw a dialog message (Can't be canceled) that also cannot be overrided (correct me if I am wrong). The dialog shows "Authentication Error e.Message =" "The internet connection appears to be offline."

It would be nice to not show this kind of message for user.

**Comment by Redth** [comment]
Thanks for the suggestion but this is not on our roadmap.  You should check connectivity before attempting to authenticate.
