### ISSUE TITLE
Facebook login failed with Xamarin.Auth

### ISSUE THREAD

**Issue by higher-faster-better** [xamarin/Xamarin.Auth#238]
I am developing an app that needs Facebook and Google login in Xamarin Forms. 

I found a guidance here for social login.
https://developer.xamarin.com/guides/xamarin-forms/cloud-services/authentication/oauth/

I was able to get success in Google login with that guidance

Here is the code that I've tried for Google login.

        string clientId = null;
        string redirectUri = null;
            
        switch (Device.RuntimePlatform)
        {
            	case Device.iOS:
            		clientId = ApiUrl.iOSClientId;
            		redirectUri = ApiUrl.iOSGoogleRedirectUrl;
            		break;
            
            	case Device.Android:
            		clientId = ApiUrl.AndroidClientId;
            		redirectUri = ApiUrl.AndroidGoogleRedirectUrl;
            		break;
        }
            
        var authenticator = new OAuth2Authenticator(
            	clientId,
            	null,
            	ApiUrl.GoogleScope,
            	new Uri(ApiUrl.GoogleAuthorizeUrl),
            	new Uri(redirectUri),
            	new Uri(ApiUrl.GoogleAccessTokenUrl),
            	null,
            	true
        );
        
        authenticator.Completed += OnAuthCompleted;
        authenticator.Error += OnAuthError;
        
        AuthenticationState.Authenticator = authenticator;
        
        var presenter = new Xamarin.Auth.Presenters.OAuthLoginPresenter();
        presenter.Login(authenticator);

The redirect urls like these

```
public static string iOSGoogleRedirectUrl = "com.googleusercontent.apps.675078306211-aqmafds8gk67h538eqius9pg9j89ajoc:/oauth2redirect";
public static string AndroidGoogleRedirectUrl = "com.googleusercontent.apps.675078306211-b0t2i7sbcrp05ilt6iu4k455snbov7cp:/oauth2redirect";
```

I've tried similar thing in facebook login. Here is the code that I've tried for Facebook login.

```
var authenticator = new OAuth2Authenticator(
                ApiUrl.AppId,
                ApiUrl.FacebookScope,
                new Uri(ApiUrl.FacebookAuthorizeUrl),
                new Uri(ApiUrl.FacebookRedirectUrl),
            	null,
            	true
        );
            
        authenticator.Completed += OnAuthCompleted;
        authenticator.Error += OnAuthError;
            
        AuthenticationState.Authenticator = authenticator;
            
        var presenter = new Xamarin.Auth.Presenters.OAuthLoginPresenter();
        presenter.Login(authenticator);
```

The redirect url likes this

    public static string FacebookRedirectUrl = "fb506102719744051:/oauth2redirect";
        
**But I am getting error in Facebook login.
**It says "The redirect_uri URL is not supported"****

I think I may have an error in redirect url for facebook. but I am not sure what should be set for redirect url in facebook.

Please help me to fix this!
Sorry for my English, Thanks.

**Comment by moljac** [comment]
@higher-faster-better 

Do not worry about your English. 

FB `redirect_url` is not docummented. It was found by one community member in the code of FB SDK and it looks like this:

https://github.com/xamarin/Xamarin.Auth/blob/master/samples/Xamarin.Forms/Evolve16Labs/05-OAuth/Portable/Views/SamplesQuick/ProvidersSamplesQuickPage.Facebook.xaml.cs#L69

so for you:

```
   fb506102719744051://authorize
```

Close the issue if this helps pls.

**Comment by higher-faster-better** [comment]
WOW, It works for me, I really appreciate. @moljac 
Thanks.

**Comment by higher-faster-better** [comment]
More question here for facebook login in android

It doesn't need to add following code to manifest file?
```
        <meta-data 
	    android:name="com.facebook.sdk.ApplicationId" 
            android:value="@string/facebook_app_id"/>
        <activity 
	    android:name="com.facebook.FacebookActivity"
            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="MyTenantWorld Resident" />
        <activity
            android:name="com.facebook.CustomTabActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
        </activity>
```

**Comment by higher-faster-better** [comment]
If I add it to manifest, the app crashes during facebook login.
If I don't add it to manifest, the control is not return to app.

Thanks for your help!

**Comment by moljac** [comment]
@higher-faster-better 
Do not edit AndroidManifest.xml manually - use c# Attributes you have intellisense/autocomplete etc:
See here

https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences/blob/master/Xamarin.Forms/Evolve16Labs/Droid/Xamarin.Auth/ActivityCustomUrlSchemeInterceptor.cs#L32

and here

https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences/blob/master/Xamarin.Forms/Evolve16Labs/Droid/Xamarin.Auth/ActivityCustomUrlSchemeInterceptor.cs#L49

and here:

https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences/blob/master/Xamarin.Forms/Evolve16Labs/Droid/Xamarin.Auth/ActivityCustomUrlSchemeInterceptor.cs#L53

NOTE: you can get away with one IntentFilter and Activity, but it is recommended to have more (one for each deep-link/app-link)

**Comment by bastianbecker21** [comment]
@moljac In Android, it doesn't return to app automatically after login successfully done. Can you give me any hint or solution for it?
Thanks.

**Comment by higher-faster-better** [comment]
hi @moljac 
I have same issue. It doesn't back to main app automatically.
Please give me a solution...

Thanks.

**Comment by sylendra7** [comment]
Hi @higher-faster-better  @bastianbecker21 @moljac  for me also not able to return to app automatically after login using the facebook. Can you please tell me any solution

**Comment by abubakrtaha2010** [comment]
@higher-faster-better @bastianbecker21 @sylendra7 
Try this answer to a question on stackoverflow. I think it will solve your problem.
https://stackoverflow.com/questions/47938171/xamarin-auth-google-not-auto-close-when-done-login/51556977#51556977
