### ISSUE TITLE
Facebook NativeUi - how to change user?

### ISSUE THREAD

**Issue by RadoslawKubas** [xamarin/Xamarin.Auth#240]
I'm trying to implement Facebook NativeUI authentication in Xamarin.Forms PCL project for iOS, and have following problem.

I created authenticator  in PCL library like this

```
authenticator = new OAuth2Authenticator(
                    clientId: ClientId,
                    scope: "",
                    authorizeUrl: new Uri("https://m.facebook.com/v2.10/dialog/oauth "),
                    redirectUrl: new Uri($"fb{ClientId}://authorize"),
                    getUsernameAsync: null,
                    isUsingNativeUI: true
                )
                {
                    AllowCancel = true,
                    ShowErrors = false
                };

            authenticator.Completed += OnFacebookAuthCompleted;
            authenticator.Error += OnFacebookAuthError;

            AuthenticationState.Authenticator = authenticator;

            var presenter = new Xamarin.Auth.Presenters.OAuthLoginPresenter();
            presenter.Login(authenticator);
```

It works fine, user can login without any problem with his user and password.

The problem is when user want to login with another Facebook account. Next time login screen looks like that:

![s1](https://user-images.githubusercontent.com/30774825/31774460-1871dc88-b4e6-11e7-8892-98042d112663.png)

It is perfect if user want to use same account, but if want to login with another and click "Cancel" application receive Error message ("OAuth Error = Permissions+error") and browser redirect to new blank page like that:

![s2](https://user-images.githubusercontent.com/30774825/31774705-c68582ca-b4e6-11e7-8bd1-fa28c76c436d.png)

And next time still offer login again to same account. 

The only way to login to another account is to delete app and install it again.

I guess, it is not a bug but some my mistake, but can't find any solution myself. When using Facebook not native or Google native everything works fine, but in this case have no idea what to do.

How can I force app to forget previous account?

And another question, is there a way to close native browser page after unsuccessfully login? When user login successfully the page close itself but in case of error stay on blank page like in this example.

**Comment by higher-faster-better** [comment]
any solution here?

**Comment by DamonWick** [comment]
Radoslaw can you share the complete code on this page

**Comment by Dev-LN** [comment]
You need to implement "sign out" logic in your app too. This is a Facebook requirement too, I think.

Once you have signed out, in your app, the next time you login it will pick up whichever your you have used to login to Facebook App on that phone.

If you want to see both users as a choice in your app, then logout from your app, logout from the Facebook app, then it will show you the different Facebook ids you can use to login to your app.

**Comment by newky2k** [comment]
Sign out needs to be implemented to enable switching users
