### ISSUE TITLE
NativeUi for Instagram works?

### ISSUE THREAD

**Issue by marcelocferdeveloper** [xamarin/Xamarin.Auth#242]
I tried a lot of ways to implement a NativeUi for Instagram but is not working. Redirects me to my redirectpage and nothing works.
If nativeui = false, works perfect.

**Comment by moljac** [comment]
@marcelinhovt 

In order for NativeUi to work deep linking (app linking, or on Windows link activation) must be implemented. For that user must find if it is possible to define on Instagram Oauth portal (where client_id is issued) if it is possible to define custom-scheme urls. NOTE: sometimes it will not be possible.

I haven't tried Instagram with Native UI - yet.

After you find if it is possible we can see how to proceed. Facebook will not let you define `fb{client_id}://authorize` for `redirect_url`, but that custom-scheme url can be found in FB native SDK code for Android and iOS.

Check server side 1st and then we can see next steps.

**Comment by marcelinhovt** [comment]
Thanks my friend. I will give a try soon!

2017-10-27 9:37 GMT-02:00 moljac <notifications@github.com>:

**Comment by newky2k** [comment]
closing as resolved
