### ISSUE TITLE
403 disallowed_useragent error

### ISSUE THREAD

**Issue by Asilee** [xamarin/Xamarin.Auth#245]
I cannot get my Asus Zenfone 2 past the 403 error. I'm not a developer, I'm not developing an app or trying to use an app. I already tried logging in to the settings on the phone, but to no avail, no matter what I do. I cannot get past the initial phone's set up because of it. Some issue with OAuth and "web-view". I just wanted to verify my account, but nothing works. 

I tried googling this situation and it's telling me that I have to learn code, sign up to become a developer, apply that code and then the errors would go away. Suppose this someone who wasn't computer literate, doesn't have a computer, or any means to do said authentication? This phone mind as well stay bricked because that's why I had to factory reset. 

I learned that I had to practically be a developer to get past this error when I pressed on the "LEARN MORE" at the bottom of the error and it took me to a Google Developer page. I just want to use my phone!!!!

**Comment by moljac** [comment]
@asilee 
Seems like settings page of your Asus Zenfone 2 is still using WebView to do OAuth login and you are using google account. WebViews will work with all OAuth service providers, but Google. 

Your problem has nothing to do with this library (Xamarin.Auth).

Try updating your phone maybe settings page was changed in the meantime.

**Comment by moljac** [comment]
Closing this one as not relevant to Xamarin.Auth
