### ISSUE TITLE
Using OAuthLoginPresenter with OAuth1Authenticator on UWP causes Exception

### ISSUE THREAD

**Issue by FlashTek** [xamarin/Xamarin.Auth#246]
# Xamarin.Auth Issue

I am using this code to show a `OAuthLoginPresenter` on Android without any problem. 

    _authenticator = new Xamarin.Auth.OAuth1Authenticator(consumerKey, consumerSecret, requestTokenUrl, authorizeUrl, accessTokenUrl, callbackUrl, null, true);
    _authenticator.ShowErrors = true;

    var presenter = new Xamarin.Auth.Presenters.OAuthLoginPresenter();
    presenter.Login(_authenticator);

When I try to execute the same code on the UWP app, I get this error:

    Unable to cast object of type 'Xamarin.Auth.OAuth1Authenticator' to type 'Xamarin.Auth.OAuth2Authenticator'.

which is probably caused by the `OnNavigate` method inside `WebAuthenticatorPage.xaml.cs`. Is there another way to use the `OAuthLoginPresenter` with `OAuth1` on Android and the UWP? Is this a bug, or am I using the interface in a wrong way?

*IF BUG, INCLUDE THIS PART:*

### Version

- [ ] nuget version = 1.5.0.3

Platform: Universal Windows, Windows 10 Fall Creators Update

Edit: Possibly a duplicate of [this ](https://github.com/xamarin/Xamarin.Auth/issues/236) report?

**Comment by newky2k** [comment]
@FlashTek can you please check this in the latest version please.

**Comment by newky2k** [comment]
no response for over two weeks, closing
