### ISSUE TITLE
ComicBook.Droid 1.5.0 broken

### ISSUE THREAD

**Issue by benczuk** [xamarin/Xamarin.Auth#247]
# Xamarin.Auth Issue

*IF BUG, INCLUDE THIS PART:*

### Version

- [ ] nuget version = 1.5.0.3
- [ ] component version = 1.5.0.3
- [ ] sample ComicBook.Droid

### Steps to reproduce

1. Pull tag 1.5.0 (or commit 1.5.0.3) from git
2. Build and run ComicBook.droid in Visual studio on physical android device
3. Select native UI, Custom renderers, push modal async
4. Press Google auth and complete process
5. Browser is redirected to google.com, custom URL handler does not fire

Platform:

-	[] .NET version = 
-	[] mono version = 

### Expected behaviour

customer url handler triggered, process completes

### Actual behaviour

google.com loaded in browser, break point on custom url activity not hit.

Same behavior is observed in my App

**Comment by benczuk** [comment]
Same issue occurs with Xamarin.Auth.Sample.XamarinAndroid on clicking Google Native UI (pulled from branch master today)

Please let me know if this is a known issue and one you are working on?

**Comment by moljac** [comment]
It is known issue and I'm working on a new set of samples

**Comment by benczuk** [comment]
Any update on this? does it work at all currently with google on Android? If so what is the workaround / fix

**Comment by moljac** [comment]
@benczuk 
Check older versions (June-August).

This is my repo with extracted samples:

https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences

Again, check older versions.

**Comment by benczuk** [comment]
Sorry for the slow reply,

Are you saying it works in a older version or asking me to test them?

I cannot get google auth to redirect to my specified url so the app picks it up at all in any version of the library i have tried

**Comment by newky2k** [comment]
@benczuk  can you check the latest version and see if this is an issue

**Comment by newky2k** [comment]
no response for two weeks,  closing
