### ISSUE TITLE
"Error Authenticating - Invalid grant" when you use the OAuth2Authenticator constructor with access token url parameter

### ISSUE THREAD

**Issue by ataparia** [xamarin/Xamarin.Auth#248]
# Xamarin.Auth Issue

### Version

- [ ] nuget version = 1.5.0.3
- [ ] component version = 
- [ ] sample

### Steps to reproduce

1. Construct OAuth2Authenticator object instance and pass in the AccessTokenUrl parameter. 
Eg. 
 var authenticator = new OAuth2Authenticator(
                                        authServerInfo.ClientId,
                                        null,
                                        authServerInfo.Scope,
                                        new Uri(authServerInfo.AuthorizationServerUrl),
                                        new Uri(authServerInfo.RedirectUrl),
                                        new Uri(authServerInfo.AccessTokenUrl),
                                        null,
                                        true)
                {
                    ShowErrors = false,
                    AllowCancel = false
                };              
2.Subscribe to Completed and Error handlers on the authenticator object.
3.Run the application

Note: Once you authenticate and allow for the access, the code flow always comes to the Error handler with the following error - "Error Authenticating - Invalid grant". However if you construct the OAuth2Authenticator object without the AccessTokenUrl parameter, things work great but the code returns the access token directly instead of the code.

Platform:

-	[] .NET version = 4.5
-	[] mono version = 

### Expected behaviour
No matter how the OAuth2Authenticator object is constructed(with or without the AccessTokenUrl parameter), after successful authentication, "Completed" event should fire.

Tell us what should happen
When OAuth2Authenticator object is constructed with the AccessTokenUrl parameter, Error even handler fires even after successful authentication.

**Comment by ataparia** [comment]
It was observed that after successful authentication, the CustomUrlSchemeInterceptorActivity was initiated on Android and I could see the code(Authorization Code) in the Intent.Data part, but still the code logic fires the Error event handler.

[Activity(Label = "CustomUrlSchemeInterceptorActivity", NoHistory = true, LaunchMode = Android.Content.PM.LaunchMode.SingleTop)]
    [IntentFilter(
        new[] { Intent.ActionView },
        Categories = new[] { Intent.CategoryDefault, Intent.CategoryBrowsable },
        DataScheme = "com.companyname.appname"
        //DataHost = "oidc_callback",
        //DataPath = "?code"    
        )]
    public class CustomUrlSchemeInterceptorActivity : Activity
    {
        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);
            // Convert Android.Net.Url to Uri
            var uri = new Uri(Intent.Data.ToString());                                    
            MainActivity.Authenticator.OnPageLoading(uri);
            
            Finish();            
        }
    }

**Comment by ataparia** [comment]
Here is the stack trace for the error:

  at Xamarin.Auth.OAuth2Authenticator+<RequestAccessTokenAsync>c__async0.MoveNext () [0x0017d] in <347784a7d58c449896f76cefd9e360c2>:0

**Comment by moljac** [comment]
@ataparia 

Which OAuth provider is this? Is this OpenID?

**Comment by ataparia** [comment]
Its a custom provider that has been developed in our company. I think its OAuth2 based provider.

**Comment by ravidixit** [comment]
I have tried using Xamarin.Auth today to get the token for Dropbox app, the OAuth2.0  is working with the POSTMAN and am able to get tokens with postman but am getting the attach error screen when I use Xamarin.Auth passing the exact same parameters what i did for postman

there is no way to set the Grant type field if you are using Xamarin.Auth to get OAuth2.0 access tokens, if there is please let me know

`     var authenticator = new OAuth2Authenticator(
            ClientId, Secret, null,
            new Uri(AuthUrl),
            new Uri(CallBack),
            new Uri(AccessTokenUrl), null, false);`


I am using Xamarin.Auth 1.5.0.3 has anyone made it work with any lower version yet? OR is it just me passing invalid parameters 

![simulator screen shot - iphone 8 - 2018-02-26 at 17 11 53](https://user-images.githubusercontent.com/8243367/36701203-2bf9aff4-1b18-11e8-85da-1bf3d6b1e6ec.png)

**Comment by NakashimaNozomi** [comment]
Does anyone have a solution?  I have same issue...

**Comment by ataparia** [comment]
Hello jjallen,
When I remove the extra slash from the redirect uri, I get an error specially when the android app tries to open up the browser(login page). The error on there says - "400 - Invalid redirect_uri".  Any idea as to how this is working for you and not me?

**Comment by jjallen37** [comment]
@ataparia 
My best guess is on Android is to check these things

1. Valid Redirect URIs listed in keycloak Mine were:
- "http://localhost" - which I verified works with Postman
- "mobile-app-id:/login"
2. Redirect URI passed into the Authenticator object
- Mine was "mobile-app-id:/login"
3. Android InterceptorActivity file that captures the redirect Intention
- Mine looked like this 
![image](https://user-images.githubusercontent.com/2042622/38429376-27aadef4-398c-11e8-8e44-f8d28cc8a46c.png)

**Comment by ataparia** [comment]
@jjallen37 
My redirect uri has to confirm to something like this "mobile-app-id://some_callback".

Also I debugged the source code and it seems like the problem is in OAuth2Authenticator.cs -> RequestAccessTokenAsync method. In this method we are using the following code to exchange the code for access token - HttpResponseMessage response = await client.PostAsync(accessTokenUrl, content).ConfigureAwait(false);
This code seems to be the culprit....If we replace this code with the following code, things are working fine
var request = new HttpRequestMessage(HttpMethod.Post, accessTokenUrl) { Content = content };
HttpResponseMessage response = await client.SendAsync(request).ConfigureAwait(false);
so instead of using client.PostAsync, if we use client.SendAsync....I am no longer facing this issue

**Comment by newky2k** [comment]
This issue is resolved

**Comment by dush88c** [comment]
> Hello jjallen,
> When I remove the extra slash from the redirect uri, I get an error specially when the android app tries to open up the browser(login page). The error on there says - "400 - Invalid redirect_uri". Any idea as to how this is working for you and not me?

You may have to whitelist the redirect_url with OAuth provider.

**Comment by toanxyz** [comment]
> @jjallen37
> My redirect uri has to confirm to something like this "mobile-app-id://some_callback".
> 
> Also I debugged the source code and it seems like the problem is in OAuth2Authenticator.cs -> RequestAccessTokenAsync method. In this method we are using the following code to exchange the code for access token - HttpResponseMessage response = await client.PostAsync(accessTokenUrl, content).ConfigureAwait(false);
> This code seems to be the culprit....If we replace this code with the following code, things are working fine
> var request = new HttpRequestMessage(HttpMethod.Post, accessTokenUrl) { Content = content };
> HttpResponseMessage response = await client.SendAsync(request).ConfigureAwait(false);
> so instead of using client.PostAsync, if we use client.SendAsync....I am no longer facing this issue

I assume that there is no difference between SendAsync and PostAsync, it just a shorter way? Why this solve the issue, I'm curious because we're facing the same issue?

**Comment by ataparia** [comment]
@toanxyz 
To be honest with you, I dont really know. All I know is that replacing PostAsync with SendAsync works for some reason and I found it out the hard way after spending numerous hours on trying to find the actual code.

**Comment by sumitkrmishra** [comment]
Hello, I am getting the same error while I am working on xamarin.ios for Microsoft authentication using Xamarin.Auth.  There is no way to pass grant_type "**grant_type:authorization_code**" . Please help me to solve this issue.
