### ISSUE TITLE
UWP shows blank page in desktop, but works on phone

### ISSUE THREAD

**Issue by Brosten** [xamarin/Xamarin.Auth#250]
- [x ] nuget version = 1.5.0.3

We have our own OAuth2 server/provider.
To use it, we use this code in the UWP LoginPage-renderer
```
            var auth = new OAuth2Authenticator(
               clientId: "Our.ClientId",
               scope: "Our.Scope",
               authorizeUrl: new Uri("https://ourUrl.se/connect/authorize"),
               redirectUrl: new Uri("https://ourUrl.se/loginsuccessful.html")

  Frame rootFrame = Window.Current.Content as Frame;
            rootFrame.Navigate(auth.GetUI(), auth);
```

This works great if used on a Windows Phone (10), but when running it local (on my desktop), I just end up on a blank screen. (Instead of the login screen provided by our Oauth2 server). iOS and Android works like a charm.

Also interesting is that using microsoft settings (https://login.live.com/oauth20_authorize.srf etc...) does work both on Windows phone and Desktop.

So... what differs between our Environment and Microsofts?
- We don't use a ClientSecret or an AccessTokenUrl
- Our oauth-server seems to do some kind of redirection... When given a url like this:
https://ourOauth2Server.se/connect/authorize?client_id=xyz&redirect_uri=xyz&response_type=token&scope=xyz&state=xyz
we become redirected to something like this:
https://ourOauth2Server.se/login?signin=someGuid
- The url created by xamarin auth, for our server has _response_type=token_. Microsoft has _response_type=code_.

Any idéa if the problem is on our oauth2-server or in Xamarin Auth ?

Regards
Andreas Brosten

**Comment by moljac** [comment]
@Brosten 
Hej

> We don't use a ClientSecret or an AccessTokenUrl
> Our oauth-server seems to do some kind of redirection... When given a url like this:
https://ourOauth2Server.se/connect/authorize?client_id=xyz&redirect_uri=xyz&response_type=token&scope=xyz&state=xyz

This looks OK.

> we become redirected to something like this:
https://ourOauth2Server.se/login?signin=someGuid

This might be problem. What happens after login?

> The url created by xamarin auth, for our server has response_type=token. Microsoft has response_type=code.

2 completely different OAuth Grant Types - `response_type=token` is for Implicit AKA Client-Side Flow used in browsers and sometimes devices, while `response_type=code` is for Authorization Code Grant should be used only on servers.
 
Any idéa if the problem is on our oauth2-server or in Xamarin Auth?

Sorry, but not sure (without more info). I suggest - go to community slack channel and ping me there, please.

**Comment by Brosten** [comment]
We found the solution. 
In Package manifest >> Capabilities
Check the "Private Networks (Client and Server)" checkbox

**Comment by Emixam23** [comment]
Hey,

I am probably outta subject but I just wanted to check if Xamarin.Auth has moved forward over UWP and works today. I didn't want to open a thread and it seems you're working with it, so I am asking you :)

Thanks :)

**Comment by Brosten** [comment]
@Emixam23 From what @moljac says, they are currently working on a patch, mainly targeting UWP-issues. Don't know when we can expect it, but hopefully it's not too far away.

**Comment by newky2k** [comment]
@Brosten @Emixam23 could you check to see if this issue still exists please?

**Comment by Emixam23** [comment]
Hey !

To be honest I ain't student no more and I didn't use Xamarin.Auth for a while.. Plus I ain't no more on that project so hard to tell :/

Good luck :)

**Comment by newky2k** [comment]
no longer required
