### ISSUE TITLE
please update the xamarin component store to indicate UWP / windows support

### ISSUE THREAD

**Issue by mdonogma** [xamarin/Xamarin.Auth#251]
if this supports UWP then please ship a working build with UWP to the xamarin component store.

after hours of searching i cam across this repository however xamarin component store outdated.

**Comment by moljac** [comment]
@mdonogma 
Packing component is very complex - samples, docs etc. And I simply did not have time to do it.

And another problem: component store is being sunset... (nice wording) Everything will be on nuget.
We are considering how to solve problems to deploy samples and docs on nuget.

And if this answer is good enough - please close the issue.

Thanks

**Comment by Emixam23** [comment]
Hey @mdonogma 

It works with Xamarin :) I have a Xamarin solution (.NET Core 1.6, Android 7.1, iOS, UWP Build 16299)

- First, take a look at this video -> https://channel9.msdn.com/Shows/XamarinShow/Snack-Pack-15-Upgrading-to-XamarinForms-to-NET-Standard
- Once you're done with it, install `Coudinary.Core` into each project

There is an example of how you can use it:

    public class CloudinarySDK
    {
        private Cloudinary cloudinary { get; set; }

        public CloudinarySDK()
        {

        }

        public void Init()
        {
            Account account = new Account(
                    "my_cloud_name",
                    "my_api_key",
                    "my_api_secret");

            cloudinary = new Cloudinary(account);
        }

        /// <summary>
        /// Upload a file by its path.
        /// </summary>
        /// <returns>The upload end path.</returns>
        /// <param name="path">Path.</param>
        public async Task<string> Upload(string path)
        {
            ImageUploadParams uploadParams = new ImageUploadParams()
            {
                File = new FileDescription(path),
                PublicId = String.Format("{0}.{1}.jpg", User.GetUserInstance().ID, DateTime.Now.ToString("yyyy-MM-dd-HH:mm:ss"))
            };
            ImageUploadResult uploadResult = await cloudinary.UploadAsync(uploadParams);

            return uploadResult.Uri.ToString();
        }

        /// <summary>
        /// Delete the specified url.
        /// </summary>
        /// <returns>The delete.</returns>
        /// <param name="url">URL.</param>
        public void Delete(string url)
        {
            DeletionParams deletionParams = new DeletionParams(url);
            cloudinary.DestroyAsync(deletionParams);
        }
    }

Hope it helps !

**Comment by moljac** [comment]
@Emixam23 Thanks.

`Coudinary.Core` is some wrapper around Xamarin.Auth??

cool

**Comment by Emixam23** [comment]
My bad, I've posted tooo fast so not on the good thread....

**Comment by moljac** [comment]
closing this one - Component store is obsolete

**Comment by Redth** [comment]
To add to this, please use the [NuGet](https://www.nuget.org/packages/Xamarin.Auth/)
