### ISSUE TITLE
Showing  "the user+denied+your+request" Popup on clicking cancel in LinkedIn authentication screen

### ISSUE THREAD

**Issue by georgethms10** [xamarin/Xamarin.Auth#252]
# Xamarin.Auth Issue

Showing "the user+denied+your+request" Popup on clicking cancel in LinkedIn authentication screen

### Version

- [ ] nuget version = 1.5.0.3 IOS
- [ ] nuget version = 1.3.1 ANDROID
### Steps to reproduce

1.Click the liked in login button 
2.In the linkedIn authentication page click cancel
3.An error message is shown "the user+denied+your+request"

Platform:
-   Android and IOS both this error message is shown
-	[] .NET version = 
-	[] mono version = 5.4.1

### Expected behaviour
The error message has no meaning. No need of that error message
Tell us what should happen
The error message has no meaning. No need of that error message. It should simply go back to the application with showing error message.
### Actual behaviour
Its shows error message  **"the user+denied+your+request"** and the cancel callback is hit two times
Tell us what happens instead
Can you also include a screen shot?
<img width="400" alt="screen shot 2017-12-06 at 12 57 11 pm" src="https://user-images.githubusercontent.com/6296111/33649904-c6c814ae-da85-11e7-8169-c17d6becdfa2.png">

**Comment by moljac** [comment]
@georgethms10 

Why:

> nuget version = 1.3.1 ANDROID

and

> nuget version = 1.5.0.3 IOS

????

Two nuget versions?

**Comment by moljac** [comment]
What are you doing with this app?

This is not OAuth error, but error from LinkedIn that user rejected some request (LinkedIn connect or similar).

**Comment by georgethms10** [comment]
Both nuget version(1.3.1 and 1.5.0.3) have this issue!! 

Is there any way that we could actually stop showing this message. 

i initialise authrequest only once but when hitting cancel in the linked in page, i get two callbacks inside Oncancel callback

`auth2Request = new OAuth2Authenticator(
					clientId: Api.clientIdLinkedin, 
					clientSecret: Api.clientSecretLinkedin, 
					scope: Api.scopeLinkedin,
					authorizeUrl: new Uri(authorizeUrlLinkedin),
					redirectUrl: new Uri(redirectUrlLinkedin),
					accessTokenUrl: new Uri(accessTokenUrlLinkedin));`

`auth2Request.Error += Cancel;`
`void Cancel(object sender, AuthenticatorErrorEventArgs e)
		{
		       //Hit twice and the "user+denied" message shown 
			auth2Request.OnCancelled();
		}`

Can we somehow disable or stop showing this denied popup.

**Comment by shivaprakashab** [comment]
@georgethms10 Did you find a solution for this issue ?

**Comment by georgethms10** [comment]
@shivaprakashab Nope

**Comment by Naveenkavin** [comment]
I have the same issue...Is there any Solution for this Problem???....Once You guys are find a Solution ....please tell me!

**Comment by SirLanceLang** [comment]
Have you tried:
OAuth2Authenticator.ShowErrors = false;

**Comment by newky2k** [comment]
@@georgethms10  can you try this on the latest version please

**Comment by newky2k** [comment]
no response for over two weeks, closing
