### ISSUE TITLE
Be able to add settings on the Android Web view

### ISSUE THREAD

**Issue by mathieumack** [xamarin/Xamarin.Auth#253]
# Xamarin.Auth Issue

### Feature description

When we used the Xamarin.Android assembly for our application we have some errors on the page rendering Inside the webview.
Our OAuth provider says that we need to update the webView object settings to add these lines :
webView.getSettings().setUseWideViewPort(true);
webView.getSettings().setLoadWithOverviewMode(true);
(Java version of the code sample).

How can I change these settings of the WebView in order to manage this specific Oauth provider constraints ?

Is it possible to change the webView property in the WebAuthenticatorActivity partial class to a public field (line 40 https://github.com/xamarin/Xamarin.Auth/blob/master/source/Core/Xamarin.Auth.XamarinAndroid/PlatformSpecific/WebAuthenticatorActivity.cs) ?
By the Intent sended when I call the GetUI() method, I will be able to cast the object as WebAuthenticatorActivity object, and change the webView settings.

Thanks for your help.

**Comment by moljac** [comment]
@mathieumack

> in order to manage this specific Oauth provider constraints ?

Are you aware how much "specific OAuth providers" are there? Are all of them according to RFC? Not malicious?

This request seems like reasonable one, but it implies maintenance etc...

Security implies a bit restrictions. It is possible to expose everything, but if that makes sense is another question.

Let us discuss it and we ll get back

**Comment by mathieumack** [comment]
Hi, thank you for your answer.
I understand that you can't valid all requests ;)

My Customer used actually an idenitity solution based on Ping Identity (https://www.pingidentity.com/en.html).

But when I used the Xamarin.Auth plugin to allow users to logon, the webpage showed in the WebView is not responsive on tablets. After long discussions with the dev team that manage the Authentification Platform, they can only just propose us to change the webView settings.

So my only available solution yet is to fork this repository, and allow to change the webView settings.
If you will be able to set the webView as public it will be perfect. But I understand that there are many impacts.

Best regards

**Comment by mathieumack** [comment]
Hi !
I have forked the project, try to change the webview settings, but I have the same problem.
After some more research, I've found a user that has the same problem with the Xamarin.Auth plugin:
https://stackoverflow.com/questions/29334279/xamarin-android-javascript-not-loading-in-webview-when-using-xamarin-auth
As this user, my problem appears on a Samsung Galaxy S3.
Do you know if this device has some limitations, and can you try your plugin on this device ?
Best regards

**Comment by mathieumack** [comment]
Hi !
After many  fork and rebuild, I've found a solution to my problem !
At the origin, when the Webclient shows the webpage, the content was not adapted to mobile devices with high dpi.
The solution was to update the mininum sdk version used to package my application from Level 15 to Level 19.
With this fix, the page login is showed correctly ! Without Adding javascript options.
