### ISSUE TITLE
ClearCookiesBeforeLogin doesn't seem to work on UWP

### ISSUE THREAD

**Issue by Brosten** [xamarin/Xamarin.Auth#254]
- [x ] nuget version = 1.5.0.3
- [ ] component version = 2.5.x

....
auth.ClearCookiesBeforeLogin = true;
var presenter = new Xamarin.Auth.Presenters.OAuthLoginPresenter();
presenter.Login(auth);
....

The second time I call presenter.Login() on UWP, I get redirected to the "Successful login" page (redirectUrl). This does NOT happen och Android or iOS. 
I guess the correct behaviour when ClearCookiesBeforeLogin =true is to show the auth-login page, without any knowledge of prior sessions?

**Comment by moljac** [comment]
@Brosten 
NativeUI?

**Comment by Brosten** [comment]
No (not native ui). Or... I'm not specifying the flag, so i think it defaults to false. Hasn't really understood the nativeui-option...

**Comment by moljac** [comment]
@Brosten 

UWP - embedded browser (WebView, Control) was quite new in April-June and I didn't test it thoroughly, so most likely bug. 

NativeUI is switched on with boolean flag. On Android and iOS you cannot influence cookies, cache of external/system browser. I'm sure this is true for Windows platforms too.

**Comment by ahmad-raza** [comment]
Its not working for iOS and android either. Any fix?

**Comment by newky2k** [comment]
@Brosten  can you please try this with the latest version please.

**Comment by newky2k** [comment]
no repsonse for over two weeks, closing
