### ISSUE TITLE
Is refreshing the page available in the api?

### ISSUE THREAD

**Issue by SuhanKoh** [xamarin/Xamarin.Auth#255]
Hello, just wondering if there is something in the code that let me refresh the screen? or go back to the first page?

**Comment by moljac** [comment]
@SuhanKoh 
Sorry I'm confused? Which screen? 1st page? I need more context...

**Comment by SuhanKoh** [comment]
Sorry, what I meant to say was, if I display an oauth page for the user to login, and there might be some buttons on the page that lead the user to another html page, hence I am asking if there is a way to control in the API that let me add a button to go back to the login page or even let the user perform back button?

**Comment by moljac** [comment]
@SuhanKoh 

> if I display an oauth page for the user to login, and there might be some buttons on the page that lead the user to another html page, hence I am asking if there is a way to control in the API that let me add a button to go back to the login page or even let the user perform back button?

In non-NativeUI version maybe with some HTML/js injection in the loaded page (so HACK), but I NativeUI - I'm pretty sure you can do nothing/nada/zilch/nichts...

In embedded browser version there might be added API for something like that, but that will be very low on the list of stuff that must be done for Xamarin.Auth.

**Comment by newky2k** [comment]
not possible
