### ISSUE TITLE
safari cannot open the page because the address is invalid in ios

### ISSUE THREAD

**Issue by nmano2188** [xamarin/Xamarin.Auth#257]
Works perfectly in Android. But for iOS, after selecting account, i got the following error.
"safari cannot open the page because the address is invalid"

I'm using device to test app.
Any work around?

**Comment by nmano2188** [comment]
I fixed now. Thanks

**Comment by mpapadis** [comment]
@nmano2188 How did you fix it? I have the same problem.

**Comment by manonaga2188** [comment]
Follow this

![ios xamarin auth](https://user-images.githubusercontent.com/35101045/36474952-34288bca-171f-11e8-9e77-92b0c31575cd.png)
