### ISSUE TITLE
Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.

### ISSUE THREAD

**Issue by Emixam23** [xamarin/Xamarin.Auth#258]
# Xamarin.Auth Issue

### Version

- [ ] nuget version = 1.5.0.3
- [ ] component version = 26.0.1.0
- [ ] xamarin forms version = 2.5.0.121934
- .NET Core 2.0 & Android 8

### Steps to reproduce

1. Update Xamarin.Forms, Xamarin.Android.*, Xamarin.auth to the versions above
2. create a Auth client with **isUsingNativeUI = true**

        // An example of code
        public OAuth2Authenticator Authenticator(Action<User> onCompleted, Action<string> onError)
        {
            OAuth2Authenticator authenticator = new OAuth2Authenticator(
                clientId,
                clientSecret,
                Scope,
                new Uri(AuthorizeUrl),
                new Uri(redirectUri),
                new Uri(AccessTokenUrl),
                null,
                isUsingNativeUI)
            {
                AllowCancel = true,
                ShowErrors = false
            };

            authenticator.Completed += OnAuthCompleted;
            authenticator.Error += OnAuthError;

            OnCompleted = onCompleted;
            OnError = onError;

            return authenticator;
        }

3. Build & Deploy

> System.MissingMethodException
> Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.

**Comment by moljac** [comment]
Xamarin.Android.Support version?

**Comment by Emixam23** [comment]
Component version 26.0.1.0

**Comment by moljac** [comment]
Can you try to turn of linking?

**Comment by Emixam23** [comment]
I already did that :/

**Comment by cbfrank** [comment]
@Emixam23 I get this error also, and my solution is to add the pacakge Xamarin.Android.Support.CustomTabs to your android project.
After added this pacakge, I got lots of compiler error as below:
Error		error: cannot find symbol
	extends android.support.customtabs.CustomTabsCallback
  symbol:   class CustomTabsCallback
  location: package android.support.customtabs
The solution for the compiler error is clearn your solution and then rebuild it again.

It's strange that Xamarin.Auth with NativeUI support depends on Xamarin.Android.Support.CustomTabs but adding Xamarin.Auth doesn't add Xamarin.Android.Support.CustomTabs automatically.
Xamarin document https://developer.xamarin.com/guides/xamarin-forms/cloud-services/authentication/oauth/ only mentationed it depends on custome tabs but should also mentation to add this pacakge

**Comment by ahoefling** [comment]
I've ran into this problem before, and I just need to add the correct version of Xamarin.Android.Support.CustomTabs like @cbfrank  mentioned.

**Comment by moljac** [comment]
@cbfrank 

> but adding Xamarin.Auth doesn't add Xamarin.Android.Support.CustomTabs automatically.

Sorry, but not true.
See nuspec (nuget dependency definitions):

https://github.com/xamarin/Xamarin.Auth/blob/master/nuget/Xamarin.Auth.nuspec#L91-L99

OK. This complex dependency (for multiple targets) is recent addition, but if you check history CustomTabs nuget dependency is in nuspec since early days (2107-06 v.1.5.0.0)

There are other causes which could cause this error (nuget restore failed, or collision with some other dependencies).

The only manual thing that usually must be done is updating Xamarin.Android.Support packages. Why because CustomTabs is pinned to 23.0.0 because Xamarin.Forms are pinned to that version of Support packages (check nuspec for Xamarin.Forms.*)

**Comment by dgerding** [comment]
I seem to remember that you should remove all of the xamarin.android.support nugets.  Naturally make a list of the ones you have in your project first :-) once you've done that you should put in the version 23 nougats for Xamarin.Android. And then you are able to install Xamarin. Auth 1.6 against it, including .Net standard projects. You may even be able to roll the xamarin support packages forward after having installed xamarin.auth installed.  I seem to remember that is possible, too. But I haven't had to move my support nougats forward yet as I'm working on other things. Hope this helps.

**Comment by newky2k** [comment]
just a project issue with dependencies
