### ISSUE TITLE
Xamairn.Auth causing System.IO.FileNotFoundException when trying to build

### ISSUE THREAD

**Issue by MobileRez** [xamarin/Xamarin.Auth#259]
# Xamarin.Auth Issue

When building with a .net standard 2.0 project app errors with:
		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Xamarin.Auth, Version=1.3.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Xamarin.Auth.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters) in /Users/builder/data/lanes/5749/ef47226b/source/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:line 229
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	LvlUpHealth.Android			

yes its installed on all platforms. 

 manually adding missing references to project cleaning, deleting obj and bin folders and rebuilding does not solve the issue

*IF BUG, INCLUDE THIS PART:*

### Version

- [ ] nuget version = 4.5.0
- [ ] component version = 1.5.0.3 
- [ ] sample

### Steps to reproduce

1. make new .net standard 2.0 project
2. add Xamarin.Auth.XamarinForms to project
3. attempt to build

Platform:

-	[] .NET version = 4.7.02556
-	[] Xamairn version = 4.8.0.757 (7f9ec2a)

### Expected behaviour

app should build with out errors. 

### Actual behaviour

app errors and refuses to build. installing nuget packages manually does not work

*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by Emixam23** [comment]
Hey !

I already had this error however, I am not sure to remember how to correct it. Just try to update your Xamarin.Android.* nugets and/or update your Android SDK :)

Hope it helps !

**Comment by MobileRez** [comment]
Thanks Emixam23, I already tried that and i am using the latest of everything. even manually added the chrome custom tabs to try and fix it.

**Comment by Emixam23** [comment]
Alright :) I have a last idea, what is your version of Android SDK? Try to put 8, I say tht because you aren't talking about it so I don't know if you're using the 7 or the 8

**Comment by MobileRez** [comment]
I am using 8 I tried 7 and 8 for Android version and that didn't help. I
get errors with iOS as well, though those are different errors but I
appreciate the help.  I also get intermittent errors with pclcrypto and
microsoft.bcl.build but pclcrypto gives me a warning triangle when I
manually install it and it still doesn't fix the pclcrypto error

**Comment by bmolinab** [comment]
Test installing the other nugets dependencies
**PCLCrypto
PInvoke.NCrypt
Validation**

it worked for me

**Comment by MobileRez** [comment]
those install fine, its the Xamarin.Auth nuget that gives me the build
errors.

Mitch Muenster
Microsoft MVP, Xamarin Certified Developer, Autistic, AR & VR Enthusiast,
Biohacker, & Public Speaker
Twitter: @MobileRez <https://twitter.com/mobilerez>
mitchmuenster.com
Microsoft MVP Profile
<https://mvp.microsoft.com/en-us/PublicProfile/5002013?fullName=Mitch%20%20Muenster>

**Comment by MobileRez** [comment]
I also tried installing those first thinking there was issues pulling in
dependencies.

Mitch Muenster
Microsoft MVP, Xamarin Certified Developer, Autistic, AR & VR Enthusiast,
Biohacker, & Public Speaker
Twitter: @MobileRez <https://twitter.com/mobilerez>
mitchmuenster.com
Microsoft MVP Profile
<https://mvp.microsoft.com/en-us/PublicProfile/5002013?fullName=Mitch%20%20Muenster>

**Comment by MobileRez** [comment]
Exception while loading assemblies: System.IO.FileNotFoundException: Could
not load assembly 'Xamarin.Auth, Version=1.5.0.0, Culture=neutral,
PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Xamarin.Auth.dll'
   at
Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference
reference, ReaderParameters parameters) in
/Users/builder/data/lanes/5749/ef47226b/source/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:line
229
   at
Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver
resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean
topLevel)
   at
Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver
resolver) MJEMobile.Android


Mitch Muenster
Microsoft MVP, Xamarin Certified Developer, Autistic, AR & VR Enthusiast,
Biohacker, & Public Speaker
Twitter: @MobileRez <https://twitter.com/mobilerez>
mitchmuenster.com
Microsoft MVP Profile
<https://mvp.microsoft.com/en-us/PublicProfile/5002013?fullName=Mitch%20%20Muenster>

**Comment by bmolinab** [comment]
I install the nugets in the whole solution in the three projects
[<a href="https://imgbb.com/"><img src="https://image.ibb.co/ckMybm/nugets.png" alt="nugets" border="0" /></a>](url)

**Comment by MobileRez** [comment]
yes If i have both the xamarin auth and xamarin.auth.forms it says I have
duplicate instances of Xamarin.Auth. so I have to uninstall one of them.
just using Xamarin.Auth does build however.

Mitch Muenster
Microsoft MVP, Xamarin Certified Developer, Autistic, AR & VR Enthusiast,
Biohacker, & Public Speaker
Twitter: @MobileRez <https://twitter.com/mobilerez>
mitchmuenster.com
Microsoft MVP Profile
<https://mvp.microsoft.com/en-us/PublicProfile/5002013?fullName=Mitch%20%20Muenster>

**Comment by MobileRez** [comment]
likewise im glad you all are able to get it installed but this packages
behavior is so inconsistent... each time i think i fix it a different or
new error pops up. and its only happening with this package.

Mitch Muenster
Microsoft MVP, Xamarin Certified Developer, Autistic, AR & VR Enthusiast,
Biohacker, & Public Speaker
Twitter: @MobileRez <https://twitter.com/mobilerez>
mitchmuenster.com
Microsoft MVP Profile
<https://mvp.microsoft.com/en-us/PublicProfile/5002013?fullName=Mitch%20%20Muenster>

**Comment by MobileRez** [comment]
okay after a ton of attempts its building and loading but now all the calls
are returning net::err_Connection_Refused with the comic book sample... and
cant find where to set up intents to fix it... *sigh*

Mitch Muenster
Microsoft MVP, Xamarin Certified Developer, Autistic, AR & VR Enthusiast,
Biohacker, & Public Speaker
Twitter: @MobileRez <https://twitter.com/mobilerez>
mitchmuenster.com
Microsoft MVP Profile
<https://mvp.microsoft.com/en-us/PublicProfile/5002013?fullName=Mitch%20%20Muenster>

**Comment by EmilAlipiev** [comment]
i have the same error. how did you fix it?

**Comment by EmilAlipiev** [comment]
I found out that if you are installing xamarin.auth.xamarinforms package, it doesnt install xamarin.auth dependency automatically on android project.

**Comment by newky2k** [comment]
@MobileRez can you try this with the latest version of Xamarin.Auth, 1.6.0.2.  xamarin.auth.xamarinforms definately has a dependecy on Xamarin.Auth now

**Comment by newky2k** [comment]
no response for over two weeks, closing
