### ISSUE TITLE
Google Auth doesn't fire redirect handler

### ISSUE THREAD

**Issue by benczuk** [xamarin/Xamarin.Auth#262]
Xamarin forms app Android version, xamarin.auth 1.5.0.3
Android 8.1.0

In my app the custom URL handler is never called. Once I have authenticated with google using native UI the webpage redirects to google.com and my redirect handler never fires (break point not hit).

The same code is in use on iOS and works perfectly there.

The same behavour is evident in ComicBook.droid on android

Is Google Auth using native UI on Android broken in Xamarin.auth?

**Comment by VadyaVL** [comment]
Hello. If you have a package: **Project.Android**
I recommend trying to replace it with **project.android** (or **com.company.project**) (_use lower case letters_).
It helped me.

**Comment by benczuk** [comment]
Thanks for the suggestion, but my package is already lowercase

**Comment by moljac** [comment]
@benczuk Please go to the slack community channel and ping me there.

Namely I'll need to see your constructor and IntentFilter and those are sensitive data, so we'll switch to private chat.

**Comment by newky2k** [comment]
taken off github
