### ISSUE TITLE
Feature Request: Xamarin Forms OKTA Sample

### ISSUE THREAD

**Issue by AllenFoster** [xamarin/Xamarin.Auth#265]
I have tried to use Xamarin.Auth in an cross platform Xamarin Forms (specifically iOS) app along with my developer account at OKTA but am observing an NullReferenceException when executing the following line of code in the PCL project:
presenter.Login(authenticator);
It would be great to see a working example. I have noticed a variety of forums where users of Xamarin.Auth have observed the same issue.
Thanks!

**Comment by moljac** [comment]
Did you initialize Presenters?

https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences/blob/master/Xamarin.Forms/Evolve16Labs/Droid/MainActivity.cs#L25

https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences/blob/master/Xamarin.Forms/Evolve16Labs/iOS/AppDelegate.cs#L21

etc...

**Comment by AllenFoster** [comment]
Thanks! My bad for missing that step.
No longer getting the NullReferenceException, however now I'm getting the following response from OKTA when executing the presenter.Login code:
errorCode: E0000022, The endpoint does not support the provided HTTP method. 
I think I properly specified the authentication, redirect and token URL and specified the correct URL scheme in the info.plist, e.g. com.oktapreview.dev-xxxxxx

**Comment by moljac** [comment]
@AllenFoster 

Hi Allen

> No longer getting the NullReferenceException, 

Glad to hear that.

>however now I'm getting the following response from OKTA when executing the presenter.Login code:

There must be something service provider specific (settings on the server side) that Xamarin.Auth cannot handle by default or at all.

> errorCode: E0000022, The endpoint does not support the provided HTTP method.

No idea. Never worked with OKTA. I can put it on very long list of OAuth providers that need samples and docs, but there is nothing related to OKTA right now. 

How fast do you need it? I hope it is not "yesterday"...

> I think I properly specified the authentication, redirect and token URL and specified the correct URL scheme in the info.plist, e.g. com.oktapreview.dev-xxxxxx

For that. I would suggest you to go to Xamarin Community Slack channel and there we can open private chat for all sensitive/private data. Rest should go into #xamarin-auth-social channel so other people can benefit from out discussion.

**Comment by galadril** [comment]
Did you got Okta login with PKCE working with Xamarin.Auth?

**Comment by Redth** [comment]
Closing due to no new information.  Please open a new issue if you have more information.
