### ISSUE TITLE
UWP app fails to start because of 'Entry Point Not Found' exception

### ISSUE THREAD

**Issue by FrankChen021** [xamarin/Xamarin.Auth#267]
# Xamarin.Auth Issue

release version of a UWP app fails to start, and an exception dialog shows as 
![image](https://user-images.githubusercontent.com/6525742/36632885-2d5611e6-19c7-11e8-98d1-7f46f521e2d1.png)
but debug version works well

### Version

- [ ] Xamarin.Auth = 1.5.0.3
- [ ] Microsoft.NETCore.UniversalWindowsPlatform = 6.0.1

### Steps to reproduce

1. create a blank Cross-Platform app (Xamarin.Forms)
2. add Xamarin.Auth to **UWP project, not the shared project** 
3. build the release version(no need to add/modify/delete any codes)
4. launch the app, it fails

Platform:

-	[] Windows version = 17074.rs_prerelease_flt.180116-1539
-	[] .NET version = netstandard 2.0
-	[] Visual Studio = Visual Studio Enterprise 2017 15.5.7

### Expected behaviour

release version of UWP app can start

### Actual behaviour

if we start the release version in Visual Studio with F5, the output windows shows some logs as below

> The thread 0x3328 has exited with code -1073741511 (0xc0000139).
> The thread 0x1314 has exited with code -1073741511 (0xc0000139).
> The thread 0x711c has exited with code -1073741511 (0xc0000139).
> The thread 0x6fbc has exited with code -1073741511 (0xc0000139).
> The program '[27996] UWPEntryNotFound.UWP.exe' has exited with code -1073741511 (0xc0000139) 'Entry Point Not Found'.
> Activation of the Windows Store app 'ec0cc741-fd3e-485c-81be-68815c480690_hma5z8g0e8z20!App' failed with error '应用未启动'.

### Some Findings

1. this problem is related to .NET Native

'`Compile with .NET Native tool chain`' option is checked by default for release configuration, and if we **uncheck this option, the release version app can starts**.

![image](https://user-images.githubusercontent.com/6525742/36632825-8b5a140a-19c6-11e8-8764-77303e495643.png)

but windows 10 app store requires app built with this option, so I can't uncheck this option to publish an app.

2.  this problem is related to Windows 16299

I checked the sample UWP app project in Xamarin.Auth.Samples.NugetReferences , its release version works well.  it works well because:

1. its minimum targeting version is **Windows 10 Build 10586**, while my project is **16299**
![targeting](https://user-images.githubusercontent.com/6525742/36632952-2875709e-19c8-11e8-87f6-40f60a0897bd.png)

(btw, actually the targeting version of the sample project is 14393, but there's no sdk of 14393 on my computer, so I retarget it to 16299)

2. it depends on Microsoft.NETCore.UniversalWindowsPlatform **5.2.2** while my project depends on that of version **6.0.1**

3. reference to Xamarin.Auth is in the shared project while the reference to Xamarin.Auth in my project is in the UWP project

if we change the all 3 settings in the sample project as same as the settings in my project, the sample project also fails to start.

**Comment by lindexi** [comment]
我也遇到这个问题，暂时只能取消

**Comment by newky2k** [comment]
@FrankChen021 @lindexi  Can you please check this issue with the latest version 1.6.0.2

**Comment by newky2k** [comment]
no reponse for over two weeks, closing
