### ISSUE TITLE
.NET Standard 2.0 compatibility issue

### ISSUE THREAD

**Issue by stesvis** [xamarin/Xamarin.Auth#268]
# Xamarin.Auth Issue

> Package 'Xamarin.Auth 1.5.0.3' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

### Version

- [ ] nuget version = 1.5.0.3

### Steps to reproduce

1. Create a new Xamarin Forms project using .NET Standard 2.0
2. Install Xamarin.Auth
3. Build the solution

Platform:

-	[] .NET version = .NET Standard 2.0

### Expected behaviour

Build without warnings/errors

### Actual behaviour

I Get the following warning:

> Package 'Xamarin.Auth 1.5.0.3' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

and i also started getting this build error:

> Could not locate R:\...\my app path\...\packages.config.  Ensure that this project has Microsoft.Bcl.Build installed and packages.config is located next to the project file.

And other similar warnings that started showing after installing the package (see attachment).

![image](https://user-images.githubusercontent.com/6062684/36769924-9142c0ac-1c04-11e8-8eb7-9fa5be6c8ab4.png)

**Comment by moljac** [comment]
Xamarin.Auth 1.5.0.x does not support .NET Standard projects.

Try 1.6.0-alpha* and please report here. 

Leaving this issue opened just for the discussion, closing it very soon (after 1.6.0 release)

**Comment by stesvis** [comment]
Hi, thanks.
I installed 1.6.0-alpha4 and it eems all good to go, thank you.

**Comment by stesvis** [comment]
The -alpha5 could not install on the android project because of other dependencies.

**Comment by moljac** [comment]
@stesvis 
Can you give me more info (error maybe) 

> The -alpha5 could not install on the android project because of other dependencies.

thanks

**Comment by stesvis** [comment]
Sure @moljac , here is what I get:

> Install-Package Xamarin.Auth -Version 1.6.0-alpha05
>   GET https://api.nuget.org/v3/registration3-gz-semver2/xamarin.auth/index.json
>   GET https://dotnet.myget.org/F/aspnetcore-dev/Packages(Id='Xamarin.Auth',Version='1.6.0-alpha05')
>   NotFound https://dotnet.myget.org/F/aspnetcore-dev/Packages(Id='Xamarin.Auth',Version='1.6.0-alpha05') 282ms
>   GET https://dotnet.myget.org/F/aspnetcore-dev/FindPackagesById()?id='Xamarin.Auth'&semVerLevel=2.0.0
>   OK https://dotnet.myget.org/F/aspnetcore-dev/FindPackagesById()?id='Xamarin.Auth'&semVerLevel=2.0.0 62ms
>   OK https://api.nuget.org/v3/registration3-gz-semver2/xamarin.auth/index.json 381ms
> Restoring packages for R:\VeloGuide\VeloGuideApp\VeloGuideApp\VeloGuideApp.Android\VeloGuideApp.Android.csproj...
> Install-Package : Version conflict detected for Xamarin.Android.Support.Compat. Reference the package directly from the project to resolve this issue. 
>  VeloGuideApp.Android -> Xamarin.Android.Support.v7.MediaRouter 26.1.0.1 -> Xamarin.Android.Support.v7.Palette 26.1.0.1 -> Xamarin.Android.Support.Compat (= 26.1.0.1) 
>  VeloGuideApp.Android -> Xamarin.Auth 1.6.0-alpha05 -> Xamarin.Android.Support.CustomTabs 25.4.0.2 -> Xamarin.Android.Support.Compat (= 25.4.0.2).
> At line:1 char:1
> + Install-Package Xamarin.Auth -Version 1.6.0-alpha05
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : Package restore failed. Rolling back package changes for 'VeloGuideApp.Android'.
> At line:1 char:1
> + Install-Package Xamarin.Auth -Version 1.6.0-alpha05
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by moljac** [comment]
@stesvis 
Before installing Xamarin.Auth try lowering versions of your Xamarin.Android.Support.* packages to version 25.4.0.2. Add Xamarin.Auth and then you can bump/update everything.

Xamarin.Auth pins Android.Support versions like Xamarin.Forms.

**Comment by stesvis** [comment]
Thanks,
another issue is that with Xamarin.Auth installed, I can't build in Release mode:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		The "LinkAssemblies" task failed unexpectedly.
> Mono.Linker.MarkException: Error processing method: 'System.Void Android.Support.CustomTabs.Chromium.SharedUtilities.CustomTabActivityHelper::LaunchUrlWithCustomTabsOrFallback(Android.App.Activity,Android.Support.CustomTabs.CustomTabsIntent,System.String,Android.Net.Uri,Android.Support.CustomTabs.Chromium.SharedUtilities.ICustomTabFallback)' in assembly: 'Xamarin.Auth.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Android.Support.CustomTabs.CustomTabsIntent::LaunchUrl(Android.Content.Context,Android.Net.Uri)
>    at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
>    at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
>    at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
>    at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
>    at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
>    at Mono.Linker.Steps.MarkStep.ProcessQueue()
>    --- End of inner exception stack trace ---
>    at Mono.Linker.Steps.MarkStep.ProcessQueue()
>    at Mono.Linker.Steps.MarkStep.ProcessEntireQueue()
>    at Mono.Linker.Steps.MarkStep.Process()
>    at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
>    at Mono.Linker.Pipeline.Process(LinkContext context)
>    at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
>    at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
>    at Xamarin.Android.Tasks.LinkAssemblies.Execute()
>    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
>    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	VeloGuideApp.Android

Unless I set the Linking to None

**Comment by raphaelsilvasage** [comment]
I'm with the same problem: 

 Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1107	Version conflict detected for Xamarin.Android.Support.Compat. Reference the package directly from the project to resolve this issue. 
 MobileCommonTest.Android -> Xamarin.Android.Support.v7.MediaRouter 27.0.2 -> Xamarin.Android.Support.v7.Palette 27.0.2 -> Xamarin.Android.Support.Compat (= 27.0.2) 

 MobileCommonTest.Android -> MobileCommonTest -> Sage.br.MobileCommon.Seguranca.Forms 1002.0.0 -> Xamarin.Auth 1.6.0 -> Xamarin.Android.Support.CustomTabs 25.4.0.2 -> Xamarin.Android.Support.Compat (= 25.4.0.2).				

When will Xamarin.Auth support Xamarin.Android.Support.Compat (= 27.0.2) ?

**Comment by moljac** [comment]
@raphaelsilvasage First downgrade to install, then upgrade.

https://github.com/xamarin/Xamarin.Auth/issues/268#issuecomment-369935963

> When will Xamarin.Auth support Xamarin.Android.Support.Compat (= 27.0.2) ?

I see no reasons, why it wouldn't support. Do Xamarin.Forms support 27.0.2? I think so. Xamarin.Auth nuspec is mirror (copy/paste) of Xamarin.Forms nuspec. This is so since Xamarin.Forms support was added, it was impossible to go on own route.

**Comment by moljac** [comment]
Closing issue.

**Comment by felixcen** [comment]
Hi, Can you please elaborate "First downgrade to install, then upgrade."?

what should I downgrade and then upgrade?

**Comment by felixcen** [comment]
I will answer my own question, we just need to install the nuget package on the *.Android.csproj


Install-Package Xamarin.Android.Support.CustomTabs -Version 27.0.2.1
