### ISSUE TITLE
Java.Security.KeyStoreException: KeyStore was not initialized

### ISSUE THREAD

**Issue by mjfara** [xamarin/Xamarin.Auth#271]
Not sure what happened with my project, but now whenever I try the following:

AccountStore.Create().Save(account, providerName);

I get the following error:
Java.Security.KeyStoreException: KeyStore was not initialized

I'm doing this from a PCL, Xamarin.Forms project.

**Comment by TamasRusvai** [comment]
Maybe Duplicated #223. Please add more information to the description.

**Comment by newky2k** [comment]
this is fixed in 1.6.02

**Comment by ignasbagdonas** [comment]
No, it doesn't. I have 1.6.0.4 and still this error occur for some users.
