### ISSUE TITLE
Dependency Issues on creating new android project

### ISSUE THREAD

**Issue by GMaddison** [xamarin/Xamarin.Auth#274]
# Xamarin.Auth Issue

On Creation of a new project Specifically for android platform

### Version

- [ ] nuget version = 4.5.1.4870
- [ ] component version = 1.6.0.1

### Steps to reproduce

1. Create a Blank Xamarin Forms Application as Shared Project
2. Add Xamarin.Auth 1.6.0.1 And Xamarin.Android.Support.CustomTabs v25.4.0.2 just to Android project
3. Build Project

Platform:
-	[] .NET version = 4.0
-	[] mono version = 8.1

### Expected behaviour

Project Should compile without errors.

### Actual behaviour

1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Attribute.font. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Attribute.fontProviderAuthority. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Attribute.fontProviderCerts. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Attribute.fontProviderFetchStrategy. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Attribute.fontProviderFetchTimeout. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Attribute.fontProviderPackage. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Attribute.fontProviderQuery. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Attribute.fontStyle. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Attribute.fontWeight. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Dimension.compat_button_inset_horizontal_material. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Dimension.compat_button_inset_vertical_material. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Dimension.compat_button_padding_horizontal_material. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Dimension.compat_button_padding_vertical_material. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Dimension.compat_control_corner_material. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Id.async. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Id.blocking. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Id.forever. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Id.italic. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.String.library_name. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Style.TextAppearance_Compat_Notification. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Style.TextAppearance_Compat_Notification_Info. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Style.TextAppearance_Compat_Notification_Info_Media. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2_Media. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Style.TextAppearance_Compat_Notification_Media. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Style.TextAppearance_Compat_Notification_Time. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Style.TextAppearance_Compat_Notification_Time_Media. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Style.TextAppearance_Compat_Notification_Title. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Style.TextAppearance_Compat_Notification_Title_Media. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Style.Widget_Compat_NotificationActionContainer. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Style.Widget_Compat_NotificationActionText. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Styleable.FontFamily. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Styleable.FontFamily_fontProviderAuthority. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Styleable.FontFamily_fontProviderCerts. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Styleable.FontFamily_fontProviderFetchStrategy. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Styleable.FontFamily_fontProviderFetchTimeout. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Styleable.FontFamily_fontProviderPackage. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Styleable.FontFamily_fontProviderQuery. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Styleable.FontFamilyFont. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Styleable.FontFamilyFont_font. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Styleable.FontFamilyFont_fontStyle. Please check that your Nuget Package versions are compatible.
1>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1392,2): warning XA0106: Skipping OAuthTest.Droid.Resource.Styleable.FontFamilyFont_fontWeight. Please check that your Nuget Package versions are compatible.

Should be noted that iOS and UWP platforms compile without error But
Its Probably Related to the versioning of Xamarin.Android.Support.* dependencies, I was wondering if there is a workaround or a specific set of plugins with specific versions required to get a new project up and running.

**Comment by moljac** [comment]
@GMaddison 

If your current packages are higher (downgrade), add Xamarin.Auth, then update everything. This should help.

Report outcome here pls.

**Comment by GMaddison** [comment]
So I Started another blank forms project with Shared Project code sharing strategy targeting Android specifically just to confirm, with the following dependencies added in default:

Xamarin.Android.Support.Design v25.4.0.2
Xamarin.Android.Support.v4 v25.4.0.2
Xamarin.Android.Support.v7.AppCompat v25.4.0.2
Xamarin.Android.Support.v7.CardView v25.4.0.2
Xamarin.Android.Support.MediaRouter v25.4.0.2
Xamarin.Forms v2.5.0.280555

And Adding the following Manually:
Xamarin.Auth v16.0.1
Xamarin.Android.Support.CustomTabs v25.4.0.2

still get the same associated errors, even more when adding the Xamarin.Auth.XamarinForms including the following line at the bottom of the log:

No way to resolve conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e". Choosing "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.

Xamarin Forms has a dependency for the support libraries at v25.4.0.2 so i unable to update/ downgrade any further. 

Also tried updating visual studio itself and everything Android/ Xamarin related but still get the same result.

**Comment by GMaddison** [comment]
Created a repo of my test project if that helps:

https://github.com/GMaddison/Xamarin.Auth-Dependancy-Error-

**Comment by aboulinguez** [comment]
Same problem here (213 warnings). Any update?

**Comment by orionstudt** [comment]
I'm experiencing the same warnings, new project.

I attempted what @moljac suggested: Uninstalled all android support Nugets, uninstalled Xamarin.Auth, installed android support Nugets at 23.3.0, installed Xamarin.Auth 1.6.0.1, updated android support Nugets to 25.4.0.2. Warnings persisted.

**Comment by moljac** [comment]
@GMaddison Thanks a lot for your sample repo. I did download it and tested and the warnings are there, but I was able to launch and work on the app.

The same is true for the completely new project I created.

I have no idea why these warnings appear. Seems that I cannot do too much about them.

**Comment by deakjahn** [comment]
Nothing to do with Auth. These warnings pop up everywhere in FX/Android. And can't be disabled.

**Comment by newky2k** [comment]
@GMaddison this doesn't appear to be a specific Xamarin.Auth issue.  Try updating to the latest version of the Xamarin Echo system components(Xamarin.Android, Visual Studio for Mac/Visual Studio Addin etc)

**Comment by gktval** [comment]
I have am having this issue also. i'm not sure how it cannot have anything to do with Xamarin.Auth, because when I remove the reference, my 127 errors go away. I've tried updating Xamarin/VS and changing my target Android version down to 7.0. Still cannot get the errors to resolve.
