### ISSUE TITLE
Provider Sample Solution Doesn't Compile

### ISSUE THREAD

**Issue by jenart** [xamarin/Xamarin.Auth#276]
# Xamarin.Auth Issue

I've dowlnloaded the .zip file and attempted to compile the provider sample solution in Visual Studio 2017:

`Xamarin.Auth-master\samples\Xamarin.Forms\Providers\XamarinAuth.XamarinForms.sln`

The solution file doesn't have the correct links to the supporting source projects. I manually updated the project references so I could at least load the various source projects.

I've upgraded `Xamarin.Forms` nuget package reference to `2.5.0.280555`.

Attempting to compile results in a truckload of errors that I can't seem to figure out how to resolve. All the errors are in `PageOAuthProviders.xaml.cs`

Unable to resolve references to: 

`Xamarin.Auth.SampleData`
`Xamarin.Auth.Helpers.OAuth1`
`Xamarin.Auth.Helpers.OAuth2`
`new PageOAuth()`
`new AuthenticationResult()`

The reference to `Xamarin.Auth.OAuthProviders.Portable` is correctly linked - which in turn links to the shared project `Xamarin.Auth.OAuthProviders.Shared` - where all the sample data and helper classes are defined. The portable project is compiling successfully and I can see the .dll in the `/bin/debug/` folder. Even if I explicitly reference this .dll from the `Xamarin.Auth (Portable)` project the references still fail to be resolved. 

Am I missing something obvious here?
Thanks,
Stuart

**Comment by moljac** [comment]
@jenart Samples are being rewritten. Simply they got too big to handle (too many OAuth providers).

**Comment by newky2k** [comment]
Samples are being rewritten as part of the job of works
