### ISSUE TITLE
Not being redirected back to the application in iOS

### ISSUE THREAD

**Issue by titonton** [xamarin/Xamarin.Auth#277]
I have everything set up exactly how it is supposed to be on the docs and on the examples, but for some reason i can't seem to be redirected back to the application after the authentication happens. I have isUsingNativeUI set to true and everything works fine, until I get redirected to google.com after signing in with the Google provider. 
On AppDelegate.cs
```
public override bool OpenUrl(UIApplication application, NSUrl url, string sourceApplication, NSObject annotation)
        {
            var uri = new Uri(url.AbsoluteString);

            AuthHandler.Auth.OnPageLoading(uri);

            return true;
        }
```

I have a AuthHandler class to take care of the handling
```
public static class AuthHandler
    {
        private static readonly OAuth2Authenticator auth= new OAuth2Authenticator
            (
                clientId: Constants.AuthClientID,
                clientSecret: null,
                authorizeUrl: new Uri("http://accounts.google.com/o/oauth2/auth"),
                accessTokenUrl: new Uri("http://www.googleapis.com/oauth2/v4/token"),
                isUsingNativeUI: true,
                redirectUrl: new Uri("{iosUrlScheme}:/oauth2redirect"),
                scope: "openid"
            );

        public static OAuth2Authenticator Auth
        {
            get{return auth;}            
        }

        public static void Authenticate()
        {
            var presenter = new Xamarin.Auth.Presenters.OAuthLoginPresenter();
            presenter.Completed += (sender, ev) =>
            {
                if (ev.IsAuthenticated)
                    Debug.WriteLine("authenticated \n\n\n\n\n\n\n\n\n\n\n");
            };
            presenter.Login(auth);
        }
    }
```

Where the object get's used in my LoginPage
```
public void TestAuth(object sender, EventArgs ev)
        {
            AuthHandler.Auth.Completed += (s, args) =>
            {
                if (args.IsAuthenticated)
                {
                    DisplayAlert("Yay", "Alright Alright Alright", "Alrighty then");
                }
            };
            AuthHandler.Authenticate();
        }
```

This project is using a.net standard2.0 and the latest stable Xamarin forms build

**Comment by moljac** [comment]
@titonton Can you create minimal sample pls (zip, repo) pls??

And go to Xamarin Community channel and ping me there.

**Comment by shrutigoyal123** [comment]
I am getting same issue. I am using xamarin.Auth 1.5.0.1 API for both android and iOS but in android it is working fine but in iOS 10 is not working as after entering emailid and password on facebook page it is not returning to forms.

Please help.

**Comment by newky2k** [comment]
@titonton @shrutigoyal123 can you please provide a sample that replicates this issue so we can investigate.

Regards

**Comment by newky2k** [comment]
no response for over two weeks, closing
