### ISSUE TITLE
UWP AuthenticatorPage does not work

### ISSUE THREAD

**Issue by zati-** [xamarin/Xamarin.Auth#278]
# Xamarin.Auth Issue

### Version

- [ ] nuget version = 1.6.0.1
- [ ] component version = 
- [ ] sample

### Steps to reproduce

Create a new project with Xamarin Forms and UWP

Create an authenticator
OAuth2Authenticator authenticator = new OAuth2Authenticator(...)
Navigation.PushAsync(new Xamarin.Auth.XamarinForms.AuthenticatorPage(authenticator));

Platform:
UWP Target : Windows 10 Fall Creators Update

### Expected behaviour

Authentication page should appear

### Actual behaviour

Blank page appear.

**Comment by newky2k** [comment]
@zati-  can you please provide some more details and a sample project that replicate the issue so we can investigate.

Regards
