### ISSUE TITLE
UWP deep linking restarts app using Xamarin Forms

### ISSUE THREAD

**Issue by zati-** [xamarin/Xamarin.Auth#279]
# Xamarin.Auth Issue

### Version

- [ ] nuget version = 1.6.0.1 

### Steps to reproduce

1. Create a Xamarin Forms UWP app using .NET Standard template
2. Add authentication

Platform:

UWP 

### Expected behaviour

See attached sample [AuthUWPBug.zip](https://github.com/xamarin/Xamarin.Auth/files/1869132/AuthUWPBug.zip)

After succesfull authentication, browser should close itself and go back to previous app window.
Label text should change to "Authentication ok"

### Actual behaviour

Browser close itself but app restarts.

Problem seems to be in `WebAuthenticatorPage.xaml.cs`

```
   private async void Button_Click(object sender, RoutedEventArgs e)
        {
            await
            Windows.ApplicationModel.Core.CoreApplication.MainView.CoreWindow.Dispatcher.RunAsync
                (
                    Windows.UI.Core.CoreDispatcherPriority.Normal,
                    () =>
                    {
                        this.Frame.GoBack();
                    }
                );

            return;
        }

```

**Comment by otis78** [comment]
I have the same issue. 
Any news about this problem?

**Comment by Brosten** [comment]
I'm also struggling with this one… Any news?

**Comment by newky2k** [comment]
if assigned @moljac to look into this.  please be patient while we investigate further.

**Comment by Redth** [comment]
Is this related to #202 ?

Can you work around it with the workaround mentioned in that issue?

**Comment by zati-** [comment]
Yes it is better with #202 workaround.
However there is still a "Do you want to switch application" popup when the deep link is activated

**Comment by Redth** [comment]
I'm not sure that's a limitation we can work around. In any case I'm going to close this issue and we can track it in #202. If you want to add any comments please put them there. Thanks!
