### ISSUE TITLE
I'm getting build error 

### ISSUE THREAD

**Issue by judsonabraham301** [xamarin/Xamarin.Auth#281]
This is the error I"m getting 
Severity	Code	Description	Project	File	Line	Suppression State
Error		The project file "..\..\..\..\..\..\source\XamarinForms\Xamarin.Auth.Forms\Xamarin.Auth.Forms.csproj" was not found.	ComicBook			
Severity	Code	Description	Project	File	Line	Suppression State
Error		The project file "..\..\..\..\..\..\source\Xamarin.Auth.Portable\Xamarin.Auth.Portable.csproj" was not found.	ComicBook

**Comment by moljac** [comment]
What are you trying to build?

**Comment by judsonabraham301** [comment]
I'm trying to build Evolve16Labs project

**Comment by judsonabraham301** [comment]
And I cant find "............\source\XamarinForms\Xamarin.Auth.Forms\Xamarin.Auth.Forms.csproj" anywhere in my project.

**Comment by judsonabraham301** [comment]
I have posted it on https://forums.xamarin.com/discussion/comment/327047#Comment_327047 aswell. Still no fix.

**Comment by judsonabraham301** [comment]
Sorry it was a simple mistake i didn't see  Xamarin.Auth.Forms and Xamarin.Auth.Portable in my reference. I removed these file and it worked successfully.

**Comment by judsonabraham301** [comment]
hey @moljac  why I'm getting github page when I'm clicking on google oauth. Will i get google authorization in this your app.

**Comment by newky2k** [comment]
Samples are being rewritten as part of the current job of work
