### ISSUE TITLE
[UWP] Cannot save Account with backslash in username

### ISSUE THREAD

**Issue by themultiplexer** [xamarin/Xamarin.Auth#282]
# Xamarin.Auth Issue

### Version

- [ ] nuget version = 4.6.0
- [ ] component version = 1.6.0.1

### Steps to reproduce

1. Create an **Account** instance with an username that contains a backslash.
2. Try to save it into the AccountStore.

Platform: Universal Windows Platform (UWP)

- [ ] .NET version = 4.6.25730.3 (.NET Standard 2.0)
- [ ] mono version = -

### Expected behaviour

The AccountStore should save the Account with the username **somedomain\user**. (like it does on Android with the same code).

### Actual behaviour

AccountStore stays empty.

**Comment by themultiplexer** [comment]
OK I more or less solved it and wrote a small utility class for saving and retrieving Accounts.
Before I store the Account I encode the username with **WebUtility.Encode()**.
After I retrieve the Account I decode the username with **WebUtility.Decode()** and return it.

I don't know whether UrlEncode is the right way, but it works.

**Comment by newky2k** [comment]
resolved
