### ISSUE TITLE
OAuth2Authenticator.authorizeUrl doesn't handle a url with a querystring already present

### ISSUE THREAD

**Issue by frigon** [xamarin/Xamarin.Auth#284]
# Xamarin.Auth Issue

*IF BUG, INCLUDE THIS PART:*

### Version

- [ ] nuget version = 1.6

### Steps to reproduce

1.  add OAuth2Authenticator.authorizeUrl  field that ALREADY has a querystring "http://myidp.com/login?someparameter=somevalue"
2.  observer the url launched has 2 querystrings in the url:  http://myidp.com/login?someparameter=somevalue?clientid=....

Platform:

-	[] .NET version = 
-	[] mono version = 

### Expected behaviour
It a url should only have one ? .

Tell us what should happen

### Actual behaviour

Tell us what happens instead
Can you also include a screen shot?

*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by newky2k** [comment]
@frigon could you please provide a small sample project that demonstrates this issue to make it easier to replicate.

**Comment by newky2k** [comment]
no response for over two weeks, closing
