### ISSUE TITLE
OAuth2Authenticator does not check CSRF foregeries in Implicit Grant

### ISSUE THREAD

**Issue by mipnw** [xamarin/Xamarin.Auth#285]
# Xamarin.Auth Issue

OAuth2Authenticator checks for forgeries only sometimes. In Implicit Grant the state is returned via a fragment, not a query, and it doesn't get checked against the expected state, leaving the app vulnerable to CSRF.

I have a fix. I'll submit a PullRequest shortly.

### Version

-nuget version = 1.6.0.1

**Comment by newky2k** [comment]
PR Submitted
