### ISSUE TITLE
What happened to AccountStore in 1.6.0.2

### ISSUE THREAD

**Issue by HappyTreesDev** [xamarin/Xamarin.Auth#288]
# Xamarin.Auth Issue

The latest version of Xamarin.Auth seems to have either moved or gotten rid of AccountStore. Where did it go or what happened?

*IF BUG, INCLUDE THIS PART:*

### Version

- [ ] nuget version = 1.6.0.2

### Steps to reproduce

1. Import Xamarin.Auth
2. Attempt to use AccountStore

### Expected behaviour

Intelisense should recognize AccountStore and the class should exist

### Actual behaviour

The class cannot be found and the code will not compile. Downgrading xamarin.auth to 1.6.0.1 solves the issue so it somehow disappeared.

**Comment by moljac** [comment]
@HappyTreesDev 

Sorry, but I'm confused (not just a bit), so I created a minimal sample and code compiles and intellisense works.

Yes there were changes on AccountStore for Android. I finally got more information for some older bugs.

I added Xamarin.Forms sample to the master, but you can also find it here (samples only in the repo):

https://github.com/moljac/Xamarin.Auth.Samples.NugetReferences/tree/master/samples/bugs-triaging/AccountStore

**Comment by moljac** [comment]
@HappyTreesDev 

Morn
did you have by chance, time to test it? I need feedback pls.

Thanks

**Comment by HappyTreesDev** [comment]
Hi, I looked into this and I think this was actually an issue I was having with the latest version of VS 2017. It has been getting into a broken state quite often with the latest build.
