### ISSUE TITLE
What is the possibility delete a given key rather than removing the entire Account in Keychain  ?

### ISSUE THREAD

**Issue by gadperera** [xamarin/Xamarin.Auth#289]
# Xamarin.Auth Issue

*IF BUG, INCLUDE THIS PART:*

### Version

- [ ] nuget version = 
- [ ] component version = 
- [ ] sample

### Steps to reproduce

1.
2.
3.

Platform:

-	[] .NET version = 
-	[] mono version = 

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead
Can you also include a screen shot?

*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by newky2k** [comment]
@gadperera  can you please provide some more detail about what you're trying to achieve, what classes you are using now and what you propose for it to work the way you want

Regards

**Comment by newky2k** [comment]
no response for two weeks, closing
