### ISSUE TITLE
Xamarin.Auth 1.6.0.2 -> Xamarin.Android.Support.CustomTabs 25.4.0.2 -> Xamarin.Android.Support.Compat (= 25.4.0.2)

### ISSUE THREAD

**Issue by patsadow2** [xamarin/Xamarin.Auth#290]
Good job:

 Parking.Droid -> Xamarin.GooglePlayServices.Maps 60.1142.1 -> Xamarin.GooglePlayServices.Basement 60.1142.1 -> Xamarin.Android.Support.Compat (>= 26.0.2) 
 Parking.Droid -> Xamarin.Auth 1.6.0.2 -> Xamarin.Android.Support.CustomTabs 25.4.0.2 -> Xamarin.Android.Support.Compat (= 25.4.0.2).

**Comment by nvmkpk** [comment]
Xamarin.Auth needs to be updated for Android Oreo.

**Comment by knagjun** [comment]
Android Project's Nuget Package install..
1. Xamarin.Android.Support.Compat install
2. Xamarin.Android.Support.CustomTabs install
Last. Xamarin.Auth install

**Comment by newky2k** [comment]
no response for over two weeks, closing
