### ISSUE TITLE
UWP app Presenter.Login shows blank white screen

### ISSUE THREAD

**Issue by paulelong** [xamarin/Xamarin.Auth#292]
# Xamarin.Auth Issue
### Version

- [ ] nuget version = 1.6.0.2
- [ ] component version = 
- [ ] sample = https://github.com/paulelong/Wilson

### Steps to reproduce
1.  Launch login UI using Presenter.Login
2.  Web page is blank on UWP, works on Android device

Platform:
-	[] .NET version = .Net Standard 2.0
-	[] mono version = 

### Expected behaviour
I think the web page should display showing an authentication screen where I can log into Google services.

### Actual behavior
The page shows up blank.  If I press back, the AuthenticationCompelte callback is run, but the IsAuthenticated is false.

This works for me on an Android device, so I think the code is correct.  Though there seems to be a lot of changes in the last few months, and it's difficult to find a good example.  For instance, I see references to GetUI, but that doesn't seem to exist now, and Presenter.Login I believe is the new way.  I've also seen references to UWP not working, and even a similar issue.  However I could understand if this is a known issue, or something lacking in my code.

**Comment by newky2k** [comment]
@paulelong Can you provide a small sample that replicates the issue so we can investigate.

**Comment by newky2k** [comment]
no response for two weeks, closing
