### ISSUE TITLE
AccountStore usage produces warning "This version is insecure, because of default password..."

### ISSUE THREAD

**Issue by JMcLauchlanSQ** [xamarin/Xamarin.Auth#293]
# Xamarin.Auth Issue

I recently installed Xamarin.Auth and started using the AccountStore class. I have noticed recently that android logs are containing messages warning about security:
```
This version is insecure, because of default password.
Please use version with supplied password for AccountStore:
    AccountStore.Create(Contex, string);
```

Any ideas as to why I am seeing this message or if anything needs to be done about it?

### Version
- [ ] component version = 1.6.0.2

### Steps to reproduce

1. Use AccountStore.Create();

Platform:

-	[] .NET version = 4.61

### Expected behaviour

No warnings in the android log

### Actual behaviour

Warning in the android log:
```
Using:
05-07 14:29:19.223 I/mono-stdout(24759): Using:
    AccountStore.Create(Contex);
or
    AccountStore.Create();
This version is insecure, because of default password.
Please use version with supplied password for AccountStore:
    AccountStore.Create(Contex, string);
or
    AccountStore.Create(string);
```

**Comment by HelenMamalaki** [comment]
@moljac 
Can you help me understand what the password is used for to make an informed decision on weather to switch to the ? Is it used for further encryption of data stored in SharedPreferences? (assuming that's where the Android instance of the Account Store stores data?)
