### ISSUE TITLE
KeyStore integrity check failed

### ISSUE THREAD

**Issue by fekberg** [xamarin/Xamarin.Auth#297]
# Xamarin.Auth Issue

*KeyStore integrity check failed.*

App crashes when using Xamarin.Auth on Android.

### Version

NuGet version 16.0.2

### Steps to reproduce

1. Install 15.0.3
2. Compile, Publish and Run the App
3. Install 16.0.2
4. Compile, Publish and Run the App

You will now get "KeyStore integrity check failed" when looking at adb logcat

Platform: Android, tested on Galaxy S9+

### Expected behaviour

Not crashing the app

### Actual behaviour

App crashes with "KeyStore integrity check failed."

### Workaround

Downgrade to 15.0.3

**Comment by mikegottlieb** [comment]
I'm also seeing this. I was upgrading to fix the KeyStore not initialized bug.

**Comment by cklenk** [comment]
I just received this same error too using 1.6.0.2. Thanks.

**Comment by LokeshBhatt79** [comment]
I am also receiving the same error, Please help.

**Comment by fekberg** [comment]
@LokeshBhatt79 Downgrade to 15.0.3 for now.

**Comment by Umar3x** [comment]
This is a serious bug. Published an app to prod yesterday had main complains about app crashes, checked logcat and saw that ... Arf. So only way for now is downgrading and publish again I guess ?
Thanks for support.

**Comment by Leobaillard** [comment]
Does this also happen with 1.6.0? I'm using netstandard and cannot revert to 1.5.x as it does not support it...

**Comment by Umar3x** [comment]
@Leobaillard
We also target NET Standard and there is no prob with 1.5. Have you got the fallback on NET 4.5?

**Comment by Leobaillard** [comment]
I don't think I do. Do I just have to add ` <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>` in the `.csproj` of the NET Standard library?

**Comment by Umar3x** [comment]
Yep should be enough.

**Comment by bastianbecker21** [comment]
I am facing same issue. The app crashes after upgrading new version from google play, new version is using 1.6.0.2, original working version is 1.6.0.
I am using PCL in Xamarin Forms project. Any solution here?

**Comment by HappyTreesDev** [comment]
#291

**Comment by fekberg** [comment]
Fix has been "in progress" since 16 May. 

What's going on?

**Comment by tharanagaraj** [comment]
Is downgrading Xamarin.Auth to 1.5.x the only temporary solution to this? Does that version cause the 'KeyStore was not initialized' and/or 'Uninitialized keystore' issue?

**Comment by Umar3x** [comment]
For now yes, staying at 1.5 is the only solution ... waiting for update and news of @moljac

**Comment by tharanagaraj** [comment]
1.5 still causes the 'KeyStore was not initialized' and/or 'Uninitialized keystore' issue. 
Is manually deleting the app data a possible workaround, so that the keystore will be recreated and initialized correctly? We have users that are unable to login to our app.

**Comment by Umar3x** [comment]
That's strange, I only have this issue with ~1.6.0. Yes imho you can erase app data, should also work with 1.6.0 ... I tried to find a way to erase data manually (as I found out that it was fixing the prob)  but I did not dig into it. If you find a way, would be glad if you share :)

**Comment by michaelgobbers** [comment]
This is a huge bug. Thank god for QA checking migration scenario's... Any new on a fix for this.

**Comment by fekberg** [comment]
@moljac 5 months since you said "fix in progress". Is Xamarin.Auth dead, or are you still maintaining it?

**Comment by Redth** [comment]
Hey folks, apologies for the inaction here.  We are going to address this particular issue very soon.  

As Xamarin.Essentials nears release, I'd also like to encourage moving over to its Secure Storage API and away from Keystore in Xamarin.Auth which we intend to mark as obsolete/deprecated.

**Comment by newky2k** [comment]
Xamarin.Auth 1.6.0.3 has now been published to Nuget

**Comment by cklenk** [comment]
@Redth Is there a guide anywhere on the best way to migrate from xamarin.auth or xamarin.essentials secure storage? So you don't have to re-enter the credentials?

Thanks

**Comment by Redth** [comment]
I've written up a migration guide that includes a class to help with the data/code migration:
https://github.com/xamarin/Xamarin.Auth/wiki/Migrating-from-AccountStore-to-Xamarin.Essentials-SecureStorage

**Comment by cklenk** [comment]
Thanks @Redth I will take a look!
