### ISSUE TITLE
CFBundleTypeRole Viewer is written incorrectly

### ISSUE THREAD

**Issue by paulelong** [xamarin/Xamarin.Auth#298]
# Xamarin.Auth Issue
I believe the info.plist for the Evolve16Labs is incorrect.  It shows CFBundleURLTypes key with value of Viewer.  Should that be CFBundleTypeRole instead?

	<array>
		<dict>
			<key>CFBundleURLName</key>
			<string>Xamarin.Auth Google OAuth</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.xamarin.traditional.standard.samples.oauth.providers.ios</string>
				<string>com.googleusercontent.apps.1093596514437-cajdhnien8cpenof8rrdlphdrboo56jh</string>
				<string>fb1889013594699403</string>
				<string>xamarin-auth</string>
			</array>
			<key>CFBundleURLTypes</key>  <--------- HERE
			<string>Viewer</string>
		</dict>
	</array>

### Steps to reproduce
I'm not sure if this is causing an issue as I have not tried to run the sample, but I think this is incorrect because of this article:  https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth.

Plus as it is right now, CFBundleURLTypes appears twice, which seems peculiar.

**Comment by newky2k** [comment]
samples are a work in progress and will be updated in the near future
