### ISSUE TITLE
[iOS] Strava authenticate 'unknown_user' error

### ISSUE THREAD

**Issue by stesvis** [xamarin/Xamarin.Auth#302]
# Xamarin.Auth Issue

### Version

- [ ] nuget version = 1.6.0.2

### Steps to reproduce
I am loading the Strava authentication page like this:

```
            var authenticator = new OAuth2Authenticator(
                clientId: myClientId,
                clientSecret: myClientSecret,
                scope: "view_private,write",
                authorizeUrl: new Uri(@"https://www.strava.com/oauth/authorize"),
                redirectUrl: new Uri(myRedirectUri),
                accessTokenUrl: new Uri(@"https://www.strava.com/oauth/token"),
                getUsernameAsync: null,
                isUsingNativeUI: false);

            authenticator.Completed += OnStravaAuthCompleted;
            authenticator.Error += OnStravaAuthError;

            AuthenticationState.Authenticator = authenticator;

            var presenter = new Xamarin.Auth.Presenters.OAuthLoginPresenter();
            presenter.Login(authenticator);
```
As soon as the Strava login page is loaded, I get error messages such as

> OAuth Error = unknown_user

and it keeps coming back when I close it.
The same code works perfectly in Android.

**Comment by newky2k** [comment]
@stesvis  can you please provide a small sample project that replicates the issue so we can investigate it further

**Comment by stesvis** [comment]
Hi @newky2k sorry i don't have one. i changed approach and now i am just calling the strava api directly.

**Comment by newky2k** [comment]
@stesvis  thanks anyway

**Comment by vai1991sri** [comment]
HI I am also getting this issue.
I integrated OAuth2Authenticator for Instagram sign in but after opening in bbor

**Comment by fernandovm** [comment]
Hi, any news? I'm also getting this issue with instagram, exactly as described by @vai1991sri.

**Comment by KevinHu-au** [comment]
Get the same error when using Xamarin.Auth with Instagram
