### ISSUE TITLE
The remote server returned an error: (403) Forbidden

### ISSUE THREAD

**Issue by krupanshu** [xamarin/Xamarin.Auth#303]
# Xamarin.Auth Issue

*IF BUG, INCLUDE THIS PART:*

### Version

- [ ] nuget version = 1.6.0.2

### Steps to reproduce

1. Try to do authentication with Twitter

Platform:

-	[] .NET version = 
.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
-	[] mono version =  5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)

### Expected behaviour

It should open twitter login page and from there user can enter and get authorized from twitter Oauth. 

### Actual behaviour

It is displaying error 

**The remote server returned an error: (403) Forbidden**

![image-2018-06-19-10-02-16-791](https://user-images.githubusercontent.com/16252935/41652644-4da64882-74a1-11e8-8be4-a8603fa4b68c.png)

**Comment by rofiqsetiawan** [comment]
@krupanshu
Make sure your `callback_url` already added on `https://apps.twitter.com/` > `Settings`

**Comment by krupanshu** [comment]
Thanks for your quick reply. It works like charm. I am closing this issue.
