### ISSUE TITLE
[1.6.0.2] CustomTab not closing for Android

### ISSUE THREAD

**Issue by gabrielsalmeida** [xamarin/Xamarin.Auth#306]
# Xamarin.Auth Issue

*IF BUG, INCLUDE THIS PART:*
On 1.6.0.2 for Android, CustomTab is not closing after log on. Returning to 1.5.0.3 fixed the problem.

1.6.0.2 Version

- [Xamarin.Auth / Xamarin.Auth.XamarinForms ] nuget version = 1.6.0.2
- [Xamarin Forms version 3.1]
- [NetStandard 1.4]

### Steps to reproduce

1. Log on thru some OAuth2.0(tested with Facebook and G+).
2. UrlSchemeInterceptor was fired(as inside my app, screen changed), however, seems that OnPageLoading(parameter) is not closing the CustomTab.

### Expected behaviour

As on version 1.5.0.3, CustomTab should close and sent back to App.

### Actual behaviour

CustomTab remain opened.

**Comment by newky2k** [comment]
@gabrielsalmeida @kensykora can you please provide a simple sample that replicates the issue so we can investigate

**Comment by newky2k** [comment]
no response for two weeks closing

**Comment by kensykora** [comment]
Hi @newky2k please re-open
