### ISSUE TITLE
Real use example of secure version of AccountStore.Create

### ISSUE THREAD

**Issue by No1e** [xamarin/Xamarin.Auth#309]
# Xamarin.Auth Issue

Can you please provide us with an example of proper use of secure AccountStore.Create?

Please allow me to describe use case.
I am using encrypted SQLite database (SQLCipher) to keep the data protected. This database requires password to open db connection.

 I have two types of data: users specific and application specific. The reason for this is that in the enterprise the common case is that we have Android base device (Zebra, Honeywell) share among multiple users. For each user, the data is stored in user dedicated database, and decryption of those db's are done during the user login procedure.

On the other hand, app specific data is store into app dedicated database. In order to protect DB, app generates strong password that must be stored locally, so that application can open db connection, and access the data without user intervention.

For storing this app specific password, I am using AccountStore.Create, so that I can read it from there, and open connection to database. New secure method is requires the password to be provided, so how should I store that particular password in secure way?

Kind regards,
Novak

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by Redth** [comment]
We are planning on deprecating `AccountStore`.  Please check out the Secure Storage API's in Xamarin.Essentials instead: https://docs.microsoft.com/en-us/xamarin/essentials/secure-storage?tabs=ios
