### ISSUE TITLE
Xamarin.Auth: Browser opens Twice in Android for Authentication

### ISSUE THREAD

**Issue by halderp** [xamarin/Xamarin.Auth#310]
# Xamarin.Auth Issue

*IF BUG, INCLUDE THIS PART:*

### Version

- [ ] nuget version = 1.6.0.1
- [ ] component version = 1.6.0.1
- [ ] sample

### Steps to reproduce

1. Created a Custom Authenticator to override OnCreatingInitialUrl method to add an additional parameter:
  authenticator = new CustomeOAuth2Authenticator
                (
                    clientId: ServerInfoFinal.ClientId,
                    clientSecret: ServerInfoFinal.Secret,
                    scope: ServerInfoFinal.Scope,
                    authorizeUrl: ServerInfoFinal.AuthorizationEndpoint,
                    redirectUrl: ServerInfoFinal.RedirectionEndpoint,
                    accessTokenUrl: ServerInfoFinal.AccessTokenEndPoint,
                    isUsingNativeUI: true
                );
2. From my activity launched the Browser:
            var presenter = new Xamarin.Auth.Presenters.OAuthLoginPresenter();
            presenter.Login(authenticator);

Platform:

Android (iOS works as expected)

### Expected behaviour

Browser should be launched only once for Authentication

### Actual behaviour

On Android Browser is Launched twice for Authentication. As a result one Browser Instance is in the backstack after authentication

*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by newky2k** [comment]
@halderp can you please provide a simple sample that demonstrates the issue that you are having so we can investigate.

Regards

**Comment by halderp** [comment]
Hi Dave
Attached the sample application.
You can easily reproduce the problem by:1) Launch app2) Press "Start Authentication" button3) It would open up our Authorization URL. Please allow 10-20 seconds of time4) Once launched click "Back" button or "X" on Browser5) You can notice the Auth Page is launched twice.RegardsPrashanta
    On Monday, September 10, 2018, 1:59:52 PM PDT, Dave Humphreys <notifications@github.com> wrote:  
 
 
@halderp can you please provide a simple sample that demonstrates the issue that you are having so we can investigate.

Regards

**Comment by newky2k** [comment]
@halderp There is an attachment with the sample project on it i'm afraid.  You need to go the issue itself at attach it.

Regards

**Comment by newky2k** [comment]
No response to request to attach the sample project to the issue, seem that they just responded to the email

**Comment by altondevir** [comment]
We have the same problem, iOS fine but android being called twice. It seems that when we close the native browser then another native browser seems to be called.
