### ISSUE TITLE
After deny of access to DropBox account Presenter stays open on Android with Xamarin.Forms

### ISSUE THREAD

**Issue by Creal1** [xamarin/Xamarin.Auth#313]
# Xamarin.Auth Issue

*IF BUG, INCLUDE THIS PART:*

### Version

- [x] nuget version = 1.6.0.2
- [x] component version = 1.6.0.2

### Steps to reproduce

1. Create OAuth2 Login for DropBox
2. Successfully sign-In with your credentials
3. Deny the access to your DropBox account

### My Code
var authenticator = new OAuth2Authenticator(DropBoxAppKey,
                                                                    null,
                                                                    new Uri(RedirectUrl),
                                                                    new Uri(AndroidRedirectUrl),
                                                                    null,
                                                                    false);
                    authenticator.ShowErrors = false;
                    authenticator.Title = "Login to DropBox";
                    authenticator.State = new Xamarin.Auth.OAuth2.State
                    {
                        RandomString = args.State
                    };
                    authenticator.Completed += OnAuthCompleted;
                    authenticator.Error += OnAuthError;

                    AuthenticationState.Authenticator = authenticator;

                    var presenter = new Xamarin.Auth.Presenters.OAuthLoginPresenter();
                    presenter.Completed += Presenter_Completed;
                    presenter.Login(authenticator);

Platform:

- [ ] Xamarin.Forms = 3.1.0.697729
- Only the iOS version works as expected

### Expected behaviour
The presenter closes after denying the access as in iOS.

### Actual behaviour
The presenter with the Deny and Accept Button of DropBox stays open. 
REMARKS: The Error Event of the OAuth2Authenticator gets called/fired but i found no way to close the presenter manually in code nor find the presenter in the current (Modal)NavigationStack.

**Comment by newky2k** [comment]
@Creal1 can you please provide a small sample project that demonstrates the issues so that we can investigate

Reagrds
