### ISSUE TITLE
oAuth flow works fine on Android 7 and above but see ERR_UNKNOWN_URL_SCHEME on Android < 7

### ISSUE THREAD

**Issue by xamarinrk1** [xamarin/Xamarin.Auth#314]
# Xamarin.Auth Issue

*IF BUG, INCLUDE THIS PART:*

Seeing ERR_UNKNOWN_URL_SCHEME error while redirecting oAuth flow back to android app only for the versions less than 7. 

oAuth flow works fine with latest android versions 7 and above

### Version

- [ ] nuget version = 1.6.0.2
- [ ] component version = 
- [ ] sample
Followed the steps exactly mentioned here, https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth

### Steps to reproduce
1.  try the oAuth flow on Oreo API 27
2.  try the same oAuth flow on KitKat API 19
3.

Platform:

-	[] .NET version = .NET Standard 2.0
-	[] mono version = 

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead
Can you also include a screen shot?

*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by newky2k** [comment]
@xamarinrk1 can you please provide a simple sample that denonstrates the issue.

Regards

**Comment by newky2k** [comment]
no response after more than two weeks, closing
