### ISSUE TITLE
Version Conflict with Android

### ISSUE THREAD

**Issue by eman1986** [xamarin/Xamarin.Auth#316]
# Xamarin.Auth Issue

Version conflict detected for Xamarin.Android.Support.Compat. Install/reference Xamarin.Android.Support.Compat 27.0.2.1 directly to project XamarinForms.Android to resolve this issue.
XamarinForms.Android -> Xamarin.Android.Support.v7.MediaRouter 27.0.2.1 -> Xamarin.Android.Support.v7.Palette 27.0.2.1 -> Xamarin.Android.Support.Compat (= 27.0.2.1) 
XamarinForms.Android -> XamarinForms.Shared -> Xamarin.Auth 1.6.0.2 -> Xamarin.Android.Support.CustomTabs 25.4.0.2 -> Xamarin.Android.Support.Compat (= 25.4.0.2).	

### Version
**Shared Layer:**
- Xamarin.Auth => 1.6.0.2
- Xamarin.Forms => 3.1.0.697729

**Android Layer:**
- Xamarin.Android.Support.Design => 27.0.2.1
- Xamarin.Android.Support.v4 =>27.0.2.1
- Xamarin.Android.Support.v7.AppCompat => 27.0.2.1
- Xamarin.Android.Support.v7.CardView => 27.0.2.1
- Xamarin.Android.Support.v7.MediaRouter => 27.0.2.1
- Xamarin.Forms => 3.1.0.697729

### Steps to reproduce
1. Install Xamarin.Auth
2. Try to build solution
3. Failure

Platform:
- .NET version = 4.6
- mono version = MonoAndroid 9.0

I did try to install Xamarin.Android.Support.Compat but that just made things worse. Should I be using the xamarin forms version instead? The [example](https://github.com/xamarin/recipes/tree/master/Recipes/xamarin-forms/General/store-credentials/StoreCredentials) made by xamarin wasn't.

**Comment by newky2k** [comment]
@eman1986 adding @moljac to help with this issue

**Comment by Redth** [comment]
You're going to have to add explicit references to the correct versions of the transitive dependencies to fix this (this is a symptom of using `PackageReference`).  You can see a bit more about how to solve this here: https://redth.codes/how-to-fix-the-dreaded-version-conflict-nuget-error-in-your-xamarin-android-projects/
