### ISSUE TITLE
Getting white screen when change orientation on auth screen

### ISSUE THREAD

**Issue by MJRomka** [xamarin/Xamarin.Auth#318]
When I navigate to the auth screen in portrait mode I see something:
<img width="517" alt="port" src="https://user-images.githubusercontent.com/3237392/45000707-01058f00-afd0-11e8-897b-99c4accacda5.png">
Then when I rotate a device it goes white and I have to restart the app to exit:
<img width="964" alt="land" src="https://user-images.githubusercontent.com/3237392/45000720-14b0f580-afd0-11e8-8606-d48e5787fd4c.png">

> VS bug [#733073](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/733073)

**Comment by mjromka** [comment]
The bug is not reproducible now
