### ISSUE TITLE
KeyStore password defaults to System.Char[]

### ISSUE THREAD

**Issue by fekberg** [xamarin/Xamarin.Auth#320]
# Xamarin.Auth Issue
The hardcoded password isn't used with the default constructor.

When you do `ToString()` on a char-array, it gives you the text System.Char[].

![image](https://user-images.githubusercontent.com/1154001/45618598-8a0fd200-ba76-11e8-8e9d-7b2014e5fb5f.png)

You'd have to do `new string(PasswordHardCoded)`, or `string.Join`, however, this will break backwards compatibility and it should migrate to the default password (if that option should still exist)

**Comment by newky2k** [comment]
@fekberg The issue with the Tostring() appears to be a mono issue, rather than a Xamarin.Auth issue.

I've assigned @moljac  to look into it for you

**Comment by fekberg** [comment]
@newky2k No, doing ToString on a char[] is incorrect.

See here as well: https://stackoverflow.com/questions/1324009/net-c-sharp-convert-char-to-string

Try it out using either mono or roslyn. Should definitely return "System.Char[]" as a string and not the actual content.

**Comment by fekberg** [comment]
@newky2k Any update?

**Comment by newky2k** [comment]
@fekberg I have assigned this issue to @moljac for him to investigate

**Comment by Redth** [comment]
We're working on a fix for this and should have it ready very soon.

**Comment by newky2k** [comment]
@fekberg  I'm looking into this now,  It appears that Xamarin.Auth was changed to use new string(PasswordHardCoded) in this commit -> https://github.com/xamarin/Xamarin.Auth/commit/f529702f8ba66712d4842dc19e614c6f5be8f260#diff-a69956567d5f7649f40fae8df21be687R53

I'm looking into the migration from the 'System.Char[]' to the content of PasswordHardCoded instead now.

Thank you for your patience

**Comment by newky2k** [comment]
Xamarin.Auth 1.6.0.3 has now been published to Nuget
