### ISSUE TITLE
Tapping "X" on Android CustomTab interface does not close window

### ISSUE THREAD

**Issue by kensykora** [xamarin/Xamarin.Auth#324]
This is a re-submission of #306 which was closed due to inactivity for request for a reproducible code sample. I provided one after it was closed, but was never re-opened. This is still occurring in our app today and we need to identify a fix for it.

# Xamarin.Auth Issue

On 1.6.0.2 for Android, CustomTab is not closing when the user taps the "X" button to close the custom tab and navigate back. It launches another custom tab instead. Tapping "X" on the new custom tab window will finally close the window.

Logging in normally works fine otherwise.

* [Xamarin.Auth / Xamarin.Auth.XamarinForms ] nuget version = 1.6.0.2
* [Xamarin Forms version 3.2.0.839982]
* [NetStandard 2.0]
 
### Steps to reproduce

Please see my reproduction here: https://github.com/kensykora/xamarin-auth-issue-306

1. Launch App
2. Tap "Login" Button
3. Observe that chrome custom tab browser opens
4. Tap the "X" button in the upper left.

**Expected**: Browser closes, the Authenticator `Completed` event occurs, with the user being not logged in.
**Actual**: Custom tab opens up again, same page

**Workaround**: After step 4, perform step 5:

5. Tap "X" in the upper left a second time on the new window that opened. Observe that the browser closes and the Authenticator `Completed` event occurs, with the user being not logged in.

**Comment by newky2k** [comment]
@kensykora thanks for resubmiting and providing a sample.  I will get @moljac to look into it for you

Regards

**Comment by dinhnc60290** [comment]
I have checked and it seems that `custom_tabs_intent.LaunchUrl(activity, uri);` it is called twice when closing, once outside the delegate and once inside the delegate.
https://github.com/xamarin/Xamarin.Auth/blob/master/source/Core/Xamarin.Auth.XamarinAndroid/UINativeNonIntegratedBrowsers/CustomTabsUtilities/CustomTabActivityHelper.cs#L109-L123
```
      custom_tabs_intent.LaunchUrl(activity, uri);   ------------------------>HERE
				custom_tabs_activity_manager.CustomTabsServiceConnected +=
                                // custom_tabs_activit_manager_CustomTabsServiceConnected
                                delegate
                                    {
                                        System.Diagnostics.Debug.WriteLine("CustomTabsActivityManager.CustomTabsServiceConnected");

                                        custom_tabs_activity_manager.LaunchUrl(uri.ToString()); ------------> HERE

                                        System.Diagnostics.Debug.WriteLine("CustomTabsActivityManager.LaunchUrl");

                                        return;
                                    }
                                ;
                System.Diagnostics.Debug.WriteLine($"CustomTabsActivityManager.BindService({package_name_for_custom_tabs})");
```

**Comment by newky2k** [comment]
@kensykora @lewixlabs  could you provide a PR for this so we can merge the changes in to the code

Regards

**Comment by lewixlabs** [comment]
> @kensykora @lewixlabs could you provide a PR for this so we can merge the changes in to the code
> 
> Regards

@newky2k i made a pull request
https://github.com/xamarin/Xamarin.Auth/pull/332

I have a demo project i built & tested and all seem working, CustomTab is open once, not twice, and result is sent on my callback in custom url scheme correctly! 👍 

Tomorrow i will do other tests, let me know if you need more infos.
Thanks!

Lewix
