### ISSUE TITLE
AccountStore data not deleted when re-install program (iOS)

### ISSUE THREAD

**Issue by achyusuf** [xamarin/Xamarin.Auth#330]
# Xamarin.Auth Issue

AccountStore data not deleted when i try to re install my app.

### Version

- [ ] nuget version = 1.6.0.1
- [ ] component version = 
- [ ] sample

### Steps to reproduce

1.
2.
3.

Platform:

-	[] .NET version = 
-	[] mono version = 

### Expected behaviour

AccountStore data must be clear

### Actual behaviour

when i save user data after login for skip login page when i open apps again. But when i re-install apps, i think this should be clear but isnt

**Comment by stealthcold** [comment]
I think it's related to iCloud sync.. I have an app using native login and it has the same behavior as xamarin.auth.

**Comment by achyusuf** [comment]
> I think it's related to iCloud sync.. I have an app using native login and it has the same behavior as xamarin.auth.

I'm not sure about this, but can you give me solution about this issue ?

Thank Before.

**Comment by Redth** [comment]
We are planning on deprecating `AccountStore` in the next release.  Please check out the Secure Storage API's in Xamarin.Essentials instead: https://docs.microsoft.com/en-us/xamarin/essentials/secure-storage?tabs=ios
