### ISSUE TITLE
this code doesn't let using a class inherited from OAuth2Authenticator

### ISSUE THREAD

**Issue by iWeaverMan** [xamarin/Xamarin.Auth#334]
_Originally posted by @iWeaverMan in https://github.com/xamarin/Xamarin.Auth/commit_comment/create#commitcomment-31116170_

**Comment by newky2k** [comment]
@iWeaverMan  Can you please provide some more details as the link you posted doesn't work.

Regards

**Comment by iWeaverMan** [comment]
this is the same error: https://github.com/xamarin/Xamarin.Auth/pull/295
