### ISSUE TITLE
Xamarin.Auth built with old version of Xamarin.Android.Support.Compat

### ISSUE THREAD

**Issue by donmesserli** [xamarin/Xamarin.Auth#335]
# Xamarin.Auth Issue

Xamarin.Auth built with Xamarin.Android.Support.Compat 24.0.5.2 which conflicts with the current version of Xamarin.Android.Support.Compat 27.0.2.1. The nuget package won't load.

### Version

- [ ] nuget version = 
- [ ] component version = 1.6.0.2
- [ ] sample

### Steps to reproduce

1. Add Xamarin.Auth to an Android project of a Xamarin.Forms app.
2.
3.

Platform:

-	[] .NET version = 
-	[] mono version = 

### Expected behaviour

Component should load
### Actual behaviour

Get the following error:
```
Severity  Code    Description Project File    Line    Suppression State Error   NU1107  Version conflict detected for Xamarin.Android.Support.Compat. Install/reference Xamarin.Android.Support.Compat 27.0.2.1 directly to project SW.Advantage.Mobile.Advantage4Kids.Android to resolve this issue.   SW.Advantage.Mobile.Advantage4Kids.Android -> Xamarin.Android.Support.v7.MediaRouter 27.0.2.1 -> Xamarin.Android.Support.v7.Palette 27.0.2.1 -> Xamarin.Android.Support.Compat (= 27.0.2.1)   SW.Advantage.Mobile.Advantage4Kids.Android -> Xamarin.Auth 1.6.0.2 -> Xamarin.Android.Support.CustomTabs 25.4.0.2 -> Xamarin.Android.Support.Compat (= 25.4.0.2).  SW.Advantage.Mobile.Advantage4Kids.Android  C:\SourceCode\Southwestern\1.DEV\SW\Advantage\Mobile\Advantage4Kids\Android\SW.Advantage.Mobile.Advantage4Kids.Android.csproj   1 
```

**Comment by Redth** [comment]
Xamarin.Auth requires 25.x or _newer_ of support libraries.  This should still work fine with newer versions installed in your app.
