### ISSUE TITLE
The Google account is being added in the device while login to new Google account. How to prevent this?

### ISSUE THREAD

**Issue by nmano2188** [xamarin/Xamarin.Auth#336]
I'm using xamarin auth 1.5.0.3 version and Netstandard 2.0 xamarin form

**Comment by newky2k** [comment]
@nmano2188  Can you please provide some more details on what the issues is.  Also we have just released 1.6.0.3, can you replicate  the issue in that and see if it still exists.

Regards

**Comment by nmano2188** [comment]
@newky2k OKAY. I will check and update.

**Comment by Redth** [comment]
Closing due to no response in over a week.  Please open a new issue with more information if you continue to experience this problem.
