### ISSUE TITLE
not found WebAuthenticatorPage.xbf

### ISSUE THREAD

**Issue by iWeaverMan** [xamarin/Xamarin.Auth#339]
# Xamarin.Auth Issue

*IF BUG, INCLUDE THIS PART:*
not found WebAuthenticatorPage.xbf

### Version

- [ ] nuget version = 1.6.0.3
- [ ] component version = 
- [ ] sample

### Steps to reproduce

1.Build
2.
3.

Platform:UWP

-	[] .NET version = 
-	[] mono version = 

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead
Can you also include a screen shot?

*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by DavidPressman** [comment]
Had same issue. Temporarily, as a bandaid for now, I copied missing files from the Win 8.1 folder to the uap folder just to get my project to build again. Obviously 1.6.0.3 has a problem as the author's nuspec does not indicate these files belong in the uap folder and they do not exist in older Xamarin.Auth uap folders I checked.

**Comment by newky2k** [comment]
@DavidPressman @iWeaverMan  was this file include in the previous versions of Xamarin.Auth?

**Comment by DavidPressman** [comment]
As I thought I indicated, the .xbf file was NOT in any of the several earlier version Xamarin.Auth UAP installed libraries I checked.
To get my program to compile I had to copy it from the Win 8.1 folder to the current UAP folder.
This obviously should never be necessary, so it appears to me the current UAP install has a bug, a bad dependency or wrong file.
I am NOT the code maintainer so cannot fix the issue, only verify it exists.
________________________________

**Comment by newky2k** [comment]
@DavidPressman brilliant thank you, i'll get @moljac  to look into adding it to the nuspec

Regards

**Comment by tpsands** [comment]
ACK. Same issue. Just upgraded from 1.6.0.2 to 1.6.0.3. Compiling iOS and Android were fine. UWP project is seeing this issue.
