### ISSUE TITLE
SSL Errors causes WebView to show blank page - Android

### ISSUE THREAD

**Issue by Iyashu5040** [xamarin/Xamarin.Auth#34]
Gingerbread does not see Facebook's security certificate as valid, and any SSL error in a webview causes it to stop loading the page. Unfortunately, GB still runs on a large amount of devices out there. The solution to this problem is the following: Override the OnReceivedSSLError method of the WebViewClient as such

```
    public override void OnReceivedSslError(WebView view, SslErrorHandler handler,SslError error)
    {
    handler.Proceed();
    }
```

I've tested this and it allows the Facebook login page to display correctly on GB devices. I know it's not very secure, I'm working on a more fine tuned version which I'll post if I get it working.

**Comment by shahidaumar** [comment]
https://stackoverflow.com/questions/12034452/monodroid-webview-loading-ssl-page

**Comment by mdmota** [comment]
And for iOS? I need a solution

**Comment by Iyashu5040** [comment]
> And for iOS? I need a solution

This issue was very specific to Android, relating to trusted SSL root certificates back in 2013. Any iOS issue is definitely unrelated to this. You should log a separate issue or look around for a solution to your problem on StackOverflow.

**Comment by mdmota** [comment]
On Android is ok. On iOS when I open the site, the browser displays this message and I can't proceed.
How to force to accept an invalid certificate in browser or webview?
https://drive.google.com/file/d/1746A43O7d1YaYgoMXp2jGZGNlB6CYMRp/view?usp=sharing
