### ISSUE TITLE
iOS 9 exception: Error Domain=NSURLErrorDomain Code=-1200

### ISSUE THREAD

**Issue by lewixlabs** [xamarin/Xamarin.Auth#347]
# Xamarin.Auth Issue (iOS v9 only)

### Version
- [x] Xamarin Forms version = 3.4.0.1008975
- [x] Xamarin.Auth nuget version = 1.6.0.3

### Platform:
-	[x] it only happens on iOS <= 9 (tested on iOS 9.3.5 with iPhone 5 32bit)
-	[x] mono version = Mono JIT compiler version 5.16.0.220
-	[x] .NET version = .Net Standard 2.0.3
-	[x] iOS SDK = 12.1

### Demo Project which demostrates this issue
https://github.com/lewixlabs/OAuth2Forms
client_id, client_secret are omitted for security reasons, contact me if you need to test

### Expected behaviour
OAuth2 authentication completed with valid access_token returned

### Actual behaviour
In webview i insert correct credentials, but after doing this, with iOS 9 only, authenticator raises error event with this stack trace:
> Error Domain=NSURLErrorDomain Code=-1200 \"An SSL error has occurred and a secure connection to the server cannot be made.\" UserInfo={NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorCodeKey=-9806, NSErrorFailingURLStringKey=https://oauthidp.polimi.it/oauthidp/oauth2/token, _kCFStreamErrorDomainKey=3, NSUnderlyingError=0x17481700 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 \"(null)\" UserInfo={_kCFNetworkCFStreamSSLErrorOriginalValue=-9806, _kCFStreamErrorCodeKey=-9806, _kCFStreamErrorDomainKey=3, _kCFStreamPropertySSLClientCertificateState=0}}, NSErrorFailingURLKey=https://oauthidp.polimi.it/oauthidp/oauth2/token}

Anyone can suggest me:
- workaround ?
- is it a TLS connection issue?

As HttpClient, on iOS side, i tried all options without luck (everytime rebuilding project and deleting obj/bin folders)
- NSUrlSession (iOS 7+)
- Managed
- CFNetwork (iOS 6+)

Thank you for any suggestion/help, if you need more infos let me know.

Lewix

> VS bug [#738679](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/738679)

**Comment by newky2k** [comment]
@lewixlabs Could you please provide a small sample which demonstrates this problem, so that we can investigate.

Regards

**Comment by moljac** [comment]
I need to take a look, but this will be a problem because of older OS version.

Triaged as "Low priority"

**Comment by lewixlabs** [comment]
Hi @moljac, thanks for your feedback.
Yes i know it's an older version of iOS, infact in my company I have only one iPhone 5 with iOS 9 which we don't update to test these cases.

Let me know (lewixlabs AT gmail DOT com) if you need OAuth2 credentials to test it.

Hi,
Lewix

**Comment by moljac** [comment]
triaging it as "Low Priority"

In order to speed up the bugfixing, please add link to the repo with minimal sample (with removed sensitve data)

**Comment by lewixlabs** [comment]
Yes i already added, please check details on my first post

Il giorno Ven 30 Nov 2018, 18:44 moljac <notifications@github.com> ha
scritto:

**Comment by lewixlabs** [comment]
Hi,
i know this issue has a low priority, this post only to know if you need oauth2 credentials to test with my demo project
https://github.com/lewixlabs/OAuth2Forms

Thanks

**Comment by lewixlabs** [comment]
I close this issue (low priority/no response from oauth team and months ago I updated my app compatible from iOS 10 only.
