### ISSUE TITLE
WebRedirectAuthenticator calling Completed event twice upon successful authentication

### ISSUE THREAD

**Issue by icnatejackson** [xamarin/Xamarin.Auth#35]
The WebRedirectAuthenticator is calling the Completed event twice upon successful authentication.

This behavior can be seen in the iOS and Android Xamarin.Auth Samples as the OAuth2Authenticator inherits from WebRedirectAuthenticator.

Update:  This may have already been addressed by another commit.  If I remove the Xamarin.Auth 1.1 component and instead add a .Net assembly reference to a version I built from current GitHub source, the Completed event only fires once.

Update to my Update:  Sorry.  The report above of this issue possibly being fixed didn't pan out.  The 2nd event does fire with a direct assembly reference, but not every time.  This issue doesn't occur every time, but it occurs often enough that it should easily be reproducible.

**Comment by mariolobar** [comment]
I am having the same problem using the last version 1.5.0.3 and presenters. I'm not using native UI.
I can reproduce in iOS and Android.
