### ISSUE TITLE
LinkedIn authentication redirects to Redirect url and not to app

### ISSUE THREAD

**Issue by georgethms10** [xamarin/Xamarin.Auth#361]
# Xamarin.Auth Issue

*IF BUG, INCLUDE THIS PART:*

### Version

- [ ] nuget version = 1.6.0.2 , 1.6.0.4
- [ ] component version = 
- [ ] sample = 

### Steps to reproduce

1. Tap login with linked in 
2. app navigates to Linked in page
3. After login it redirects to RedirectUrl 
4. It is not coming back to application callbacks

### Code

```
auth2Obj = new OAuth2Authenticator(
                isUsingNativeUI:true,
					clientId: Api.clientIdLinkedin,
					clientSecret: Api.clientSecretLinkedin,
					scope: Api.scopeLinkedin,
					authorizeUrl: new Uri(Api.authorizeUrlLinkedin),
					redirectUrl: new Uri(Api.redirectUrlLinkedin),
					accessTokenUrl: new Uri(Api.accessTokenUrlLinkedin));

			mDialog.Show();
			if (auth2Obj != null)
			{
				auth2Obj.Completed += LoginComplete;
				auth2Obj.Error += Cancel;
                auth2Obj.ShowErrors = true;
				activity.StartActivity(auth2Obj.GetUI(activity));
			}
```

Platform:
-	[] mono version = 5.10.1.47

### Expected behaviour
It should navigate back to application callbacks
either OnCompleted or Error 
### Actual behaviour
After successful authentication it navigates to the Redirect URL and stays there.

**Comment by higher-faster-better** [comment]
Why was this issue closed? @georgenthms10, you found the solution?

**Comment by Manik400** [comment]
iam building flutter app and using HTTP , flutter web auth to make request to sign in lnkedin and then in lnkdin dev redirect is not of my app it is some another website but I want my app to automatically back to my app instead of redirect URL 
or I want to have web HTTP URL 
how can resolve this
