### ISSUE TITLE
Setting response type for Oauth2Authenticator

### ISSUE THREAD

**Issue by abbotteric** [xamarin/Xamarin.Auth#42]
There does not seem to be a way to set the "response_type" when using Oauth2Authenticator. The request defaults to "token", I would like to use "code" is this possible?

**Comment by dengere** [comment]
@ermau  when i try constructor that takes clientSecret and accessTokenUrl,  completed delegation eventArgs has access_token and id_token.
how can i get "short code" instead of tokens?

**Comment by BenDevelopment** [comment]
Same question for me. How can I get the "code" istead of "id_token"?

**Comment by chinkan** [comment]
I have same issue using Xamarin.Auth with IdentityServer4, if only request for token, backend cannot get the user id. So, I need to change the request_type to "id_token token". How can I do this? Thanks!
