### ISSUE TITLE
Add a way to change the Authenticator error handler added by WebAuthenticatorActivity

### ISSUE THREAD

**Issue by brendanzagaeski** [xamarin/Xamarin.Auth#44]
[Retrying immediately after an error in WebAuthenticatorActivity authentication](https://github.com/xamarin/Xamarin.Auth/blob/master/src/Xamarin.Auth.Android/WebAuthenticatorActivity.cs#L70-L78) might be undesirable in some cases. For example, in Xamarin.Social's FacebookService, if the user does not have a `username` (`username` is optional on Facebook), [GetUsernameAsync()](https://github.com/xamarin/Xamarin.Social/blob/master/src/Xamarin.Social/Services/FacebookService.cs#L43-L60) throws an exception. The WebAuthenticatorActivity then repeatedly retries and fails, rapidly producing [many error message pop-ups](http://www.screencast.com/t/3DI7v8zwC), with no way to stop them. Currently there's no easy way to change this default behavior.

For the particular case of FacebookService, another option might be to change GetUsernameAsync() to try the `name` field if accessing the `username` field fails.

**Comment by newky2k** [comment]
no response since 2013
