### ISSUE TITLE
Refresh tokens

### ISSUE THREAD

**Issue by ermau** [xamarin/Xamarin.Auth#47]
We need to provide built in support for dealing with refresh tokens.

**Comment by WhitneyLand** [comment]
May I ask what the ETA is on this, since the PR is already available?

**Comment by erictrinh276** [comment]
Hi everyone, any update on this?

**Comment by lewixlabs** [comment]
Hi,
as I said [here](https://github.com/xamarin/Xamarin.Auth/issues/125#issuecomment-438299442) you can try my example, without OAuth2 extensions, on my [gist](https://gist.github.com/lewixlabs/6addc59de22318400a3a9691078ecb33)

Hi,
Lewix

**Comment by Redth** [comment]
Thanks, that gist is helpful for users looking to implement this.

Adding refresh token support is not currently on our roadmap but may be in the future.  For now, I suggest using the workaround mentioned above, thanks!
