### ISSUE TITLE
OAuth2 token should be passed in the header

### ISSUE THREAD

**Issue by kevin-brown** [xamarin/Xamarin.Auth#61]
As specified in RFC 6750, OAuth2 bearer tokens may be passed into a request using the `Authorization` header, request body, or url parameter.  This has been mentioned in https://github.com/xamarin/Xamarin.Auth/issues/53, but that issue is primarily for something unrelated.

---

The `Authorization` header must be supported by all servers (and in my experience, it is), as specified in the RFC:

> Clients SHOULD make authenticated requests with a bearer token using the "Authorization" request header field with the "Bearer" HTTP  authorization scheme.  Resource servers MUST support this method.
> -- [RFC 650 - 2.1](http://tools.ietf.org/html/rfc6750#section-2.1)

In the project I'm working on, we use [DOAC](https://github.com/Rediker-Software/doac) which does not implement the url parameter.  For now, this is because it isn't required and there are some challenges associated with it that we don't want to deal with.

> Because of the security weaknesses associated with the URI method (see Section 5), including the high likelihood that the URL containing the access token will be logged, it SHOULD NOT be used unless it is impossible to transport the access token in the "Authorization" request header field or the HTTP request entity-body Resource servers MAY support this method.
> -- [RFC 650 - 2.3](http://tools.ietf.org/html/rfc6750#section-2.3)

---

Interestingly, the [function for generating the header](https://github.com/xamarin/Xamarin.Auth/blob/ab74344adf08035c661db8dbc84b691c560a0632/src/Xamarin.Auth/OAuth2Request.cs#L105-L115) is implemented, but it is not used anywhere.  Instead, the url parameter is used by default, and there does not appear to be an easy way (without subclassing the request) to use the header over the query parameter.

**Comment by djonpereira** [comment]
Hi Kevin,
Did u manage to solve this issue?
I'm having the same problem... 
My implementation works fine in Postman... but when i try to get something directly from my app i get no response... I need to use the Authorize filter... and it's getting blocked on the server or not getting there at all...

**Comment by kevin-brown** [comment]
Back in 2014, we solved this by subclassing `OAuth2Request` and overriding `GetResponseAsync` in order to inject the token.

```csharp
public override Task<Response> GetResponseAsync (CancellationToken cancellationToken)
{
    // Make sure we have an account
    if (Account == null) {
        throw new InvalidOperationException ("You must specify an Account for this request to proceed");
    }

    // Sign the request before getting the response
    var req = GetPreparedWebRequest ();

    // Authorize it
    var authorization = GetAuthorizationHeader (Account);

    req.Headers [HttpRequestHeader.Authorization] = authorization;

    return base.GetResponseAsync (cancellationToken);
}
```

It's been two years and we've changed enough on our side (and `Xamarin.Auth` has changed as well) that I have no idea if this patch still works.

**Comment by djonpereira** [comment]
Thanks Kevin,
I manage to make a call using a HttpClient like so...

HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", access_token);

            HttpResponseMessage response = await client.GetAsync(new Uri(getUserUrl));
            if (response.IsSuccessStatusCode)
            {
                var responseString = await response.Content.ReadAsStringAsync();
                responseString = responseString.Replace(@"\", string.Empty).Trim(new char[] { '\"' });
                var responseJson = JObject.Parse(responseString);

                builder.SetTitle("Logged in");
                builder.SetMessage("AccessToken: " + responseJson["access_token"]);
            }
            else {
                builder.SetTitle("Error");
            }

I'll take a look at your solution...

**Comment by newky2k** [comment]
PR added to resolve this issue

**Comment by lewixlabs** [comment]
Hi,
any update about this request?

Should I use workaround by @djonpereira?
