### ISSUE TITLE
KeyChainAccountStore does not use ValueData for storing the secret

### ISSUE THREAD

**Issue by nextmunich** [xamarin/Xamarin.Auth#66]
From reading the source in KeyChainAccountStore, it looks like no secret information is ever stored in the secret field ValueData. Instead, all reads/writes on data to be stored are performed on the Generic field of the SecRecord - which, AFAIK, will not be encrypted when stored in the keychain.

**Comment by marktap** [comment]
I realize this is a pretty old submission :-( sorry for the delay. This will be fixed in the next release.
