### ISSUE TITLE
Add support for the non-browser based OAuth 2 workflows

### ISSUE THREAD

**Issue by ErikSchierboom** [xamarin/Xamarin.Auth#7]
At the moment, this library supports three-legged authentication. However, there are also OAuth 2 servers that support two-legged authentication. It would be great if these could also be included in your library.

The three workflows are:
- Resource owner credentials grant (http://tools.ietf.org/html/rfc6749#section-4.3)
- Client credentials grant (http://tools.ietf.org/html/rfc6749#section-4.4)
- Refreshing access tokens (http://tools.ietf.org/html/rfc6749#section-6)

**Comment by Redth** [comment]
Thanks for the suggestion, not currently on our roadmap.
