### ISSUE TITLE
Facebook success.html displays instead of going back to previous page

### ISSUE THREAD

**Issue by coreyperkins** [xamarin/Xamarin.Auth#70]
Authentication is successful but I an redirected to a white page with the following red text.

"SECURITY WARNING: Please treat the URL above as you would your password and do not share it with anyone. See the Facebook Help Center for more information."

I have only tried this on iOS at this point. It seems as if Xamarin.Auth needs to know to ignore this.

I also documented this at: http://forums.xamarin.com/discussion/25183/xamarin-forms-xamarin-auth-and-facebook?new=1

**Comment by vineelsunny** [comment]
I'm also facing the same problem,can anyone please provide any solution.Thank you!!

**Comment by gramland** [comment]
I have the same problem in ios.

**Comment by newky2k** [comment]
@coreyperkins  is this still an issue

**Comment by newky2k** [comment]
no response for two weeks
