### ISSUE TITLE
Problem when exchanging code for access token (only on Android).

### ISSUE THREAD

**Issue by jacksierkstra** [xamarin/Xamarin.Auth#74]
Hello,

I'm not really sure if I found a bug or if it is another problem. I'm using this library in my Xamarin.iOS and my Xamarin.Android application. I have the following flow on both of my apps:

Im facing problems in the OAuth2 flow when I want to exchange my code for an access token.

We have two networks, where one of the networks is outside of the company network. When I'm on the company network, the process goes fine on the Android Emulator and when I'm on the outside network, the process goes fine ONLY on IOS. So, to sum up what I tested already:

**Outside network** 

| Device | Result |
| --- | --- |
| Macbook (iOS simulator) | Ok |
| Macbook (Android simulator) | 400 Bad request while exchanging code for access token |
| Android tablet | 400 Bad request while exchanging code for access token |

**Company network** 

| Device | Result |
| --- | --- |
| Windows (Android emulator (Xamarin Player) ) | Ok |
| Windows (Android emulator (Genymotion) ) | Ok |

I really don't know where to begin to debug this problem, because in all scenario's, they're using the same code `OAuth2Authenticator`:
https://github.com/xamarin/Xamarin.Auth/blob/master/src/Xamarin.Auth/OAuth2Authenticator.cs

Since I'm getting the `Ok` flow in both the outside and the company network, I'm suspecting this isn't a network issue.

I hope somebody can point me in the right direction!

Best regards,
Jack Sierkstra

**Comment by PranavHouston** [comment]
@jacksierkstra Do you recall what the configuration error on your side was? I am getting the exact same problem.

**Comment by jacksierkstra** [comment]
@PranavHouston Hello Pranav. Unfortunately I do not. In fact, I am not doing any development in C# anymore, instead I moved to Java development.. Sorry.

**Comment by PranavHouston** [comment]
@jacksierkstra  No worries Jack. Figured out my issue. My redirect url had an extra "/" at the end (after it was type casted as an uri)
