### ISSUE TITLE
Unhandled Android.Views.WindowManagerBadTokenException in Xamarin.Utilities.Android.ActivityEx

### ISSUE THREAD

**Issue by Dzoge** [xamarin/Xamarin.Auth#75]
I'm currently facing the following unhandled exception 
`"Android.Views.WindowManagerBadTokenException: Unable to add window -- token android.os.BinderProxy@6564d270 is not valid; is your activity running?"`

That is being raised when `alert.Show ();` is called in `Xamarin.Utilities.Android.ActivityEx.ShowError (this Activity activity, string title, string message)` method.

There is no way to catch the exception from the application itself so it causes my app to crash.

In my application I
- create a TaskCompletionSource
- add Completed handler to Authenticator
- get UI with GetUI()
- start the intent
- await until TaskCompletionSource returns (assigned in Completed event handler)

as soon as I receive the result I exit the function. The error is called back later, when OnRedirectPageLoaded tries to call my callback page. So the error is raised and application crashes. 

In order to make it work I cloned the source, wrapped the `alert.Show ();` with exception handler and now I'm using locally built DLL file instead.

**Comment by fa15073** [comment]
assume you are using oauth2, the real problem seems to be OnRedirectPageLoaded are called twice (both on page loading and on page loaded) and the 2nd RequestAccessTokenAsync fails (triggering ShowError)
not sure what Commit cde10c4e was the right fix or the fix should be in oauth2 authenticator
but you can always override the current implementation to fix this

**Comment by ali4ever4** [comment]
so is there any solution other than i do like what @Dzoge  said putting alert.show() in try catch after getting the whole source code into my machine ?!

**Comment by JakubHolovsky** [comment]
Is this still relevant? They seem to have added the try + catch:

```
try
      {
        AlertDialog.Builder builder = new AlertDialog.Builder((Context) activity);
        builder.SetMessage(message);
        builder.SetTitle(title);
        builder.SetNeutralButton("OK", (EventHandler<DialogClickEventArgs>) ((s, e) => ((Dialog) s).Cancel()));
        builder.Create().Show();
      }
      catch (Exception ex)
      {
        string message1 = ex.Message;
        Log.Error("Xamarin.Auth", "Error: {0}:{1} - {2}", (object) title, (object) message, (object) message1);
      }
```

**Comment by newky2k** [comment]
seems resolved by https://github.com/xamarin/Xamarin.Auth/pull/155
