### ISSUE TITLE
New component version with ShowUIErrors feature

### ISSUE THREAD

**Issue by siacomuzzi** [xamarin/Xamarin.Auth#83]
Hi,

Could you please submit a new component version? I need the `ShowUIErrors` feature: https://github.com/xamarin/Xamarin.Auth/blame/master/src/Xamarin.Auth/WebAuthenticator.cs#L62

Thanks!

**Comment by moljac** [comment]
@prashantvc 

Component store is being shutdown, so it is reasonable to close this one.

**Comment by prashantvc** [comment]
@siacomuzzi The Component store is shutting down, you can find the new versions of the Xamarin.Auth on nuget here https://www.nuget.org/packages/Xamarin.Auth/
