### ISSUE TITLE
Does not build with Xamarin.Auth sample for iOS:

### ISSUE THREAD

**Issue by erickrivas** [xamarin/Xamarin.Auth#85]
getting the following error on Xamarin Studio 5.5.4 when building the out of the box Xamarin.Auth sample for iOS:

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets: Error: Error executing task CompileSceneKitAssetsTask: Task does not have property "ProjectDir" defined (Xamarin.Auth.iOS)

Any advice or pointers on how to resolve would be appreciated.

**Comment by prashantvc** [comment]
@erickrivas We made lot of changes since this issue is reported. Do you still see this issue? Could you share the diagnostic build output if you still see this issue?

**Comment by prashantvc** [comment]
Because we have not received a reply to our request for more information, I am marking this issue as closed. If you are still encountering this issue on the latest version of the plugin, please don’t hesitate to reopen the ticket with the requested information. Thanks!
