### ISSUE TITLE
Publish as a nuget package that contains the binarys directly

### ISSUE THREAD

**Issue by yufeih** [xamarin/Xamarin.Auth#86]
Xamarin.Auth on nuget is currently published as a forwarder to a component in Xamarin store.

Please embed the binarys directly inside the nupkg just like Android support libraries.

**Comment by prashantvc** [comment]
We are deprecating the Component store, and migrating all the existing [packages to Nuget](https://blog.xamarin.com/hello-nuget-new-home-xamarin-components/). 
Now complete package should be available in the nuget ste
