### ISSUE TITLE
Issue with Yammer Authentication 

### ISSUE THREAD

**Issue by rkshnair** [xamarin/Xamarin.Auth#89]
The authentication is working fine with iPhone 5, 6 etc but When viewed on an iPhone 4 screen the Approve and Deny buttons are off the bottom of the screen(the screen appear after authentication), and the page isn't scrollable, so you can never get to them.

Are we missing something, or is this process completely impossible in a browser of that resolution. Any workarounds ?

**Comment by newky2k** [comment]
Added to the Issue Triage Process project
