### ISSUE TITLE
SSL on iOS9

### ISSUE THREAD

**Issue by bpress** [xamarin/Xamarin.Auth#95]
Hello.

I'm using Xamarin.Auth to add "Login with Facebook" functionality to my app.
When running in iOS 9, immediately after presenting the GetUI() View Controller, I get an SSL error alert dialog. The application log is reporting "NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)".

**Comment by durandt** [comment]
Documentation here:
https://developer.apple.com/library/mac/documentation/CoreFoundation/Reference/CFStreamConstants/#//apple_ref/doc/constant_group/CFStream_Error_Domain_Constants_CFHost_

Says the `StreamErrorDomainSSL` error codes are defined in:
`Security/SecureTransport.h`

That you can find in XCode or here: 
http://www.opensource.apple.com/source/libsecurity_ssl/libsecurity_ssl-36800/lib/SecureTransport.h

-9802 would be `errSSLFatalAlert`, which doesn't help much I guess.

**Comment by bpress** [comment]
Hi,
I saw that codes, and it looks like some https call is complaining about invalid ssl certificates.
However I cannot pinpoint which call is failing.
I should debug using the source code rather than the compiled assembly.
Strange enough, the very same app is working in ios 8 (both simulator and real device),
but fails under ios 9.

[cid:566BD339-1A17-483F-ADC0-ECC106D6CA47]<http://www.msoft.it/>

Supporto Tecnico
supporto@msoft-italia.com<mailto:supporto@msoft-italia.com>

B-Press S.r.l.
Piazzale Lombardia, 4 - 28100 Novara (NO)
T. +39 0321 499508 - F.+39 0321 492974



Da: Thibault Durand
Risposta: "xamarin/Xamarin.Auth"
Data: lunedì 21 settembre 2015 09:04
A: "xamarin/Xamarin.Auth"
Cc: Supporto MSoft
Oggetto: Re: [Xamarin.Auth] SSL on iOS9 (#95)


Documentation here:
https://developer.apple.com/library/mac/documentation/CoreFoundation/Reference/CFStreamConstants/#//apple_ref/doc/constant_group/CFStream_Error_Domain_Constants_CFHost_

Says the StreamErrorDomainSSL error codes are defined in:
Security/SecureTransport.h

That you can find in XCode or here:
http://www.opensource.apple.com/source/libsecurity_ssl/libsecurity_ssl-36800/lib/SecureTransport.h

-9802 would be errSSLFatalAlert, which doesn't help much I guess.

**Comment by bpress** [comment]
Hi.
I've tried to debug the source code, and it looks like the error is thrown by the UIWebView inside the WebAuthenticationController, while trying to load this url:

https://m.facebook.com/dialog/oauth/?client_id=1658202597727497&redirect_uri=http%3A%2F%2Fwww.facebook.com%2Fconnect%2Flogin_success.html&response_type=token&scope=email&state=jyeybgpamkrsaodc

I've tried to completely disable ATS by adding the following keys to Info.plist, but with no success at all:

`<key>NSAppTransportSecurity</key>
<dict>
	<key>NSAllowArbitraryLoads</key>
	<true/>
</dict>`

Again, this occurs only in iOS 9

**Comment by LithiumToast** [comment]
Add this to your plist

```
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSExceptionDomains</key>
  <dict>
    <key>facebook.com</key>
    <dict>
      <key>NSIncludesSubdomains</key> <true/>        
      <key>NSThirdPartyExceptionRequiresForwardSecrecy</key> <false/>
    </dict>
    <key>fbcdn.net</key>
    <dict>
      <key>NSIncludesSubdomains</key> <true/>
      <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>  <false/>
    </dict>
    <key>akamaihd.net</key>
    <dict>
      <key>NSIncludesSubdomains</key> <true/>
      <key>NSThirdPartyExceptionRequiresForwardSecrecy</key> <false/>
    </dict>
  </dict>
</dict>
```

**Comment by mws580** [comment]
I made the info.plist changes and now I get 
"Given URL is not allowed bt the Application configuration.  One or more given URLs is not allowed by Apps settings.

**Comment by jamesmontemagno** [comment]
Opt out with until you figure out all the urls.

<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>

**Comment by mws580** [comment]
Opting out using the keys above still gives me the error

**Comment by newky2k** [comment]
this is a issue for ios apps with ATS no xamarin.auth
