### ISSUE TITLE
Problem specific to Android Marshmallow - error "The authentication or decryption has failed"

### ISSUE THREAD

**Issue by ltaljaard** [xamarin/Xamarin.Auth#98]
Method OAuth2Request works fine on iOS and Android Lollipop (Google API 22) and under iOS 9. However it returns the following error on Android Marshmallow (Google API 23).

I have created a test project to demonstrate the issue: https://github.com/ltaljaard/FacebookLoginTest

All you need to do is to enter a valid Facebook App ID on line 100 of the Renderers\LoginPageRenderer.cs, (in the Droid project) and enter a valid Azure site in line 103 of the same file. Then first run the app using Lollipop to confirm that everything works, then run it using Marshmallow to confirm that this is a Marshmallow-specific issue.

Here are the details of the exception:

[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Net.WebException: Error: SendFailure (The authentication or decryption has failed.) ---> System.IO.IOException: The authentication or decryption has failed. ---> System.NullReferenceException: Object reference not set to an instance of an object
[MonoDroid] at System.Net.Sockets.NetworkStream.BeginWrite (System.Byte[] buffer, Int32 offset, Int32 size, System.AsyncCallback callback, System.Object state) [0x00088] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/System/System.Net.Sockets/NetworkStream.cs:255
[MonoDroid] at Mono.Security.Protocol.Tls.RecordProtocol.BeginSendRecord (ContentType contentType, System.Byte[] recordData, System.AsyncCallback callback, System.Object state) [0x00026] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/RecordProtocol.cs:765
[MonoDroid] at Mono.Security.Protocol.Tls.RecordProtocol.BeginSendRecord (HandshakeType handshakeType, System.AsyncCallback callback, System.Object state) [0x00017] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/RecordProtocol.cs:727
[MonoDroid] at Mono.Security.Protocol.Tls.SslClientStream.BeginNegotiateHandshake (System.AsyncCallback callback, System.Object state) [0x0004c] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslClientStream.cs:411
[MonoDroid] at Mono.Security.Protocol.Tls.SslStreamBase.BeginNegotiateHandshake (Mono.Security.Protocol.Tls.InternalAsyncResult asyncResult) [0x00021] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslStreamBase.cs:488
[MonoDroid] --- End of inner exception stack trace ---
[MonoDroid] at Mono.Security.Protocol.Tls.SslStreamBase.BeginNegotiateHandshake (Mono.Security.Protocol.Tls.InternalAsyncResult asyncResult) [0x00067] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslStreamBase.cs:503
[MonoDroid] at Mono.Security.Protocol.Tls.SslStreamBase.BeginWrite (System.Byte[] buffer, Int32 offset, Int32 count, System.AsyncCallback callback, System.Object state) [0x0007f] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslStreamBase.cs:847
[MonoDroid] at System.Net.WebConnection.BeginWrite (System.Net.HttpWebRequest request, System.Byte[] buffer, Int32 offset, Int32 size, System.AsyncCallback cb, System.Object state) [0x0005f] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/System/System.Net/WebConnection.cs:1054
[MonoDroid] --- End of inner exception stack trace ---
[MonoDroid] at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x0005e] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/System/System.Net/HttpWebRequest.cs:944
[MonoDroid] at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (IAsyncResult iar, System.Func`2 endFunction, System.Action`1 endAction, System.Threading.Tasks.Task`1 promise, Boolean requiresSynchronization) [0x00014] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/threading/Tasks/FutureFactory.cs:552
[MonoDroid] --- End of inner exception stack trace ---
[MonoDroid] at System.Threading.Tasks.Task.ThrowIfExceptional (Boolean includeTaskCanceledExceptions) [0x00014] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2168
[MonoDroid] at System.Threading.Tasks.Task`1[TResult].GetResultCore (Boolean waitCompletionNotification) [0x00034] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Future.cs:568
[MonoDroid] at System.Threading.Tasks.Task`1[TResult].get_Result () [0x00000] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Future.cs:535
[MonoDroid] at Xamarin.Auth.Request.<GetResponseAsync>m__0 (System.Threading.Tasks.Task`1 resTask) [0x00000] in <filename unknown>:0
[MonoDroid] at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2[TAntecedentResult,TResult].InnerInvoke () [0x00027] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:207
[MonoDroid] at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2523
[MonoDroid] ---> (Inner Exception #0) System.Net.WebException: Error: SendFailure (The authentication or decryption has failed.) ---> System.IO.IOException: The authentication or decryption has failed. ---> System.NullReferenceException: Object reference not set to an instance of an object
[MonoDroid] at System.Net.Sockets.NetworkStream.BeginWrite (System.Byte[] buffer, Int32 offset, Int32 size, System.AsyncCallback callback, System.Object state) [0x00088] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/System/System.Net.Sockets/NetworkStream.cs:255
[MonoDroid] at Mono.Security.Protocol.Tls.RecordProtocol.BeginSendRecord (ContentType contentType, System.Byte[] recordData, System.AsyncCallback callback, System.Object state) [0x00026] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/RecordProtocol.cs:765
[MonoDroid] at Mono.Security.Protocol.Tls.RecordProtocol.BeginSendRecord (HandshakeType handshakeType, System.AsyncCallback callback, System.Object state) [0x00017] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/RecordProtocol.cs:727
[MonoDroid] at Mono.Security.Protocol.Tls.SslClientStream.BeginNegotiateHandshake (System.AsyncCallback callback, System.Object state) [0x0004c] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslClientStream.cs:411
[MonoDroid] at Mono.Security.Protocol.Tls.SslStreamBase.BeginNegotiateHandshake (Mono.Security.Protocol.Tls.InternalAsyncResult asyncResult) [0x00021] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslStreamBase.cs:488
[MonoDroid] --- End of inner exception stack trace ---
[MonoDroid] at Mono.Security.Protocol.Tls.SslStreamBase.BeginNegotiateHandshake (Mono.Security.Protocol.Tls.InternalAsyncResult asyncResult) [0x00067] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslStreamBase.cs:503
[MonoDroid] at Mono.Security.Protocol.Tls.SslStreamBase.BeginWrite (System.Byte[] buffer, Int32 offset, Int32 count, System.AsyncCallback callback, System.Object state) [0x0007f] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslStreamBase.cs:847
[MonoDroid] at System.Net.WebConnection.BeginWrite (System.Net.HttpWebRequest request, System.Byte[] buffer, Int32 offset, Int32 size, System.AsyncCallback cb, System.Object state) [0x0005f] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/System/System.Net/WebConnection.cs:1054
[MonoDroid] --- End of inner exception stack trace ---
[MonoDroid] at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x0005e] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/System/System.Net/HttpWebRequest.cs:944
[MonoDroid] at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (IAsyncResult iar, System.Func`2 endFunction, System.Action`1 endAction, System.Threading.Tasks.Task`1 promise, Boolean requiresSynchronization) [0x00014] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/threading/Tasks/FutureFactory.cs:552 <---
[MonoDroid] --- End of inner exception stack trace ---
[MonoDroid] at ImAvailMobileApp.Droid.LoginPageRenderer+<OnElementChanged>c__async0+<OnElementChanged>c__AnonStorey1.<>m__1 (System.Object sender, Xamarin.Auth.AuthenticatorCompletedEventArgs eventArgs) [0x001a1] in /Users/louistaljaard/Documents/Projects/Azure/ImAvailMobileApp/Droid/Renderers/LoginPageRenderer.cs:145
[MonoDroid] at (wrapper delegate-invoke) System.EventHandler`1[Xamarin.Auth.AuthenticatorCompletedEventArgs]:invoke_void_object_TEventArgs (object,Xamarin.Auth.AuthenticatorCompletedEventArgs)
[MonoDroid] at Xamarin.Auth.Authenticator+<OnSucceeded>c__AnonStorey0.<>m__0 () [0x00024] in <filename unknown>:0
[MonoDroid] at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/2098/3efa14c4/source/monodroid/src/Mono.Android/src/Java.Lang/Thread.cs:36
[MonoDroid] at Java.Lang.IRunnableInvoker.n_Run (IntPtr jnienv, IntPtr native__this) [0x00009] in /Users/builder/data/lanes/2098/3efa14c4/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Java.Lang.IRunnable.cs:71
[MonoDroid] at (wrapper dynamic-method) System.Object:f651e514-fdf8-49f3-98a6-c75aae9ffdb4 (intptr,intptr)
[MonoDroid] ---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.Net.WebException: Error: SendFailure (The authentication or decryption has failed.) ---> System.IO.IOException: The authentication or decryption has failed. ---> System.NullReferenceException: Object reference not set to an instance of an object
[MonoDroid] at System.Net.Sockets.NetworkStream.BeginWrite (System.Byte[] buffer, Int32 offset, Int32 size, System.AsyncCallback callback, System.Object state) [0x00088] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/System/System.Net.Sockets/NetworkStream.cs:255
[MonoDroid] at Mono.Security.Protocol.Tls.RecordProtocol.BeginSendRecord (ContentType contentType, System.Byte[] recordData, System.AsyncCallback callback, System.Object state) [0x00026] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/RecordProtocol.cs:765
[MonoDroid] at Mono.Security.Protocol.Tls.RecordProtocol.BeginSendRecord (HandshakeType handshakeType, System.AsyncCallback callback, System.Object state) [0x00017] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/RecordProtocol.cs:727
[MonoDroid] at Mono.Security.Protocol.Tls.SslClientStream.BeginNegotiateHandshake (System.AsyncCallback callback, System.Object state) [0x0004c] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslClientStream.cs:411
[MonoDroid] at Mono.Security.Protocol.Tls.SslStreamBase.BeginNegotiateHandshake (Mono.Security.Protocol.Tls.InternalAsyncResult asyncResult) [0x00021] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslStreamBase.cs:488
[MonoDroid] --- End of inner exception stack trace ---
[MonoDroid] at Mono.Security.Protocol.Tls.SslStreamBase.BeginNegotiateHandshake (Mono.Security.Protocol.Tls.InternalAsyncResult asyncResult) [0x00067] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslStreamBase.cs:503
[MonoDroid] at Mono.Security.Protocol.Tls.SslStreamBase.BeginWrite (System.Byte[] buffer, Int32 offset, Int32 count, System.AsyncCallback callback, System.Object state) [0x0007f] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslStreamBase.cs:847
[MonoDroid] at System.Net.WebConnection.BeginWrite (System.Net.HttpWebRequest request, System.Byte[] buffer, Int32 offset, Int32 size, System.AsyncCallback cb, System.Object state) [0x0005f] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/System/System.Net/WebConnection.cs:1054
[MonoDroid] --- End of inner exception stack trace ---
[MonoDroid] at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x0005e] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/System/System.Net/HttpWebRequest.cs:944
[MonoDroid] at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (IAsyncResult iar, System.Func`2 endFunction, System.Action`1 endAction, System.Threading.Tasks.Task`1 promise, Boolean requiresSynchronization) [0x00014] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/threading/Tasks/FutureFactory.cs:552
[MonoDroid] --- End of inner exception stack trace ---
[MonoDroid] at System.Threading.Tasks.Task.ThrowIfExceptional (Boolean includeTaskCanceledExceptions) [0x00014] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2168
[MonoDroid] at System.Threading.Tasks.Task`1[TResult].GetResultCore (Boolean waitCompletionNotification) [0x00034] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Future.cs:568
[MonoDroid] at System.Threading.Tasks.Task`1[TResult].get_Result () [0x00000] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Future.cs:535
[MonoDroid] at Xamarin.Auth.Request.<GetResponseAsync>m__0 (System.Threading.Tasks.Task`1 resTask) [0x00000] in <filename unknown>:0
[MonoDroid] at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2[TAntecedentResult,TResult].InnerInvoke () [0x00027] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:207
[MonoDroid] at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2523
[MonoDroid] ---> (Inner Exception #0) System.Net.WebException: Error: SendFailure (The authentication or decryption has failed.) ---> System.IO.IOException: The authentication or decryption has failed. ---> System.NullReferenceException: Object reference not set to an instance of an object
[MonoDroid] at System.Net.Sockets.NetworkStream.BeginWrite (System.Byte[] buffer, Int32 offset, Int32 size, System.AsyncCallback callback, System.Object state) [0x00088] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/System/System.Net.Sockets/NetworkStream.cs:255
[MonoDroid] at Mono.Security.Protocol.Tls.RecordProtocol.BeginSendRecord (ContentType contentType, System.Byte[] recordData, System.AsyncCallback callback, System.Object state) [0x00026] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/RecordProtocol.cs:765
[MonoDroid] at Mono.Security.Protocol.Tls.RecordProtocol.BeginSendRecord (HandshakeType handshakeType, System.AsyncCallback callback, System.Object state) [0x00017] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/RecordProtocol.cs:727
[MonoDroid] at Mono.Security.Protocol.Tls.SslClientStream.BeginNegotiateHandshake (System.AsyncCallback callback, System.Object state) [0x0004c] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslClientStream.cs:411
[MonoDroid] at Mono.Security.Protocol.Tls.SslStreamBase.BeginNegotiateHandshake (Mono.Security.Protocol.Tls.InternalAsyncResult asyncResult) [0x00021] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslStreamBase.cs:488
[MonoDroid] --- End of inner exception stack trace ---
[MonoDroid] at Mono.Security.Protocol.Tls.SslStreamBase.BeginNegotiateHandshake (Mono.Security.Protocol.Tls.InternalAsyncResult asyncResult) [0x00067] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslStreamBase.cs:503
[MonoDroid] at Mono.Security.Protocol.Tls.SslStreamBase.BeginWrite (System.Byte[] buffer, Int32 offset, Int32 count, System.AsyncCallback callback, System.Object state) [0x0007f] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslStreamBase.cs:847
[MonoDroid] at System.Net.WebConnection.BeginWrite (System.Net.HttpWebRequest request, System.Byte[] buffer, Int32 offset, Int32 size, System.AsyncCallback cb, System.Object state) [0x0005f] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/System/System.Net/WebConnection.cs:1054
[MonoDroid] --- End of inner exception stack trace ---
[MonoDroid] at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x0005e] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/mcs/class/System/System.Net/HttpWebRequest.cs:944
[MonoDroid] at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (IAsyncResult iar, System.Func`2 endFunction, System.Action`1 endAction, System.Threading.Tasks.Task`1 promise, Boolean requiresSynchronization) [0x00014] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/threading/Tasks/FutureFactory.cs:552 <---
[MonoDroid] <---

**Comment by newky2k** [comment]
@ltaljaard is this still an issue

**Comment by ltaljaard** [comment]
@newky2k I don't know, I have moved over to the Azure AD type authentication. I guess you could run the provided sample and check?

**Comment by newky2k** [comment]
@ltaljaard  thanks for the update

**Comment by newky2k** [comment]
no longer needed
