### ISSUE TITLE
Pinterest Auth2 throwing error only on iOS

### ISSUE THREAD

**Issue by dzolnjan** [xamarin/Xamarin.Auth#99]
Pinterest Auth2 is throwing error on web browser startup > Invalid state from server. Possible forgery!

It works fine with exactly same auth details on Android !

```
var auth = new OAuth2Authenticator(
      clientId: "4811462802426315117",
      scope: "",
      authorizeUrl: new Uri("https://api.pinterest.com/oauth/"),
      redirectUrl: new Uri("https://danielztestapp.com/"));
```

https://github.com/xamarin/Xamarin.Auth/blob/master/src/Xamarin.Auth/OAuth2Authenticator.cs#L250

![pinterest auth error](https://cloud.githubusercontent.com/assets/3109244/12224897/f045d450-b7fb-11e5-9e74-15b0c19880d0.png)

**Comment by newky2k** [comment]
@dzolnjan is this still an issue

**Comment by newky2k** [comment]
no response for two weeks, closing
